/*
 * content/geschmacklos.js — content for Geschmacklos (Cards Against Humanity style, NSFW, adults only)
 *
 * EDIT ME. Pure content. A bilingual { de, en } bundle with NO category pools —
 * one fixed set per language. `prompts` are the black cards: each is a sentence
 * with exactly ONE blank written as ___. `answers` are the white cards: short,
 * punchy noun phrases that fill that blank. This deck runs filthy by default —
 * keep the CAH voice: absurd, dark, crude, German-millennial. de is the primary
 * voice, en mirrors it in count and meaning. No slurs, no minors, nothing illegal.
 */
(function (global) {
  "use strict";

  var GESCHMACKLOS = {
    de: {
      prompts: [
        "Womit würde ich niemals auf einem ersten Date angeben? ___",
        "___ — das ist mein Toxic Trait.",
        "Der wahre Grund für meinen letzten Breakup: ___.",
        "In der Notaufnahme musste ich einmal ___ erklären.",
        "Mein Therapeut hat aufgehört, weil ich ständig über ___ rede.",
        "Was steckt wirklich in meinem Suchverlauf? ___.",
        "Beim Sex denke ich heimlich an ___.",
        "Meine Dating-App-Bio sollte eigentlich lauten: ___.",
        "Ich habe meine Ex verlassen wegen ___.",
        "Mein größter Ick ist ___.",
        "Das Erste, was ich morgens tue: ___.",
        "Statt zur Therapie zu gehen, gönne ich mir einfach ___.",
        "Der Grund, warum ich nicht mehr eingeladen werde: ___.",
        "Mein Liebesleben besteht nur noch aus ___.",
        "Was ich brauche, um den Montag zu überleben: ___.",
        "In meinem Testament vererbe ich vor allem ___.",
        "Meine größte Red Flag beim ersten Kennenlernen: ___.",
        "Was ich um 4 Uhr morgens am meisten liebe: ___.",
        "Das Romantischste, was ich je gesagt habe: ___.",
        "Mein Körper läuft aktuell zu 90 % auf ___.",
        "Das dunkelste Geheimnis meiner Beziehung ist ___.",
        "Mein Gott ist ___.",
        "Der Grund, warum mich meine Mutter enttäuscht ansieht: ___.",
        "Zu jedem Grillen bringe ich immer ___ mit.",
        "Meine Superkraft im Bett ist ___.",
        "Der wahre Grund, warum ich noch bei Hotel Mama wohne: ___.",
        "Auf meinem Grabstein soll stehen: ___.",
        "Was mich sofort anmacht: ___.",
        "Mein ganzes Selbstwertgefühl basiert auf ___.",
        "Das Peinlichste, was ich je gegoogelt habe: ___.",
        "Statt Sport zu machen, betreibe ich lieber ___.",
        "Wofür ich mich prostituieren würde: ___.",
        "Dafür erwartet mein Sugar Daddy ___.",
        "Auf jeder Party bin ich der Typ mit ___.",
        "Was ich meinem Date bis nach dem Sex verschweige: ___.",
        "Meine OnlyFans-Nische wäre ___.",
        "Mein spirituelles Erwachen kam durch ___.",
        "Das Letzte, woran ich vor dem Einschlafen denke: ___.",
        "Der wahre Grund, warum ich zu spät komme: ___.",
        "Meine ganze Kindheit erklärt sich durch ein Wort: ___.",
        "Was ich beim Sex auf keinen Fall hören will: ___.",
        "Mein Beziehungsstatus ist kompliziert wegen ___.",
        "Das Highlight jedes Familienessens: ___.",
        "In meiner Bewerbung habe ich schamlos gelogen über ___.",
        "Meine geheimste Sucht ist ___.",
        "Was mein Ex an mir am meisten vermisst: ___.",
        "Der Grund, warum ich überall blockiert wurde: ___.",
        "Mein Liebesbeweis sieht so aus: ___.",
        "Was ich niemals meinen Eltern zeigen würde: ___.",
        "Mein Leben wäre besser ohne ___.",
        "Das versauteste Kompliment, das ich je bekommen habe: ___.",
        "Wenn ich betrunken bin, werde ich zu ___.",
        "Mein Personal Trainer hat aufgegeben wegen ___.",
        "Was ich im letzten Beziehungsgespräch gestanden habe: ___.",
        "Mein Alltag besteht zu 80 % aus ___.",
        "Der wahre Grund, warum ich Single bin: ___.",
        "Beim ersten Date rieche ich immer nach ___.",
        "Mein größtes Talent, das auf keinem Lebenslauf steht: ___.",
        "Was mich nachts wach hält: ___.",
        "Mein letzter Gedanke vor dem Tod wird sein: ___.",
      ],
      answers: [
        "Ein durchschnittlicher Penis",
        "Drei Bier und schlechte Entscheidungen",
        "Mein Vaterkomplex",
        "Ein Döner um 4 Uhr morgens",
        "Apache 207 auf voller Lautstärke",
        "Mein OnlyFans-Zweitaccount",
        "Hotel Mama mit 32",
        "Mein toxischer Ex",
        "Eine gesunde Portion Selbsthass",
        "Ein UFC-Kämpfer im Halbfinale",
        "Der Nippel meiner Nachbarin",
        "Ein spontaner Steuerbetrug",
        "Mein innerer Monolog beim Sex",
        "Der letzte Rest meiner Würde",
        "Ein durchschaubarer Fuckboy",
        "Zu viel Selbstbräuner",
        "Ein missglücktes Dickpic",
        "Ein sehr spezifischer Kink",
        "Ein Glas Aperol um 11 Uhr vormittags",
        "Mein Bausparvertrag",
        "Ungeklärte Mutterprobleme",
        "Ein Nacktfoto an die falsche Person",
        "Ein bisschen zu viel Selbstliebe",
        "Ein FKK-Strand in der Nebensaison",
        "Ein Vibrator mit fast leerem Akku",
        "Mein Beckenboden",
        "Eine unangebrachte Erektion",
        "Ein sehr feuchter Traum",
        "Ein bisschen Kokain zum Geburtstag",
        "Die peinliche Stille nach dem Sex",
        "Ein Liter Jägermeister",
        "Eine spontane Steuerprüfung",
        "Eine schlecht getarnte Beule in der Hose",
        "Ein durchgeschwitztes Trikot vom FC Bayern",
        "Die Verwandtschaft an Weihnachten",
        "Mein Bierbauch mit Persönlichkeit",
        "Ein billiger One-Night-Stand",
        "Eine ungeplante Schwangerschaftsangst",
        "Ein sehr optimistisches Kondom-Format",
        "Der Geruch von Verzweiflung",
        "Zwei Waschbären im Trenchcoat",
        "Ein Thermomix mit Bewusstsein",
        "Ein Delfin mit eindeutigen Absichten",
        "Ein Ikea-Regal, das zurückstarrt",
        "Ein Meerschweinchen im Führungsteam",
        "Ein Pferd im Wartezimmer der Sparkasse",
        "Ein Praktikant mit Gottkomplex",
        "Ein sprechender Rossmann-Kassenbon",
        "Ein Bobbycar auf der Autobahn",
        "Ein Aldi-Prospekt als Aphrodisiakum",
        "Ein Schwan mit eigenem Anwalt",
        "Ein Kühlschrank, der meine Geheimnisse kennt",
        "Ein enttäuschender Handjob",
        "Ein Dreier, der zum Zweier schrumpfte",
        "Zwei Finger und viel Optimismus",
        "Ein Orgasmus, den ich vorgetäuscht habe",
        "Ein Kondom, das in ihr geblieben ist",
        "Ein spontaner Ständer in der U-Bahn",
        "Meine faltigen Hoden",
        "Ein Penis mit deutlichem Linksdrall",
        "Ein Deepthroat mit Würgereflex",
        "Der Fleck auf der Matratze",
        "Sabber auf einem fremden Kopfkissen",
        "Ein Schwanz, der beim Sex einschläft",
        "Sex bei ausgeschaltetem Licht aus gutem Grund",
        "Ein Rollenspiel, das eskaliert ist",
        "Die Sexpuppe im Kleiderschrank",
        "Ein Analplug in der Waschmaschine",
        "Ein Fußjob unterm Esstisch bei Oma",
        "Eine Fessel am Bettpfosten und keine Ausrede",
        "Die Ex, die im Bett den falschen Namen stöhnt",
        "Ein viel zu feuchter Kuss auf den Hals",
        "Mein Suchverlauf, Kategorie \"seltsam\"",
        "Ein Furz mit Nachdruck",
        "Der Bremsstreifen in meiner Unterhose",
        "Durchfall in einem Zugklo ohne Papier",
        "Ein Pups, der kein Pups war",
        "Blähungen im vollen Fahrstuhl",
        "Ein verstopftes Klo beim ersten Date",
        "Meine Hinterlassenschaft in der Autobahnraststätte",
        "Ein brauner Streifen im Freibad",
        "Beim Niesen in die Hose geschissen",
        "Der offene Sarg von Oma",
        "Der Herzinfarkt mitten beim Sex",
        "Allein sterben mit vierzehn Katzen",
        "Die Urne auf dem Kaminsims",
        "Mein Testament, in dem alle enterbt sind",
        "Meine Organe auf dem Schwarzmarkt",
        "Ein Abschiedsbrief in Emojis",
        "Meine Beerdigung mit schlechter Beteiligung",
        "Mein Wille zu leben, aktuell im Minus",
        "Ein Nachruf, den keiner lesen will",
        "Die Midlife-Crisis mit 27",
        "Der Duft vom Pflegeheim",
        "Ein AfD-Onkel beim Weihnachtsessen",
        "Die politischen Ansichten meines Vaters nach dem dritten Bier",
        "Ein Querdenker mit Aluhut",
        "Ein Reichsbürger mit selbstgemachtem Ausweis",
        "Die WhatsApp-Uni meines Onkels",
        "Der Pfarrer, der die Hand zu lange hält",
        "Ein Beichtstuhl mit WLAN",
        "Ein Bibelvers als Ausrede",
        "Ein Impfpass mit verdächtigen Lücken",
        "Ein Vaterschaftstest mit Überraschung",
        "Das Kind, das dem Postboten ähnelt",
        "Die Enttäuschung in Papas Augen",
        "Der Grund, warum dich keiner zurückruft",
        "Eine ehrliche Meinung über dein Aussehen",
        "Deine Mutter, aber als Kompliment gemeint",
        "Der Moment, in dem ich \"Mama\" zu meinem Chef sagte",
        "Ein Ständer bei der Rückenmassage von Tante Gerda",
        "Dem Busfahrer \"Ich liebe dich\" sagen",
        "Ein versehentliches Like auf ein Foto von 2014",
        "Die Sprachnachricht, die an die Falsche ging",
        "Der Klaps auf den Po vom Chef",
        "Zurückwinken zu jemandem, der jemand anderen meinte",
        "Ein Ballermann-Eimer um 10 Uhr morgens",
        "Die Mallorca-Schlägerei am Flughafen",
        "Deutsche Bürokratie als Fetisch",
        "Ein Termin beim Bürgeramt in diesem Jahrzehnt",
        "Ein GEZ-Brief als Mahnung fürs Leben",
        "Die Deutsche Bahn und ihre Pünktlichkeit",
        "Der Nachbar, der die Mülltrennung kontrolliert",
        "Malle ohne Kondom",
        "Ein Kasten Oettinger als Liebesbeweis",
        "FKK mit den Nachbarn im Schrebergarten",
        "Die Sparkasse, die meinen Kredit ablehnt",
        "Ein Grillabend mit Bratwurst und Verrat",
        "Ein Schrebergarten mit zu vielen Regeln",
        "Das Oktoberfest und mein Erbrochenes",
        "Ein Späti-Bier um 8 Uhr morgens",
        "Ein Schwitzkasten von Khabib",
        "Ein Ellbogen von Conor McGregor",
        "Der Schweiß aus einem UFC-Käfig",
        "Ein Elfmeter in der 90. Minute verschossen",
        "Der VAR, der mein Leben überprüft",
        "Ein ausgebrannter Fußballprofi mit Zigarette",
        "Ein Cutman für meine Gefühle",
        "Ein Kopfstoß in der Kreisliga",
        "Helene Fischer bei meiner Beerdigung",
        "Ein Auto-Tune für mein Stöhnen",
        "Ballermann-Hits in Dauerschleife",
        "Ein Schlagerhit über meine Ex",
        "Eine Line vom Klodeckel",
        "Ein Ketaminloch auf dem Festival",
        "Zwei Pillen und ein Kaugummi",
        "Ein Joint zum Frühstück",
        "MDMA und ehrliche Gefühle",
        "Ein Blackout mit Zeugen",
        "Ein Filterloser um 7 Uhr morgens",
        "Ein Nasenhaar, das nach Freiheit strebt",
        "Der Käse unter der Vorhaut",
        "Ein Achselschweißfleck bis zum Gürtel",
        "Ein Pickel an einer sehr privaten Stelle",
        "Mundgeruch nach Zwiebelmett",
        "Rasierpickel am Sack",
        "Zehennägel im Bett",
        "Die Hämorrhoiden meines Chefs",
        "Ein Furunkel auf der Pobacke",
        "Meine unbehandelte Depression",
        "Ein Nervenzusammenbruch im Rewe",
        "Meine Tabletten mit einem Glas Wein",
        "Ein Weinkrampf in der Umkleidekabine",
        "Eine Panikattacke beim Elternabend",
        "Bürgergeld und große Träume",
        "Meine Schufa mit einem Eintrag zu viel",
        "Ein leerer Kühlschrank am 28. des Monats",
        "Ein Pfandflaschen-Imperium",
        "Ein Kredit für ein Sofa",
        "Ein Threesome mit meinem besten Freund und viel Reue",
        "Der Vibrator meiner Mitbewohnerin",
        "Sperma auf der guten Couch",
        "Ein Pornotab, den meine Mutter gefunden hat",
        "Meine Ex und ihr neuer, jüngerer Freund",
        "Ein Sextape, das keiner sehen wollte",
        "Eine Erektionsstörung im entscheidenden Moment",
        "Ein Quickie, der 40 Sekunden dauerte",
        "Ein Clown auf einer Beerdigung",
        "Der letzte Wille meiner Katze",
        "Ein Sarg mit Ratenzahlung",
        "Ein Dönerladen als Beichtstuhl",
        "Der Nacktscanner am Flughafen",
        "Der Amtsarzt und seine kalten Hände",
        "Eine Prostatauntersuchung mit zu viel Blickkontakt",
        "Ein Zungenkuss von der Ex-Schwiegermutter",
        "Ein Tinder-Date, das aussah wie das Profilbild, nur schlimmer",
        "Die Wahrheit hinter meinem \"Ich arbeite von zu Hause\"",
        "Mein Google-Kalender voller Lügen",
        "Ein Dosenravioli-Dinner bei Kerzenlicht",
        "Ein Sixpack aus Leberkäse",
        "Ein sehr enges Höschen bei 35 Grad",
        "Meine Vorliebe für ältere, wohlhabende Menschen",
        "Ein Nacktselfie im Umkleidespiegel",
        "Ein Zungenpiercing mit Hintergedanken",
        "Mein Beckenboden nach drei Kindern",
        "Ein Ganzkörperschauer beim Gedanken an meine Ex",
        "Ein Klaps, der als Zärtlichkeit gemeint war",
        "Ein Nasenspray, das mein Leben regiert",
        "Ein Kater mit Existenzkrise",
        "Der Typ, der beim Sex \"Papa\" hören will",
        "Ein sehr detaillierter Fußfetisch",
        "Ein Bausparvertrag als Vorspiel",
        "Die Deutsche Bahn als Beziehungsmodell",
        "Ein Grillmeister mit zu viel Testosteron",
        "Ein Vollbart mit Essensresten von gestern",
        "Meine Suchanfrage \"ist das normal?\"",
        "Ein spontanes Geständnis im Vollrausch",
        "Der Fleck, den ich nicht erklären kann",
        "Ein Kondomautomat, der mein Geld gefressen hat",
        "Meine Ex, die jetzt Achtsamkeitscoach ist",
        "Ein Herpesbläschen vor dem Fototermin",
        "Der Zahnarzt, der zu nah steht",
        "Ein feuchter Traum über den Kollegen",
        "Meine Vorhaut und ihre Geheimnisse",
        "Ein Sonnenbrand an einer sehr blassen Stelle",
        "Der Muskelkrampf beim Orgasmus",
        "Ein Ex, der jetzt Podcaster ist",
        "Meine Sammlung ungelesener Mahnungen",
        "Ein Toupet, das im Wind verrutscht",
        "Ein Wutanfall im Ikea-Parkhaus",
        "Ein sehr unangenehmes Kribbeln da unten",
        "Ein Klingelton, der mitten in der Beerdigung losgeht",
        "Ein Furz während der Yogastunde",
        "Ein sehr direktes Feedback von meinem Proktologen",
        "Ein Nippelblitzer in der Videokonferenz",
        "Mein Browserverlauf im Inkognito-Modus",
        "Ein Bierbauch, der bei jedem Schritt wackelt",
        "Ein viel zu frühes \"Ich liebe dich\" nach zwei Wochen",
        "Ein Blasenschwäche-Moment beim Lachen",
        "Die Kontrolle über meinen Darm verlieren",
        "Ein Aufstoßen, das nach Döner von gestern schmeckt",
        "Ein sehr unpassender Lachanfall bei der Trauerfeier",
        "Mein Ex-Chef und seine \"Umarmungspolitik\"",
        "Ein feuchter Handschlag vom Personaler",
        "Ein Kotzeimer beim Ballermann",
        "Ein Klogang, den man durch die Wand hört",
        "Ein Schluckauf mitten im Heiratsantrag",
        "Ein sehr fragwürdiger Fleck auf dem Autositz",
        "Ein Ex, der sich einen Sportwagen gekauft hat",
        "Mein linker Hoden, der tiefer hängt",
        "Ein Sextoy, das lauter ist als geplant",
        "Ein Herpesausbruch pünktlich zum Date",
        "Ein sehr direkter Kommentar von meiner Oma",
        "Meine Google-Bewertung als Mensch",
        "Ein leerer Blick beim Dirty Talk",
        "Ein Rückfall in alte Muster mit dem Ex",
        "Ein Pornoheft unter Opas Matratze",
        "Ein Sonnenstich beim FKK-Wandern",
        "Mein Puls, wenn Mama anruft",
        "Ein Kondom im Gullideckel nach der Party",
        "Ein sehr ehrliches Selbstgespräch im Spiegel",
        "Ein Facetime, das zufällig angenommen wurde",
        "Mein Ex und seine neue Persönlichkeit aus dem Fitnessstudio",
        "Ein sehr langer Toilettengang während des Meetings",
        "Ein feuchter Fleck unbekannter Herkunft",
        "Ein Sabberfaden im Schlaf vor Zeugen",
        "Ein sehr selbstbewusster Striptease ohne Publikum",
        "Ein Anruf vom Inkasso beim Candle-Light-Dinner",
        "Mein Beitrag zur globalen Erwärmung nach einer Portion Bohnen",
        "Ein sehr gewagtes Selfie, das an alle ging",
      ],
    },
    en: {
      prompts: [
        "What would I never brag about on a first date? ___",
        "___ — that's my toxic trait.",
        "The real reason for my last breakup: ___.",
        "In the ER I once had to explain ___.",
        "My therapist quit because I kept talking about ___.",
        "What's really in my search history? ___.",
        "During sex I secretly think about ___.",
        "My dating-app bio should really just say: ___.",
        "I left my ex because of ___.",
        "My biggest ick is ___.",
        "The first thing I do every morning: ___.",
        "Instead of going to therapy, I just treat myself to ___.",
        "The reason I don't get invited anymore: ___.",
        "My love life now consists entirely of ___.",
        "What I need to survive Monday: ___.",
        "In my will, I mostly leave behind ___.",
        "My biggest red flag when we first meet: ___.",
        "What I love most at 4 a.m.: ___.",
        "The most romantic thing I've ever said: ___.",
        "My body currently runs 90 % on ___.",
        "The darkest secret in my relationship is ___.",
        "My god is ___.",
        "The reason my mother looks at me with disappointment: ___.",
        "To every barbecue I always bring ___.",
        "My superpower in bed is ___.",
        "The real reason I still live at Hotel Mum: ___.",
        "My gravestone should read: ___.",
        "What instantly turns me on: ___.",
        "My entire self-worth is based on ___.",
        "The most embarrassing thing I've ever googled: ___.",
        "Instead of working out, I'd rather practise ___.",
        "What I'd sell my body for: ___.",
        "In return, my sugar daddy expects ___.",
        "At every party I'm the guy with ___.",
        "What I hide from my date until after the sex: ___.",
        "My OnlyFans niche would be ___.",
        "My spiritual awakening came through ___.",
        "The last thing I think about before falling asleep: ___.",
        "The real reason I'm always late: ___.",
        "My entire childhood can be explained in one word: ___.",
        "What I absolutely don't want to hear during sex: ___.",
        "My relationship status is complicated because of ___.",
        "The highlight of every family dinner: ___.",
        "On my job application I shamelessly lied about ___.",
        "My most secret addiction is ___.",
        "What my ex misses most about me: ___.",
        "The reason I got blocked everywhere: ___.",
        "My idea of a love token looks like this: ___.",
        "What I'd never show my parents: ___.",
        "My life would be better without ___.",
        "The filthiest compliment I've ever received: ___.",
        "When I'm drunk I turn into ___.",
        "My personal trainer gave up because of ___.",
        "What I confessed in my last relationship talk: ___.",
        "My daily life is 80 % ___.",
        "The real reason I'm single: ___.",
        "On a first date I always smell of ___.",
        "My greatest talent that's not on any CV: ___.",
        "What keeps me up at night: ___.",
        "My last thought before death will be: ___.",
      ],
      answers: [
        "An average penis",
        "Three beers and bad decisions",
        "My daddy issues",
        "A döner at 4 a.m.",
        "Apache 207 at full volume",
        "My secret OnlyFans account",
        "Living at Hotel Mum at 32",
        "My toxic ex",
        "A healthy dose of self-loathing",
        "A UFC fighter in the semifinal",
        "My neighbour's nipple",
        "A bit of casual tax fraud",
        "My inner monologue during sex",
        "The last shred of my dignity",
        "A painfully obvious fuckboy",
        "Too much fake tan",
        "A failed dick pic",
        "A very specific kink",
        "A glass of Aperol at 11 a.m.",
        "My savings plan",
        "Unresolved mommy issues",
        "A nude sent to the wrong person",
        "A little too much self-love",
        "A nudist beach in the off-season",
        "A vibrator on low battery",
        "My pelvic floor",
        "An inappropriate erection",
        "A very wet dream",
        "A little cocaine for my birthday",
        "The awkward silence after sex",
        "A litre of Jägermeister",
        "A surprise tax audit",
        "A poorly hidden bulge in the trousers",
        "A sweat-soaked Bayern Munich jersey",
        "The relatives at Christmas",
        "My beer belly with personality",
        "A cheap one-night stand",
        "An unplanned pregnancy scare",
        "A very optimistic condom size",
        "The smell of desperation",
        "Two raccoons in a trench coat",
        "A Thermomix that gained consciousness",
        "A dolphin with clear intentions",
        "An IKEA shelf that stares back",
        "A guinea pig on the management board",
        "A horse in the bank's waiting room",
        "An intern with a god complex",
        "A talking drugstore receipt",
        "A toy car on the motorway",
        "A supermarket flyer as an aphrodisiac",
        "A swan that lawyered up",
        "A fridge that knows my secrets",
        "A disappointing handjob",
        "A threesome that shrank to a twosome",
        "Two fingers and a lot of optimism",
        "An orgasm I faked",
        "A condom that stayed inside her",
        "A spontaneous boner on the subway",
        "My wrinkly balls",
        "A penis with a distinct leftward lean",
        "A deepthroat with a gag reflex",
        "The stain on the mattress",
        "Drool on a stranger's pillow",
        "A dick that falls asleep mid-sex",
        "Sex with the lights off for a reason",
        "A role-play that escalated",
        "The sex doll in the wardrobe",
        "A butt plug in the washing machine",
        "A footjob under Grandma's dinner table",
        "A cuff on the bedpost and no excuse",
        "The ex who moans the wrong name in bed",
        "A far too wet kiss on the neck",
        "My search history, filed under \"weird\"",
        "A fart with follow-through",
        "The skid mark in my underwear",
        "Diarrhoea in a train toilet with no paper",
        "A fart that wasn't just a fart",
        "Flatulence in a packed elevator",
        "A clogged toilet on a first date",
        "What I left behind at the motorway loo",
        "A brown streak in the public pool",
        "Shitting myself while sneezing",
        "Grandma's open casket",
        "A heart attack mid-sex",
        "Dying alone with fourteen cats",
        "The urn on the mantelpiece",
        "My will, in which everyone is cut out",
        "My organs on the black market",
        "A farewell note written in emojis",
        "My funeral with a poor turnout",
        "My will to live, currently in the red",
        "An obituary nobody wants to read",
        "A midlife crisis at 27",
        "The smell of the nursing home",
        "A far-right uncle at Christmas dinner",
        "My dad's political opinions after his third beer",
        "A conspiracy nut in a tinfoil hat",
        "A sovereign citizen with a homemade ID",
        "My uncle's WhatsApp university degree",
        "The priest who holds your hand too long",
        "A confessional booth with Wi-Fi",
        "A Bible verse used as an excuse",
        "A vaccination card with suspicious gaps",
        "A paternity test with a surprise",
        "The kid that looks like the mailman",
        "The disappointment in Dad's eyes",
        "The reason nobody calls you back",
        "An honest opinion about your looks",
        "Your mum, but meant as a compliment",
        "The moment I called my boss \"Mum\"",
        "A boner during Aunt Gerda's back rub",
        "Telling the bus driver \"I love you\"",
        "An accidental like on a photo from 2014",
        "The voice note that went to the wrong person",
        "A slap on the bum from the boss",
        "Waving back at someone who meant someone else",
        "A Ballermann sangria bucket at 10 a.m.",
        "The Mallorca brawl at the airport",
        "German bureaucracy as a fetish",
        "A city-hall appointment this decade",
        "A TV-licence letter haunting me for life",
        "Deutsche Bahn and its punctuality",
        "The neighbour who polices the recycling",
        "Mallorca without a condom",
        "A crate of cheap beer as a token of love",
        "Getting naked with the neighbours in the allotment",
        "The bank rejecting my loan",
        "A barbecue with sausages and betrayal",
        "An allotment with too many rules",
        "Oktoberfest and my vomit",
        "A corner-shop beer at 8 a.m.",
        "A headlock from Khabib",
        "An elbow from Conor McGregor",
        "The sweat from a UFC cage",
        "A penalty missed in the 90th minute",
        "The VAR reviewing my life",
        "A washed-up footballer with a cigarette",
        "A cutman for my feelings",
        "A headbutt in the Sunday league",
        "Schlager music at my funeral",
        "Auto-Tune for my moaning",
        "Party anthems on endless repeat",
        "A cheesy pop hit about my ex",
        "A line off the toilet lid",
        "A K-hole at the festival",
        "Two pills and a piece of gum",
        "A joint for breakfast",
        "MDMA and honest feelings",
        "A blackout with witnesses",
        "An unfiltered cigarette at 7 a.m.",
        "A nose hair reaching for freedom",
        "The cheese under the foreskin",
        "An armpit stain down to the belt",
        "A pimple in a very private place",
        "Breath that reeks of raw onion and pork",
        "Razor bumps on the balls",
        "Toenail clippings in the bed",
        "My boss's haemorrhoids",
        "A boil on the buttock",
        "My untreated depression",
        "A breakdown in the supermarket aisle",
        "My meds washed down with wine",
        "A crying fit in the changing room",
        "A panic attack at the parents' evening",
        "Welfare cheques and big dreams",
        "My credit score with one strike too many",
        "An empty fridge on the 28th of the month",
        "An empire built on deposit bottles",
        "A loan taken out for a sofa",
        "A threesome with my best friend and a lot of regret",
        "My flatmate's vibrator",
        "Cum on the good couch",
        "A porn tab my mother found",
        "My ex and her new, younger boyfriend",
        "A sex tape nobody wanted to see",
        "Erectile dysfunction at the crucial moment",
        "A quickie that lasted 40 seconds",
        "A clown at a funeral",
        "My cat's last will and testament",
        "A coffin bought on instalments",
        "A kebab shop as a confessional",
        "The naked scanner at airport security",
        "The public doctor and his cold hands",
        "A prostate exam with too much eye contact",
        "A french kiss from the ex-mother-in-law",
        "A Tinder date who looked like the profile pic, only worse",
        "The truth behind my \"I work from home\"",
        "My Google calendar full of lies",
        "A candlelit dinner of canned ravioli",
        "A six-pack made of Leberkäse",
        "Very tight underwear in 35-degree heat",
        "My taste for older, wealthy people",
        "A nude selfie in the changing-room mirror",
        "A tongue piercing with an agenda",
        "My pelvic floor after three kids",
        "A full-body shudder at the thought of my ex",
        "A smack that was meant to be tender",
        "A nasal spray that runs my life",
        "A hangover with an existential crisis",
        "The guy who wants to be called \"Daddy\" in bed",
        "A very detailed foot fetish",
        "A savings contract as foreplay",
        "Deutsche Bahn as a relationship model",
        "A grill master with too much testosterone",
        "A full beard with yesterday's food in it",
        "My search query \"is this normal?\"",
        "A drunken confession out of nowhere",
        "The stain I can't explain",
        "A condom machine that ate my money",
        "My ex who is now a mindfulness coach",
        "A cold sore right before the photo shoot",
        "The dentist who stands too close",
        "A wet dream about a coworker",
        "My foreskin and its secrets",
        "Sunburn on a very pale spot",
        "A muscle cramp mid-orgasm",
        "An ex who is now a podcaster",
        "My collection of unopened debt letters",
        "A toupee slipping in the wind",
        "A meltdown in the IKEA car park",
        "A very unpleasant tingle down there",
        "A ringtone going off in the middle of a funeral",
        "A fart during yoga class",
        "Some very direct feedback from my proctologist",
        "A nip slip during the video call",
        "My browser history in incognito mode",
        "A beer belly that wobbles with every step",
        "A very premature \"I love you\" after two weeks",
        "A weak-bladder moment mid-laugh",
        "Losing all control of my bowels",
        "A burp that tastes of last night's kebab",
        "A very ill-timed giggle at the memorial",
        "My ex-boss and his \"hugging policy\"",
        "A very clammy handshake from the recruiter",
        "A puke bucket at Ballermann",
        "A toilet trip you can hear through the wall",
        "Hiccups in the middle of a proposal",
        "A very questionable stain on the car seat",
        "An ex who bought himself a sports car",
        "My left ball, which hangs lower",
        "A sex toy louder than expected",
        "A herpes outbreak right on cue for the date",
        "A very blunt comment from my grandma",
        "My Google review as a human being",
        "A blank stare during dirty talk",
        "A relapse into old patterns with my ex",
        "A porn mag under Grandpa's mattress",
        "Sunstroke on a nude hike",
        "My heart rate when Mum calls",
        "A condom down the drain after the party",
        "A very honest pep talk in the mirror",
        "A FaceTime accidentally answered",
        "My ex and his new gym personality",
        "A very long toilet break during the meeting",
        "A damp patch of unknown origin",
        "A string of drool in my sleep, with witnesses",
        "A very confident striptease with no audience",
        "A call from the debt collector during the candlelit dinner",
        "My contribution to global warming after a portion of beans",
        "A very risqué selfie that went out to everyone",
      ],
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.Geschmacklos = GESCHMACKLOS;
})(window);
