/*
 * content/geschmacklos.js — content for Geschmacklos (Cards Against Humanity style, NSFW, adults only)
 *
 * EDIT ME. Pure content. A bilingual { de, en } bundle with NO category pools —
 * one fixed set per language. `prompts` are the black cards: each is a sentence
 * with exactly ONE blank written as ___. `answers` are the white cards: short,
 * punchy noun phrases that fill that blank. Mix tame and filthy; keep the CAH
 * voice — absurd, dark, German-millennial. de is the primary voice, en mirrors
 * it in count and meaning. No slurs, no minors, nothing illegal.
 */
(function (global) {
  "use strict";

  var GESCHMACKLOS = {
    de: {
      prompts: [
        "Womit würde ich niemals auf einem ersten Date angeben? ___",
        "___ — das ist mein Toxic Trait.",
        "Der wahre Grund für meinen letzten Breakup: ___.",
        "In der Notaufnahme musste ich einmal ___ erklären.",
        "Mein Therapeut hat aufgehört, weil ich ständig über ___ rede.",
        "Was steckt wirklich in meinem Suchverlauf? ___.",
        "Beim Sex denke ich heimlich an ___.",
        "Meine Dating-App-Bio sollte eigentlich lauten: ___.",
        "Ich habe meine Ex verlassen wegen ___.",
        "Mein größter Ick ist ___.",
        "Das Erste, was ich morgens tue: ___.",
        "Statt zur Therapie zu gehen, mache ich einfach ___.",
        "Der Grund, warum ich nicht mehr eingeladen werde: ___.",
        "Mein Liebesleben besteht nur noch aus ___.",
        "Was ich brauche, um klarzukommen: ___.",
        "In meinem Testament vererbe ich vor allem ___.",
        "Mein Red Flag beim ersten Kennenlernen: ___.",
        "Was ich um 4 Uhr morgens am meisten liebe: ___.",
        "Das Romantischste, was ich je gesagt habe: ___.",
        "Mein Körper läuft aktuell zu 90 % auf ___.",
        "Das dunkelste Geheimnis meiner Beziehung ist ___.",
        "Mein Gott ist ___.",
        "Der Grund, warum mich meine Mutter enttäuscht ansieht: ___.",
        "Zu jedem Grillen bringe ich immer ___ mit.",
        "Meine Superkraft im Bett ist ___.",
        "Der wahre Grund, warum ich noch bei Hotel Mama wohne: ___.",
        "Auf meinem Grabstein soll stehen: ___.",
        "Was mich sofort anmacht: ___.",
        "Mein ganzes Selbstwertgefühl basiert auf ___.",
        "Das Peinlichste, was ich je gegoogelt habe: ___.",
        "Statt Sport zu machen, betreibe ich ___.",
        "Was ich für Geld tun würde: ___.",
        "Dafür erwartet mein Sugar Daddy ___.",
        "Auf jeder Party bin ich der Typ mit ___.",
        "Was ich meinem Date verschweige: ___.",
        "Meine OnlyFans-Nische wäre ___.",
        "Mein spirituelles Erwachen kam durch ___.",
        "Das Letzte, woran ich vor dem Einschlafen denke: ___.",
        "Der wahre Grund, warum ich zu spät komme: ___.",
        "Meine Kindheit erklärt sich durch ein Wort: ___.",
        "Was ich beim Sex auf keinen Fall hören will: ___.",
        "Mein Beziehungsstatus ist kompliziert wegen ___.",
        "Das Highlight jedes Familienessens: ___.",
        "In meiner Bewerbung habe ich gelogen über ___.",
        "Meine geheime Sucht ist ___.",
        "Was mein Ex an mir am meisten vermisst: ___.",
        "Der Grund, warum ich blockiert wurde: ___.",
        "Mein Liebesbeweis sieht so aus: ___.",
        "Was ich niemals meinen Eltern zeigen würde: ___.",
        "Mein Leben wäre besser ohne ___.",
        "Das versauteste Kompliment, das ich je bekommen habe: ___.",
        "Wenn ich betrunken bin, werde ich zu ___.",
        "Mein Personal Trainer hat aufgegeben wegen ___.",
        "Was ich in meinem letzten Beziehungsgespräch gestanden habe: ___.",
        "Mein Alltag besteht zu 80 % aus ___.",
        "Der Grund, warum ich Single bin: ___.",
        "Beim ersten Date rieche ich immer nach ___.",
        "Mein größtes Talent, das auf keinem Lebenslauf steht: ___.",
        "Was mich nachts wach hält: ___.",
        "Mein letzter Gedanke vor dem Tod wird sein: ___.",
      ],
      answers: [
        "Ein durchschnittlicher Penis",
        "Emotionale Unerreichbarkeit",
        "Der Gruppenchat",
        "Drei Bier und schlechte Entscheidungen",
        "Mein Vaterkomplex",
        "Ein Döner um 4 Uhr morgens",
        "Ungelöste Bindungsprobleme",
        "Ein zu enthusiastischer Handschlag",
        "Apache 207 auf voller Lautstärke",
        "Mein OnlyFans-Zweitaccount",
        "Hotel Mama mit 32",
        "Passiv-aggressive Sprachnachrichten",
        "Ein halbherziges Sixpack",
        "Die Steuererklärung von 2019",
        "Ungewaschene Bettwäsche",
        "Mein toxischer Ex",
        "Eine gesunde Portion Selbsthass",
        "Zwei Gramm Selbstbewusstsein",
        "Ein UFC-Kämpfer im Halbfinale",
        "Der Nippel meiner Nachbarin",
        "Vier Energydrinks auf nüchternen Magen",
        "Ein feuchter Händedruck",
        "Meine ungefilterte Meinung",
        "Ein spontaner Steuerbetrug",
        "Die Playlist meiner Trennung",
        "Ein Bauchnabelpiercing aus 2008",
        "Mein innerer Monolog beim Sex",
        "Eine App, die meinen Schlaf trackt",
        "Der letzte Rest meiner Würde",
        "Ein aggressiver Kaufrausch nachts",
        "Die Erwartungen meiner Mutter",
        "Ein durchschaubarer Fuckboy",
        "Mein Serotoninmangel",
        "Ein Tinder-Match von vor drei Jahren",
        "Zu viel Selbstbräuner",
        "Ein missglücktes Dickpic",
        "Meine unbezahlten Rechnungen",
        "Ein Kilo Nutella",
        "Die Bundesliga-Tabelle",
        "Ein sehr spezifischer Kink",
        "Meine emotionale Verfügbarkeit von 2 %",
        "Ein Glas Aperol um 11 Uhr vormittags",
        "Der Klügere gibt nach — also nie ich",
        "Ein durchgeschwitztes MMA-Trikot",
        "Mein Bausparvertrag",
        "Ungeklärte Mutterprobleme",
        "Ein Nacktfoto an die falsche Person",
        "Die WhatsApp-Gruppe meiner Familie",
        "Ein bisschen zu viel Selbstliebe",
        "Mein Cortisolspiegel",
        "Ein FKK-Strand in der Nebensaison",
        "Die Reste vom Junggesellenabschied",
        "Ein sehr langer Blickkontakt",
        "Mein Prokrastinations-Talent",
        "Ein leeres Bankkonto mit Stil",
        "Zwei linke Füße auf der Tanzfläche",
        "Ein aufdringlicher Body-Spray-Nebel",
        "Meine Google-Suche um 3 Uhr nachts",
        "Ein Vibrator mit fast leerem Akku",
        "Der Duft von altem Bier",
        "Ein motivierendes Zitat auf Instagram",
        "Mein Beckenboden",
        "Eine unangebrachte Erektion",
        "Der Hype um Apache 207",
        "Ein Sixpack direkt aus der Dose",
        "Meine gescheiterte Diät",
        "Ein Screenshot, den ich nie hätte machen sollen",
        "Die Schulden bei meinen Freunden",
        "Ein sehr feuchter Traum",
        "Mein Impuls, alles hinzuschmeißen",
        "Ein missverstandenes Kompliment",
        "Die Erwartungshaltung an mich selbst",
        "Ein aufgeblähter Bauch nach dem Döner",
        "Mein Selbstmitleid am Sonntag",
        "Ein illegal geparktes Auto",
        "Der Geruch von Verzweiflung",
        "Ein bisschen Kokain zum Geburtstag",
        "Meine Steuerklasse",
        "Ein Fußballspiel, das ich verloren habe",
        "Die peinliche Stille nach dem Sex",
        "Ein sehr direkter Blick nach unten",
        "Mein innerer Schweinehund",
        "Ein aufblasbares Einhorn im Pool",
        "Die Zunge meiner Ex",
        "Ein Liter Jägermeister",
        "Mein narzisstischer Zug",
        "Eine dubiose Überweisung",
        "Der Bizeps meines Personal Trainers",
        "Ein billiges Parfüm aus dem Drogeriemarkt",
        "Meine Angst vor Nähe",
        "Ein spontaner Rückfall",
        "Die Kommentarspalte auf YouTube",
        "Ein aggressiv gutes Aftershave",
        "Mein letzter Funken Selbstachtung",
        "Ein sehr peinlicher Suchbegriff",
        "Die Schwiegermutter in spe",
        "Ein durchtrainierter UFC-Ringrichter",
        "Meine chronische Erschöpfung",
        "Ein Kater, der drei Tage dauert",
        "Der Gedanke an meine Ex um Mitternacht",
        "Ein zu großzügiges Trinkgeld",
        "Mein Bedürfnis nach Bestätigung",
        "Eine spontane Steuerprüfung",
        "Der Bauch nach zwei Portionen Pommes",
        "Ein sehr enthusiastischer Kuss vom Hund",
        "Meine Unfähigkeit, Nein zu sagen",
        "Ein trauriger Solo-Moment",
        "Die Rechnung, die niemand zahlen will",
        "Ein billiger Sekt aus dem Tetrapak",
        "Mein zu langer Blick in den Ausschnitt",
        "Ein bisschen zu viel Zunge",
        "Die Selbstzweifel um 2 Uhr nachts",
        "Ein Sixpack, aber nur aus Bier",
        "Mein peinlicher Musikgeschmack",
        "Eine schlecht getarnte Beule in der Hose",
        "Der Anruf meiner Mutter am Sonntag",
        "Ein sehr feuchtes Missverständnis",
        "Meine Angststörung mit Charme",
        "Ein durchgeschwitztes Trikot vom FC Bayern",
        "Der letzte Schluck aus der Flasche",
        "Ein zu enger Jeansknopf",
        "Mein Drang, alles zu ghosten",
        "Eine unangemessene Umarmung",
        "Der Geruch nach Döner und Reue",
        "Ein sehr detailliertes Sexträumchen",
        "Meine emotionale Achterbahn",
        "Ein bisschen Selbstsabotage",
        "Die Verwandtschaft an Weihnachten",
        "Ein aufgezwungenes Kompliment",
        "Mein Bierbauch mit Persönlichkeit",
        "Ein Nachtisch, den ich nicht verdient habe",
        "Der Gruppenchat meiner Ex-WG",
        "Ein sehr fragwürdiges Tattoo",
        "Meine Steuer-Rückstände",
        "Ein feuchtfröhlicher Junggesellinnenabschied",
        "Der Blick meines Personal Trainers",
        "Ein bisschen Fremdscham",
        "Meine unrealistischen Erwartungen",
        "Ein durchgelegenes Sofa nach der Trennung",
        "Der Rausch nach vier Aperol Spritz",
        "Ein sehr spontanes Nacktbaden",
        "Mein Bedürfnis, geliebt zu werden",
        "Eine peinlich lange Sprachnachricht",
        "Der Kloß im Hals beim Ex-Song",
        "Ein zu selbstsicherer Fuckboy",
        "Meine dünne Haut",
        "Ein billiger One-Night-Stand",
        "Der Wodka aus dem Gefrierfach",
        "Ein sehr durchsichtiges Kompliment",
        "Mein Drang nach Drama",
        "Eine ungeplante Schwangerschaftsangst",
        "Der Kühlschrank meiner Eltern",
        "Ein sehr enthusiastischer Applaus für mich selbst",
        "Meine chronische Verspätung",
        "Ein feuchter Waschlappen der Gefühle",
        "Der Muskelkater vom Nichtstun",
        "Ein bisschen zu ehrliches Feedback",
        "Mein innerer Boxkampf",
        "Eine sehr lange Umarmung von Fremden",
        "Der Geruch von altem Schweiß im Fitnessstudio",
        "Ein sehr peinliches Autotune-Cover",
        "Meine emotionale Steuererklärung",
        "Ein bisschen Größenwahn",
        "Der Kloß Selbstzweifel",
        "Ein feuchter Freitagabend",
        "Mein Talent, Menschen zu vergraulen",
        "Eine unangebrachte Frage beim Abendessen",
        "Der Rausch der Macht",
        "Ein sehr optimistisches Kondom-Format",
        "Meine emotionale Verstopfung",
        "Ein aggressives Bedürfnis nach Aufmerksamkeit",
        "Der Kater aller Kater",
        "Ein sehr fragwürdiger Lebenslauf",
        "Mein Fetisch für schlechte Nachrichten",
        "Eine sehr laute Nachbarschaft um Mitternacht",
        "Der letzte Rest im Kühlschrank",
        "Ein durchtrainierter Döner-Mann um 4 Uhr",
        "Meine Sammlung schlechter Ausreden",
        "Ein spontaner Heulkrampf",
        "Der ewige Optimismus meiner Dating-App",
      ],
    },
    en: {
      prompts: [
        "What would I never brag about on a first date? ___",
        "___ — that's my toxic trait.",
        "The real reason for my last breakup: ___.",
        "In the ER I once had to explain ___.",
        "My therapist quit because I kept talking about ___.",
        "What's really in my search history? ___.",
        "During sex I secretly think about ___.",
        "My dating-app bio should really just say: ___.",
        "I left my ex because of ___.",
        "My biggest ick is ___.",
        "The first thing I do every morning: ___.",
        "Instead of going to therapy, I just do ___.",
        "The reason I don't get invited anymore: ___.",
        "My love life now consists entirely of ___.",
        "What I need to cope: ___.",
        "In my will, I mostly leave behind ___.",
        "My red flag when we first meet: ___.",
        "What I love most at 4 a.m.: ___.",
        "The most romantic thing I've ever said: ___.",
        "My body currently runs 90 % on ___.",
        "The darkest secret in my relationship is ___.",
        "My god is ___.",
        "The reason my mother looks at me with disappointment: ___.",
        "To every barbecue I always bring ___.",
        "My superpower in bed is ___.",
        "The real reason I still live at Hotel Mum: ___.",
        "My gravestone should read: ___.",
        "What instantly turns me on: ___.",
        "My entire self-worth is based on ___.",
        "The most embarrassing thing I've ever googled: ___.",
        "Instead of working out, I practice ___.",
        "What I'd do for money: ___.",
        "In return, my sugar daddy expects ___.",
        "At every party I'm the guy with ___.",
        "What I hide from my date: ___.",
        "My OnlyFans niche would be ___.",
        "My spiritual awakening came through ___.",
        "The last thing I think about before falling asleep: ___.",
        "The real reason I'm always late: ___.",
        "My childhood can be explained in one word: ___.",
        "What I absolutely don't want to hear during sex: ___.",
        "My relationship status is complicated because of ___.",
        "The highlight of every family dinner: ___.",
        "On my job application I lied about ___.",
        "My secret addiction is ___.",
        "What my ex misses most about me: ___.",
        "The reason I got blocked: ___.",
        "My idea of a love token looks like this: ___.",
        "What I'd never show my parents: ___.",
        "My life would be better without ___.",
        "The filthiest compliment I've ever received: ___.",
        "When I'm drunk I turn into ___.",
        "My personal trainer gave up because of ___.",
        "What I confessed in my last relationship talk: ___.",
        "My daily life is 80 % ___.",
        "The reason I'm single: ___.",
        "On a first date I always smell of ___.",
        "My greatest talent that's not on any CV: ___.",
        "What keeps me up at night: ___.",
        "My last thought before death will be: ___.",
      ],
      answers: [
        "An average penis",
        "Emotional unavailability",
        "The group chat",
        "Three beers and bad decisions",
        "My daddy issues",
        "A döner at 4 a.m.",
        "Unresolved attachment issues",
        "An overly enthusiastic handshake",
        "Apache 207 at full volume",
        "My secret OnlyFans account",
        "Living at Hotel Mum at 32",
        "Passive-aggressive voice notes",
        "A half-hearted six-pack",
        "My 2019 tax return",
        "Unwashed bedsheets",
        "My toxic ex",
        "A healthy dose of self-loathing",
        "Two grams of self-confidence",
        "A UFC fighter in the semifinal",
        "My neighbour's nipple",
        "Four energy drinks on an empty stomach",
        "A clammy handshake",
        "My unfiltered opinion",
        "A bit of casual tax fraud",
        "My breakup playlist",
        "A belly-button piercing from 2008",
        "My inner monologue during sex",
        "An app that tracks my sleep",
        "The last shred of my dignity",
        "An aggressive late-night shopping spree",
        "My mother's expectations",
        "A painfully obvious fuckboy",
        "My serotonin deficiency",
        "A Tinder match from three years ago",
        "Too much fake tan",
        "A failed dick pic",
        "My unpaid bills",
        "A kilo of Nutella",
        "The Bundesliga table",
        "A very specific kink",
        "My 2 % emotional availability",
        "A glass of Aperol at 11 a.m.",
        "Whoever backs down first loses — so never me",
        "A sweat-soaked MMA jersey",
        "My savings plan",
        "Unresolved mommy issues",
        "A nude sent to the wrong person",
        "My family's WhatsApp group",
        "A little too much self-love",
        "My cortisol levels",
        "A nudist beach in the off-season",
        "The leftovers from a stag do",
        "A very long eye contact",
        "My talent for procrastination",
        "An empty bank account with style",
        "Two left feet on the dance floor",
        "An overpowering cloud of body spray",
        "My 3 a.m. Google search",
        "A vibrator on low battery",
        "The smell of stale beer",
        "A motivational quote on Instagram",
        "My pelvic floor",
        "An inappropriate erection",
        "The hype around Apache 207",
        "A six-pack straight out of a can",
        "My failed diet",
        "A screenshot I never should have taken",
        "The money I owe my friends",
        "A very wet dream",
        "My urge to quit everything",
        "A misread compliment",
        "The expectations I put on myself",
        "A bloated belly after the döner",
        "My Sunday self-pity",
        "An illegally parked car",
        "The smell of desperation",
        "A little cocaine for my birthday",
        "My tax bracket",
        "A football match I lost",
        "The awkward silence after sex",
        "A very direct glance downwards",
        "My inner couch potato",
        "An inflatable unicorn in the pool",
        "My ex's tongue",
        "A litre of Jägermeister",
        "My narcissistic streak",
        "A dodgy bank transfer",
        "My personal trainer's biceps",
        "Cheap drugstore perfume",
        "My fear of intimacy",
        "A spontaneous relapse",
        "The YouTube comment section",
        "Aggressively good aftershave",
        "My last spark of self-respect",
        "A very embarrassing search term",
        "My future mother-in-law",
        "A ripped UFC referee",
        "My chronic exhaustion",
        "A hangover that lasts three days",
        "Thinking about my ex at midnight",
        "An overly generous tip",
        "My need for validation",
        "A surprise tax audit",
        "My gut after two portions of fries",
        "A very enthusiastic kiss from the dog",
        "My inability to say no",
        "A sad solo moment",
        "The bill nobody wants to pay",
        "Cheap sparkling wine from a carton",
        "My lingering stare down someone's top",
        "A little too much tongue",
        "The self-doubt at 2 a.m.",
        "A six-pack, but only made of beer",
        "My embarrassing taste in music",
        "A poorly hidden bulge in the trousers",
        "My mum's Sunday phone call",
        "A very wet misunderstanding",
        "My anxiety disorder with charm",
        "A sweat-soaked Bayern Munich jersey",
        "The last swig from the bottle",
        "A jeans button done up too tight",
        "My urge to ghost everyone",
        "An inappropriate hug",
        "The smell of döner and regret",
        "A very detailed sex dream",
        "My emotional rollercoaster",
        "A bit of self-sabotage",
        "The relatives at Christmas",
        "A forced compliment",
        "My beer belly with personality",
        "A dessert I didn't deserve",
        "The group chat from my old flatshare",
        "A very questionable tattoo",
        "My tax arrears",
        "A boozy hen party",
        "The look my personal trainer gives me",
        "A bit of secondhand embarrassment",
        "My unrealistic expectations",
        "A sagged-out sofa after the breakup",
        "The buzz after four Aperol Spritz",
        "A very spontaneous skinny dip",
        "My need to be loved",
        "An embarrassingly long voice note",
        "The lump in my throat during the ex song",
        "An overconfident fuckboy",
        "My thin skin",
        "A cheap one-night stand",
        "The vodka from the freezer",
        "A very transparent compliment",
        "My craving for drama",
        "An unplanned pregnancy scare",
        "My parents' fridge",
        "A very enthusiastic round of applause for myself",
        "My chronic lateness",
        "A damp flannel of feelings",
        "Sore muscles from doing nothing",
        "A little too much honest feedback",
        "My inner boxing match",
        "A very long hug from strangers",
        "The smell of old sweat at the gym",
        "A very embarrassing autotune cover",
        "My emotional tax return",
        "A touch of megalomania",
        "The lump of self-doubt",
        "A boozy Friday night",
        "My talent for driving people away",
        "An inappropriate dinner-table question",
        "The rush of power",
        "A very optimistic condom size",
        "My emotional constipation",
        "An aggressive need for attention",
        "The hangover of all hangovers",
        "A very questionable CV",
        "My fetish for bad news",
        "A very loud neighbourhood at midnight",
        "The last thing left in the fridge",
        "A ripped döner guy at 4 a.m.",
        "My collection of bad excuses",
        "A spontaneous crying fit",
        "The eternal optimism of my dating app",
      ],
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.Geschmacklos = GESCHMACKLOS;
})(window);
