// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/geschmacklos.js — content for Geschmacklos (Cards Against Humanity style, NSFW, adults only)
 *
 * EDIT ME. Pure content. A bilingual { de, en } bundle with NO category pools —
 * one fixed set per language.
 *
 * `prompts` are the black cards: each is a sentence with ONE or TWO blanks,
 * written as ___. Most have a single blank; a handful have two (Pick 2 — the
 * host screen flags these, the player plays two cards).
 *
 * GRAMMAR RULE for DE prompts (learned at game night): answers are NOMINATIVE
 * noun phrases ("Ein Dickpic", "Der Tod") and are never inflected. A blank must
 * therefore sit in a case-neutral slot — subject, predicate after "ist/wäre",
 * or (safest) after a colon: "Der Grund: ___". NEVER put ___ behind a
 * case-governing preposition (wegen/mit/aus/zu/nach/durch/ohne/über/um/gegen…)
 * and never as a bare direct object mid-sentence ("Ich vererbe ___") — with
 * articled cards that reads wrong for the whole table and kills the flow.
 * If the blank is a lone SUBJECT with a conjugated verb, prefer plural verbs or
 * two-blank "und" constructions so plural cards ("Faltige Hoden") fit too.
 * English has no case inflection, so the en side only mirrors count & spirit.
 *
 * `answers` are the white cards. Keep them SHORT — 1-2 words on average, a bare
 * punchy noun phrase. Longer full-phrase gags are the rare exception, not the
 * rule. This deck runs filthy: absurd, dark, crude, politically incorrect,
 * German-millennial. de is the primary voice, en mirrors it in count and spirit.
 * No slurs, no hate against protected groups, no minors. Dark-noun humor about
 * shady stuff is fair game — this is CAH, not a compliance seminar.
 */
(function (global) {
  "use strict";

  var GESCHMACKLOS = {
    de: {
      prompts: [
        // --- one blank ---
        "Der peinlichste Flex auf einem ersten Date: ___.",
        "___ — das ist mein Toxic Trait.",
        "Der wahre Grund für meinen letzten Breakup: ___.",
        "Mein letzter Besuch in der Notaufnahme, kurz erklärt: ___.",
        "Mein Therapeut hat gekündigt. Mein einziges Sitzungsthema: ___.",
        "Was steckt wirklich in meinem Suchverlauf? ___.",
        "Woran ich beim Sex heimlich denke: ___.",
        "Meine Dating-App-Bio sollte eigentlich lauten: ___.",
        "Der Nachfolger meiner Ex: ___.",
        "Mein größter Ick ist ___.",
        "Das Erste, was ich morgens tue: ___.",
        "Therapie ist teuer. Mein Hausmittel: ___.",
        "Der Grund, warum ich nicht mehr eingeladen werde: ___.",
        "Mein Liebesleben, zusammengefasst: ___.",
        "Was ich brauche, um den Montag zu überleben: ___.",
        "In meinem Testament steht nur ein einziger Posten: ___.",
        "Meine größte Red Flag beim ersten Kennenlernen: ___.",
        "Was ich um 4 Uhr morgens am meisten liebe: ___.",
        "Das Romantischste, was ich je gesagt habe: ___.",
        "Der Treibstoff, auf dem mein Körper aktuell zu 90 % läuft: ___.",
        "Das dunkelste Geheimnis meiner Beziehung ist ___.",
        "Mein Gott ist ___.",
        "Der Grund, warum mich meine Mutter enttäuscht ansieht: ___.",
        "Mein Standard-Mitbringsel zu jedem Grillen: ___.",
        "Meine Superkraft im Bett ist ___.",
        "Der wahre Grund, warum ich noch bei Hotel Mama wohne: ___.",
        "Auf meinem Grabstein soll stehen: ___.",
        "Was mich sofort anmacht: ___.",
        "Das einzige Fundament meines Selbstwertgefühls: ___.",
        "Das Peinlichste, was ich je gegoogelt habe: ___.",
        "Mein einziger Sport: ___.",
        "Wofür ich mich prostituieren würde: ___.",
        "Was mein Sugar Daddy dafür erwartet: ___.",
        "Auf jeder Party bin ich bekannt für eine Sache: ___.",
        "Was ich meinem Date bis nach dem Sex verschweige: ___.",
        "Meine OnlyFans-Nische wäre ___.",
        "Der Auslöser meines spirituellen Erwachens: ___.",
        "Das Letzte, woran ich vor dem Einschlafen denke: ___.",
        "Der wahre Grund, warum ich zu spät komme: ___.",
        "Meine ganze Kindheit erklärt sich durch ein Wort: ___.",
        "Was ich beim Sex auf keinen Fall hören will: ___.",
        "Mein Beziehungsstatus: kompliziert. Der Schuldige: ___.",
        "Das Highlight jedes Familienessens: ___.",
        "Worüber ich in meiner Bewerbung schamlos gelogen habe: ___.",
        "Meine geheimste Sucht ist ___.",
        "Was mein Ex an mir am meisten vermisst: ___.",
        "Der Grund, warum ich überall blockiert wurde: ___.",
        "Mein Liebesbeweis sieht so aus: ___.",
        "Was ich niemals meinen Eltern zeigen würde: ___.",
        "Eine Sache müsste aus meinem Leben verschwinden: ___.",
        "Das versauteste Kompliment, das ich je bekommen habe: ___.",
        "Mein betrunkenes Alter Ego: ___.",
        "Mein Personal Trainer hat aufgegeben. Der Grund: ___.",
        "Was ich im letzten Beziehungsgespräch gestanden habe: ___.",
        "Mein Alltag besteht zu 80 % aus einer Sache: ___.",
        "Der wahre Grund, warum ich Single bin: ___.",
        "Mein Parfüm beim ersten Date: ___.",
        "Mein größtes Talent, das auf keinem Lebenslauf steht: ___.",
        "Was mich nachts wach hält: ___.",
        "Mein letzter Gedanke vor dem Tod wird sein: ___.",
        // --- two blanks (Pick 2) ---
        "Mein perfekter Abend: ___ und ___.",
        "In der Hölle warten nur ___ und ___.",
        "Das Rezept für eine Katastrophe: ___ plus ___.",
        "Erst ___, dann ___ — die Geschichte meines Lebens.",
        "Meine Lieblingskombination im Bett: ___ und ___.",
        "Mein Tinder-Match — versprochen: ___, geliefert: ___.",
        "Familienweihnachten: ___ und ___ gehen sich an die Gurgel.",
        "Die zwei Dauerthemen meiner Therapie: ___ und ___.",
        "Der wahre Grund für den Weltuntergang: ___ und ___.",
        "Meine Kleinanzeige — biete: ___, suche: ___.",
        "Mein Körper: oben ___, unten ___.",
        "Zwei Dinge, die niemand kombinieren sollte: ___ und ___.",
        "Meine Dating-Bio: ___, aber im Bett ___.",
        "Zum Frühstück: ___. Zum Nachtisch: ___.",
      ],
      answers: [
        // signature long ones (kept rare on purpose)
        "Ein durchschnittlicher Penis",
        "Drei Bier und schlechte Entscheidungen",
        "Der letzte Rest meiner Würde",
        "Zwei Waschbären im Trenchcoat",
        "Ein Penis mit Linksdrall",
        "Zwei Finger und viel Optimismus",
        "Ein Fußjob unterm Esstisch",
        "Der AfD-Onkel an Weihnachten",
        "Ein Döner um 4 Uhr",
        "Ein verstopftes Klo beim Date",
        // --- Sex & Körper (short) ---
        "Ein Dickpic",
        "Mein Penis",
        "Faltige Hoden",
        "Vorhautkäse",
        "Ein Analplug",
        "Feuchte Träume",
        "Ein Ständer",
        "Ein Deepthroat",
        "Ein Quickie",
        "Zu viel Sperma",
        "Erektionsstörung",
        "Ein Vibrator",
        "Mein OnlyFans",
        "Ein Fußfetisch",
        "Ein Dreier",
        "Ein Handjob",
        "Nacktfotos",
        "Ein Kondomunfall",
        "Rasierpickel am Sack",
        "Ein Zungenkuss",
        "Meine Sexpuppe",
        "Fesseln",
        "Blümchensex",
        "Ein Rohrkrepierer",
        "Ein Kink",
        "Gespieltes Stöhnen",
        "Ein Muschifurz",
        "Der Fleck",
        "Ein Seitensprung",
        "Selbstbefriedigung",
        "Ein Schamhaar im Bett",
        "Ein Aschenbecherkuss",
        "Ein Knutschfleck mit 40",
        "Ein Zungenpiercing",
        "Der Beckenboden",
        "Ein Sextape",
        "Ein Walk of Shame",
        // --- Scat / Ekel ---
        "Durchfall",
        "Ein Furz",
        "Bremsstreifen",
        "Verstopfung",
        "Hämorrhoiden",
        "Ein feuchter Pups",
        "Klopapiermangel",
        // --- Drogen & Suff ---
        "Ballermann",
        "Jägermeister",
        "Ein Blackout",
        "Etwas Koks",
        "MDMA",
        "Ein Joint",
        "Ein Ketaminloch",
        "Oettinger",
        "Restalkohol",
        "Ein Späti-Bier",
        "Ein Kotzeimer",
        // --- Deutschland (edgy) ---
        "Der Reichsbürger",
        "Ein Querdenker",
        "Der Aluhut",
        "Das Bürgeramt",
        "Die Deutsche Bahn",
        "Meine Schufa",
        "Bürgergeld",
        "Mülltrennung",
        "Der Schrebergarten",
        "Die Sparkasse",
        "Ein Nazi-Opa",
        "Die Kirchensteuer",
        "Ein Bausparvertrag",
        "Der Blitzer",
        "Ein GEZ-Brief",
        // --- Tod & Düster ---
        "Der Tod",
        "Meine Urne",
        "Ein Herzinfarkt",
        "Allein sterben",
        "Organhandel",
        "Eine Beerdigung",
        "Der Sensenmann",
        "Ein offener Sarg",
        "Ein Clown auf dem Friedhof",
        // --- Absurd ---
        "Ein Thermomix",
        "Ein Delfin",
        "Ein Ikea-Regal",
        "Ein Pony",
        "Ein Praktikant",
        "Ein Bobbycar",
        "Ein Gartenzwerg",
        "Ein Alpaka",
        "Ein Kaktus",
        "Ein Nacktmull",
        "Ein Wackeldackel",
        "Ein sprechender Kassenbon",
        // --- Psyche & gemein ---
        "Deine Mutter",
        "Papas Enttäuschung",
        "Mein Vaterkomplex",
        "Mutterprobleme",
        "Selbsthass",
        "Meine Therapie",
        "Depression",
        "Eine Panikattacke",
        "Mein toxischer Ex",
        "Dein Aussehen",
        "Bindungsangst",
        "Ein Burnout",
        "Ein Trauma",
        "Mein inneres Kind",
        "Größenwahn",
        "Fremdscham",
        // --- Pop & Promi ---
        "Apache 207",
        "Helene Fischer",
        "Ballermann-Hits",
        "Dieter Bohlen",
        "Mario Barth",
        "Der Bachelor",
        "Ein DSDS-Casting",
        "Ein Autotune-Stöhnen",
        // --- Sport ---
        "Khabib",
        "Conor McGregor",
        "Der VAR",
        "Die Kreisliga",
        "Ein Eigentor",
        "Ein Kopfstoß",
        // --- Essen (eklig) ---
        "Ein Döner",
        "Kalter Leberkäse",
        "Mettbrötchen",
        "Toast Hawaii",
        "Dosenravioli",
        "Handkäse",
        "Ein Bierbauch",
        "Schimmelbrot",
        // --- Loser-Leben & Geld ---
        "Die Miete",
        "Ein Pfandbon",
        "Ein Dispo",
        "Hotel Mama",
        "Mindestlohn",
        "Die Steuererklärung",
        "Ein Inkassobrief",
        "Der Gerichtsvollzieher",
        "Ein leerer Kühlschrank",
        // --- Dating-Elend ---
        "Ein Tinder-Date",
        "Ein Ghosting",
        "Ein Fuckboy",
        "Ein Sugar Daddy",
        "Eine Situationship",
        "Ein Ex-Rückfall",
        "Ein Schwangerschaftstest",
        // --- Hygiene & Körperhorror ---
        "Achselschweiß",
        "Mundgeruch",
        "Nasenhaare",
        "Ein Pickel",
        "Fußpilz",
        "Ohrenschmalz",
        "Ein Furunkel",
        "Käsefüße",
        "Ein Herpesbläschen",
        // --- Religion & Autorität ---
        "Der Pfarrer",
        "Ein Beichtstuhl",
        "Der Papst",
        "Ein Weihwasserbecken",
        "Der Nacktscanner",
        "Eine Prostatauntersuchung",
        "Der Amtsarzt",
        // --- Fetisch & Rotlicht ---
        "Ein Latexanzug",
        "Eine Peitsche",
        "Handschellen",
        "Ein Bordell",
        "Ein Escort",
        "Ein Spanner",
        // --- Alter & Verfall ---
        "Ein Seniorenheim",
        "Eine Zahnprothese",
        "Ein Rollator",
        "Inkontinenz",
        "Ein Treppenlift",
        // --- Internet-Typen ---
        "Ein Hater",
        "Ein Troll",
        "Ein Stalker",
        "Ein Simp",
        "Ein Incel",
        "Ein Boomer",
        "Eine Karen",
        "Ein Messie",
        // --- Körper, spontan ---
        "Ein feuchter Händedruck",
        "Ein Blähbauch",
        "Ein Lachkrampf",
        "Ein Weinkrampf bei Ikea",
        "Ein Schweißausbruch",
        "Ein Ohnmachtsanfall",
        "Ein Nippelblitzer",
      ],
    },
    en: {
      prompts: [
        // --- one blank ---
        "What would I never brag about on a first date? ___",
        "___ — that's my toxic trait.",
        "The real reason for my last breakup: ___.",
        "In the ER I once had to explain ___.",
        "My therapist quit because I kept talking about ___.",
        "What's really in my search history? ___.",
        "During sex I secretly think about ___.",
        "My dating-app bio should really just say: ___.",
        "My ex's replacement: ___.",
        "My biggest ick is ___.",
        "The first thing I do every morning: ___.",
        "Instead of going to therapy, I just treat myself to ___.",
        "The reason I don't get invited anymore: ___.",
        "My love life now consists entirely of ___.",
        "What I need to survive Monday: ___.",
        "In my will, I mostly leave behind ___.",
        "My biggest red flag when we first meet: ___.",
        "What I love most at 4 a.m.: ___.",
        "The most romantic thing I've ever said: ___.",
        "My body currently runs 90 % on ___.",
        "The darkest secret in my relationship is ___.",
        "My god is ___.",
        "The reason my mother looks at me with disappointment: ___.",
        "To every barbecue I always bring ___.",
        "My superpower in bed is ___.",
        "The real reason I still live at Hotel Mum: ___.",
        "My gravestone should read: ___.",
        "What instantly turns me on: ___.",
        "My entire self-worth is based on ___.",
        "The most embarrassing thing I've ever googled: ___.",
        "Instead of working out, I'd rather practise ___.",
        "What I'd sell my body for: ___.",
        "In return, my sugar daddy expects ___.",
        "At every party I'm the guy with ___.",
        "What I hide from my date until after the sex: ___.",
        "My OnlyFans niche would be ___.",
        "My spiritual awakening came through ___.",
        "The last thing I think about before falling asleep: ___.",
        "The real reason I'm always late: ___.",
        "My entire childhood can be explained in one word: ___.",
        "What I absolutely don't want to hear during sex: ___.",
        "My relationship status is complicated because of ___.",
        "The highlight of every family dinner: ___.",
        "On my job application I shamelessly lied about ___.",
        "My most secret addiction is ___.",
        "What my ex misses most about me: ___.",
        "The reason I got blocked everywhere: ___.",
        "My idea of a love token looks like this: ___.",
        "What I'd never show my parents: ___.",
        "My life would be better without ___.",
        "The filthiest compliment I've ever received: ___.",
        "My drunk alter ego: ___.",
        "My personal trainer gave up because of ___.",
        "What I confessed in my last relationship talk: ___.",
        "My daily life is 80 % ___.",
        "The real reason I'm single: ___.",
        "On a first date I always smell of ___.",
        "My greatest talent that's not on any CV: ___.",
        "What keeps me up at night: ___.",
        "My last thought before death will be: ___.",
        // --- two blanks (Pick 2) ---
        "My perfect evening: ___ and ___.",
        "In hell there is only ___ and ___.",
        "The recipe for disaster: ___ plus ___.",
        "First ___, then ___ — the story of my life.",
        "During sex I love to combine ___ with ___.",
        "My Tinder match promised ___, delivered ___.",
        "Family Christmas: ___ fighting with ___.",
        "My therapy is all about ___ and ___.",
        "The real reason for the apocalypse: ___ and ___.",
        "My classified ad — offering: ___, seeking: ___.",
        "My body: ___ on top, ___ down below.",
        "Two things nobody should ever combine: ___ and ___.",
        "My dating bio: ___, but in bed ___.",
        "For breakfast we had ___, for dessert ___.",
      ],
      answers: [
        // signature long ones (kept rare on purpose)
        "An average penis",
        "Three beers and bad decisions",
        "The last shred of my dignity",
        "Two raccoons in a trench coat",
        "A penis with a leftward lean",
        "Two fingers and a lot of optimism",
        "A footjob under the dinner table",
        "A far-right uncle at Christmas",
        "A döner at 4 a.m.",
        "A clogged toilet on a date",
        // --- Sex & body (short) ---
        "A dick pic",
        "My penis",
        "Wrinkly balls",
        "Foreskin cheese",
        "A butt plug",
        "Wet dreams",
        "A boner",
        "A deepthroat",
        "A quickie",
        "Too much cum",
        "Erectile dysfunction",
        "A vibrator",
        "My OnlyFans",
        "A foot fetish",
        "A threesome",
        "A handjob",
        "Nudes",
        "A condom fail",
        "Razor bumps down there",
        "A french kiss",
        "My sex doll",
        "Handcuffs",
        "Vanilla sex",
        "A total dud",
        "A kink",
        "A faked moan",
        "A queef",
        "The stain",
        "An affair",
        "Masturbation",
        "A pube in the bed",
        "An ashtray kiss",
        "A hickey at 40",
        "A tongue piercing",
        "My pelvic floor",
        "A sex tape",
        "A walk of shame",
        // --- Scat / gross ---
        "Diarrhoea",
        "A fart",
        "Skid marks",
        "Constipation",
        "Haemorrhoids",
        "A wet fart",
        "No toilet paper",
        // --- Drugs & booze ---
        "Ballermann",
        "Jägermeister",
        "A blackout",
        "A little coke",
        "MDMA",
        "A joint",
        "A K-hole",
        "Cheap lager",
        "Leftover booze",
        "An 8 a.m. beer",
        "A puke bucket",
        // --- Germany (edgy) ---
        "A sovereign citizen",
        "A conspiracy nut",
        "A tinfoil hat",
        "City hall",
        "Deutsche Bahn",
        "My credit score",
        "Welfare cheques",
        "Recycling police",
        "The allotment",
        "The bank",
        "A Nazi grandpa",
        "Church tax",
        "A savings plan",
        "A speed camera",
        "A licence-fee letter",
        // --- Death & dark ---
        "Death",
        "My urn",
        "A heart attack",
        "Dying alone",
        "Organ trafficking",
        "A funeral",
        "The grim reaper",
        "An open casket",
        "A clown at the cemetery",
        // --- Absurd ---
        "A Thermomix",
        "A dolphin",
        "An IKEA shelf",
        "A pony",
        "An intern",
        "A toy car",
        "A garden gnome",
        "An alpaca",
        "A cactus",
        "A naked mole rat",
        "A bobblehead dog",
        "A talking receipt",
        // --- Psyche & mean ---
        "Your mum",
        "Dad's disappointment",
        "My daddy issues",
        "Mommy issues",
        "Self-loathing",
        "My therapy",
        "Depression",
        "A panic attack",
        "My toxic ex",
        "Your looks",
        "Fear of commitment",
        "Burnout",
        "Trauma",
        "My inner child",
        "Delusions of grandeur",
        "Second-hand cringe",
        // --- Pop & celebs ---
        "Apache 207",
        "Helene Fischer",
        "Party anthems",
        "Dieter Bohlen",
        "A cringe comedian",
        "The Bachelor",
        "A talent-show audition",
        "Auto-tuned moaning",
        // --- Sport ---
        "Khabib",
        "Conor McGregor",
        "The VAR",
        "The Sunday league",
        "An own goal",
        "A headbutt",
        // --- Food (gross) ---
        "A kebab",
        "Cold meatloaf",
        "A raw pork roll",
        "Pineapple pizza",
        "Canned ravioli",
        "Stinky cheese",
        "A beer belly",
        "Mouldy bread",
        // --- Loser life & money ---
        "The rent",
        "A deposit bottle",
        "An overdraft",
        "Hotel Mum",
        "Minimum wage",
        "The tax return",
        "A debt letter",
        "The bailiff",
        "An empty fridge",
        // --- Dating misery ---
        "A Tinder date",
        "Getting ghosted",
        "A fuckboy",
        "A sugar daddy",
        "A situationship",
        "A relapse with the ex",
        "A pregnancy scare",
        // --- Hygiene & body horror ---
        "Armpit sweat",
        "Bad breath",
        "Nose hair",
        "A pimple",
        "Athlete's foot",
        "Earwax",
        "A boil",
        "Cheesy feet",
        "A cold sore",
        // --- Religion & authority ---
        "The priest",
        "A confessional",
        "The Pope",
        "A holy-water font",
        "The naked scanner",
        "A prostate exam",
        "The public doctor",
        // --- Fetish & red light ---
        "A latex suit",
        "A whip",
        "Cuffs",
        "A brothel",
        "An escort",
        "A peeping tom",
        // --- Age & decay ---
        "A nursing home",
        "Dentures",
        "A walker",
        "Incontinence",
        "A stairlift",
        // --- Internet types ---
        "A hater",
        "A troll",
        "A stalker",
        "A simp",
        "An incel",
        "A boomer",
        "A Karen",
        "A hoarder",
        // --- Body, spontaneous ---
        "A clammy handshake",
        "A bloated belly",
        "A fit of giggles",
        "A meltdown at IKEA",
        "A sweat attack",
        "Fainting",
        "A nip slip",
      ],
    },
    es: {
      prompts: [
        // --- one blank ---
        "¿De qué nunca presumiría en una primera cita? ___",
        "___ — ese es mi rasgo tóxico.",
        "El verdadero motivo de mi última ruptura: ___.",
        "En urgencias una vez tuve que explicar ___.",
        "Mi psicólogo lo dejó porque no paraba de hablar de ___.",
        "¿Qué hay de verdad en mi historial de búsqueda? ___.",
        "Durante el sexo pienso en secreto en ___.",
        "Mi bio de la app de citas debería decir solo: ___.",
        "El sustituto de mi ex: ___.",
        "Lo que más grima me da: ___.",
        "Lo primero que hago cada mañana: ___.",
        "En vez de ir a terapia, me doy un capricho: ___.",
        "El motivo por el que ya no me invitan: ___.",
        "Mi vida amorosa ahora consiste únicamente en ___.",
        "Lo que necesito para sobrevivir al lunes: ___.",
        "En mi testamento dejo sobre todo ___.",
        "Mi mayor bandera roja cuando nos conocemos: ___.",
        "Lo que más me gusta a las 4 de la mañana: ___.",
        "Lo más romántico que he dicho nunca: ___.",
        "Ahora mismo mi cuerpo funciona al 90 % con ___.",
        "El secreto más oscuro de mi relación es ___.",
        "Mi dios es ___.",
        "El motivo por el que mi madre me mira decepcionada: ___.",
        "A cada barbacoa siempre llevo ___.",
        "Mi superpoder en la cama es ___.",
        "El verdadero motivo por el que sigo viviendo en casa de mis padres: ___.",
        "En mi lápida debería poner: ___.",
        "Lo que me pone al instante: ___.",
        "Toda mi autoestima se basa en ___.",
        "Lo más vergonzoso que he buscado en Google: ___.",
        "En vez de hacer deporte, prefiero practicar ___.",
        "Por esto vendería mi cuerpo: ___.",
        "A cambio, mi sugar daddy espera ___.",
        "En todas las fiestas soy el de ___.",
        "Lo que le oculto a mi cita hasta después del sexo: ___.",
        "Mi nicho en OnlyFans sería ___.",
        "Mi despertar espiritual llegó gracias a ___.",
        "Lo último en lo que pienso antes de dormirme: ___.",
        "El verdadero motivo por el que siempre llego tarde: ___.",
        "Toda mi infancia se explica en una palabra: ___.",
        "Lo que no quiero oír bajo ningún concepto durante el sexo: ___.",
        "Mi situación sentimental es complicada por culpa de ___.",
        "Lo mejor de cada cena familiar: ___.",
        "En mi solicitud de empleo mentí descaradamente sobre ___.",
        "Mi adicción más secreta es ___.",
        "Lo que más echa de menos mi ex de mí: ___.",
        "El motivo por el que me han bloqueado en todas partes: ___.",
        "Mi idea de un detalle de amor es esta: ___.",
        "Lo que nunca les enseñaría a mis padres: ___.",
        "Mi vida sería mejor sin ___.",
        "El piropo más guarro que me han dicho: ___.",
        "Mi alter ego borracho: ___.",
        "Mi entrenador personal tiró la toalla por culpa de ___.",
        "Lo que confesé en mi última charla de pareja: ___.",
        "Mi día a día es un 80 % ___.",
        "El verdadero motivo por el que estoy soltero: ___.",
        "En una primera cita siempre huelo a ___.",
        "Mi mayor talento que no sale en ningún currículum: ___.",
        "Lo que no me deja dormir por la noche: ___.",
        "Mi último pensamiento antes de morir será: ___.",
        // --- two blanks (Pick 2) ---
        "Mi noche perfecta: ___ y ___.",
        "En el infierno solo hay ___ y ___.",
        "La receta del desastre: ___ más ___.",
        "Primero ___, luego ___ — la historia de mi vida.",
        "Durante el sexo me encanta combinar ___ con ___.",
        "Mi match de Tinder prometía ___, y trajo ___.",
        "Navidad en familia: ___ peleándose con ___.",
        "Mi terapia gira en torno a ___ y ___.",
        "El verdadero motivo del apocalipsis: ___ y ___.",
        "Mi anuncio por palabras — ofrezco: ___, busco: ___.",
        "Mi cuerpo: arriba ___, abajo ___.",
        "Dos cosas que nadie debería combinar nunca: ___ y ___.",
        "Mi bio de citas: ___, pero en la cama ___.",
        "De desayuno hubo ___, de postre ___.",
      ],
      answers: [
        // signature long ones (kept rare on purpose)
        "Un pene normalito",
        "Tres cervezas y malas decisiones",
        "Lo último que me quedaba de dignidad",
        "Dos mapaches en una gabardina",
        "Un pene que tira a la izquierda",
        "Dos dedos y mucho optimismo",
        "Un footjob por debajo de la mesa",
        "Un tío facha en Nochebuena",
        "Un kebab a las 4 de la mañana",
        "Un váter atascado en una cita",
        // --- Sex & body (short) ---
        "Una foto de la polla",
        "Mi pene",
        "Huevos arrugados",
        "Requesón de prepucio",
        "Un plug anal",
        "Sueños húmedos",
        "Una erección",
        "Una garganta profunda",
        "Un rapidito",
        "Demasiado semen",
        "Disfunción eréctil",
        "Un vibrador",
        "Mi OnlyFans",
        "Un fetiche de pies",
        "Un trío",
        "Una paja",
        "Nudes",
        "Un condón roto",
        "Granitos de depilación ahí abajo",
        "Un morreo",
        "Mi muñeca hinchable",
        "Esposas",
        "Sexo vainilla",
        "Un gatillazo",
        "Un fetiche",
        "Un gemido fingido",
        "Un pedo vaginal",
        "La mancha",
        "Una aventura",
        "La masturbación",
        "Un pelo púbico en la cama",
        "Un beso de cenicero",
        "Un chupetón a los 40",
        "Un piercing en la lengua",
        "Mi suelo pélvico",
        "Un vídeo porno casero",
        "El paseo de la vergüenza",
        // --- Scat / gross ---
        "Diarrea",
        "Un pedo",
        "Palominos en los calzoncillos",
        "Estreñimiento",
        "Almorranas",
        "Un pedo húmedo",
        "Sin papel higiénico",
        // --- Drugs & booze ---
        "Magaluf",
        "Jägermeister",
        "Una laguna mental",
        "Un poco de coca",
        "MDMA",
        "Un porro",
        "Un viaje de ketamina",
        "Cerveza barata",
        "Las sobras del botellón",
        "Una caña a las 8 de la mañana",
        "Un cubo para vomitar",
        // --- Spain (edgy) ---
        "Un okupa",
        "Un conspiranoico",
        "Un gorro de papel de aluminio",
        "El ayuntamiento",
        "Renfe",
        "Mi historial en el ASNEF",
        "El paro",
        "La policía del reciclaje",
        "El huerto urbano",
        "El banco",
        "Un abuelo franquista",
        "Hacienda",
        "Un plan de pensiones",
        "Un radar de tráfico",
        "Una multa de la DGT",
        // --- Death & dark ---
        "La muerte",
        "Mi urna",
        "Un infarto",
        "Morir solo",
        "Tráfico de órganos",
        "Un funeral",
        "La parca",
        "Un ataúd abierto",
        "Un payaso en el cementerio",
        // --- Absurd ---
        "Una Thermomix",
        "Un delfín",
        "Una estantería de IKEA",
        "Un poni",
        "Un becario",
        "Un coche de juguete",
        "Un gnomo de jardín",
        "Una alpaca",
        "Un cactus",
        "Una rata topo desnuda",
        "Un perrito que mueve la cabeza",
        "Un tique que habla",
        // --- Psyche & mean ---
        "Tu madre",
        "La decepción de papá",
        "Mis traumas con papá",
        "Mis traumas con mamá",
        "El autodesprecio",
        "Mi terapia",
        "La depresión",
        "Un ataque de pánico",
        "Mi ex tóxico",
        "Tu cara",
        "El miedo al compromiso",
        "El burnout",
        "Un trauma",
        "Mi niño interior",
        "Delirios de grandeza",
        "Vergüenza ajena",
        // --- Pop & celebs ---
        "Bad Bunny",
        "Isabel Pantoja",
        "Canciones de verbena",
        "Risto Mejide",
        "Un humorista cutre",
        "La isla de las tentaciones",
        "Un casting de talent show",
        "Gemidos con autotune",
        // --- Sport ---
        "Khabib",
        "Conor McGregor",
        "El VAR",
        "La liga de veteranos",
        "Un gol en propia puerta",
        "Un cabezazo",
        // --- Food (gross) ---
        "Un kebab",
        "Albóndigas frías",
        "Un bocadillo de carne cruda",
        "Pizza con piña",
        "Raviolis de lata",
        "Queso apestoso",
        "Una barriga cervecera",
        "Pan mohoso",
        // --- Loser life & money ---
        "El alquiler",
        "Un casco de botella",
        "Un descubierto en la cuenta",
        "La casa de mis padres",
        "El salario mínimo",
        "La declaración de la renta",
        "Una carta de deudas",
        "El cobrador del frac",
        "Una nevera vacía",
        // --- Dating misery ---
        "Una cita de Tinder",
        "Que te hagan ghosting",
        "Un fuckboy",
        "Un sugar daddy",
        "Una situationship",
        "Una recaída con el ex",
        "Un susto de embarazo",
        // --- Hygiene & body horror ---
        "Sudor de axila",
        "Mal aliento",
        "Pelos de la nariz",
        "Un grano",
        "Pie de atleta",
        "Cerumen",
        "Un forúnculo",
        "Pies que huelen a queso",
        "Un herpes labial",
        // --- Religion & authority ---
        "El cura",
        "Un confesionario",
        "El Papa",
        "Una pila de agua bendita",
        "El escáner corporal del aeropuerto",
        "Un tacto rectal",
        "El médico de cabecera",
        // --- Fetish & red light ---
        "Un traje de látex",
        "Un látigo",
        "Unas esposas",
        "Un puticlub",
        "Un acompañante de lujo",
        "Un mirón",
        // --- Age & decay ---
        "Una residencia de ancianos",
        "Una dentadura postiza",
        "Un andador",
        "La incontinencia",
        "Un salvaescaleras",
        // --- Internet types ---
        "Un hater",
        "Un troll",
        "Un acosador",
        "Un simp",
        "Un incel",
        "Un boomer",
        "Una Karen",
        "Un acumulador compulsivo",
        // --- Body, spontaneous ---
        "Un apretón de manos sudado",
        "Una barriga hinchada",
        "Un ataque de risa",
        "Una crisis nerviosa en IKEA",
        "Un ataque de sudor",
        "Un desmayo",
        "Que se te salga un pezón",
      ],
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.Geschmacklos = GESCHMACKLOS;
})(window);
