// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/mindmeld.js — content for Mind Meld (convergence team game)
 *
 * EDIT ME. Pure content, no game logic. Each team is handed 2–3 distinct SEED
 * WORDS drawn from a pool. Every round all members simultaneously blurt a new
 * word, trying to converge on the SAME word. These are the starting seeds — so
 * they should be single, concrete-ish, evocative words that give a team
 * somewhere to converge FROM. (Different shape from the shared term database, so
 * they live here.)
 *
 * `words` is a flat list; the game draws 2–3 distinct entries per team. Pools
 * become selectable chips and are language-switchable. `label` is what players
 * see; the key is the internal id.
 */
(function (global) {
  "use strict";

  var MINDMELD = {
    de: {
      allgemein: {
        label: "🎲 Allgemein",
        words: [
          "Feuer",
          "Ozean",
          "Mond",
          "Gewitter",
          "Vulkan",
          "Wüste",
          "Regenbogen",
          "Dschungel",
          "Schokolade",
          "Pizza",
          "Kaffee",
          "Honig",
          "Zitrone",
          "Sushi",
          "Berlin",
          "Paris",
          "Sauna",
          "Friedhof",
          "Flughafen",
          "Insel",
          "Chaos",
          "Heimweh",
          "Freiheit",
          "Nostalgie",
          "Panik",
          "Glück",
          "Vampir",
          "Zombie",
          "Superheld",
          "Roboter",
          "Einhorn",
          "Ninja",
          "Geist",
          "Montag",
          "Mitternacht",
          "Karneval",
          "Achterbahn",
          "Labyrinth",
          "Zirkus",
          "Anker",
          "Spiegel",
          "Schlüssel",
          "Regenschirm",
          "Kompass",
          "Kerze",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        words: [
          "Handschellen",
          "Beichte",
          "One-Night-Stand",
          "Verlangen",
          "Tinder",
          "Kuss",
          "Verführung",
          "Dessous",
          "Massage",
          "Fantasie",
          "Flirt",
          "Leidenschaft",
          "Geheimnis",
          "Nacktheit",
          "Peitsche",
          "Augenbinde",
          "Verboten",
          "Ex",
          "Affäre",
          "Rendezvous",
          "Champagner",
          "Bett",
          "Stöhnen",
          "Sünde",
          "Kerzenlicht",
          "Hotelzimmer",
          "Techtelmechtel",
          "Striptease",
          "Rotwein",
          "Versuchung",
          "Seidenlaken",
          "Knutschfleck",
          "Lippenstift",
          "Rollenspiel",
          "Whirlpool",
          "Kondom",
          "Poolboy",
          "Aktfoto",
          "Erregung",
          "Sinnlichkeit",
          "Liebesbrief",
          "Höschen",
          "Rücksitz",
          "Schmetterlinge",
          "Vorspiel",
        ],
      },
    },
    en: {
      allgemein: {
        label: "🎲 General",
        words: [
          "Fire",
          "Ocean",
          "Moon",
          "Thunderstorm",
          "Volcano",
          "Desert",
          "Rainbow",
          "Jungle",
          "Chocolate",
          "Pizza",
          "Coffee",
          "Honey",
          "Lemon",
          "Sushi",
          "Berlin",
          "Paris",
          "Sauna",
          "Graveyard",
          "Airport",
          "Island",
          "Chaos",
          "Homesickness",
          "Freedom",
          "Nostalgia",
          "Panic",
          "Luck",
          "Vampire",
          "Zombie",
          "Superhero",
          "Robot",
          "Unicorn",
          "Ninja",
          "Ghost",
          "Monday",
          "Midnight",
          "Carnival",
          "Rollercoaster",
          "Labyrinth",
          "Circus",
          "Anchor",
          "Mirror",
          "Key",
          "Umbrella",
          "Compass",
          "Candle",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        words: [
          "Handcuffs",
          "Confession",
          "One-night stand",
          "Desire",
          "Tinder",
          "Kiss",
          "Seduction",
          "Lingerie",
          "Massage",
          "Fantasy",
          "Flirt",
          "Passion",
          "Secret",
          "Nudity",
          "Whip",
          "Blindfold",
          "Forbidden",
          "Ex",
          "Affair",
          "Rendezvous",
          "Champagne",
          "Bed",
          "Moaning",
          "Sin",
          "Candlelight",
          "Hotel room",
          "Fling",
          "Striptease",
          "Red wine",
          "Temptation",
          "Silk sheets",
          "Hickey",
          "Lipstick",
          "Roleplay",
          "Hot tub",
          "Condom",
          "Pool boy",
          "Nude photo",
          "Arousal",
          "Sensuality",
          "Love letter",
          "Panties",
          "Back seat",
          "Butterflies",
          "Foreplay",
        ],
      },
    },
    es: {
      allgemein: {
        label: "🎲 General",
        words: [
          "Fuego",
          "Océano",
          "Luna",
          "Tormenta",
          "Volcán",
          "Desierto",
          "Arcoíris",
          "Selva",
          "Chocolate",
          "Pizza",
          "Café",
          "Miel",
          "Limón",
          "Sushi",
          "Berlín",
          "París",
          "Sauna",
          "Cementerio",
          "Aeropuerto",
          "Isla",
          "Caos",
          "Morriña",
          "Libertad",
          "Nostalgia",
          "Pánico",
          "Suerte",
          "Vampiro",
          "Zombi",
          "Superhéroe",
          "Robot",
          "Unicornio",
          "Ninja",
          "Fantasma",
          "Lunes",
          "Medianoche",
          "Carnaval",
          "Montaña rusa",
          "Laberinto",
          "Circo",
          "Ancla",
          "Espejo",
          "Llave",
          "Paraguas",
          "Brújula",
          "Vela",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        words: [
          "Esposas",
          "Confesión",
          "Rollo de una noche",
          "Deseo",
          "Tinder",
          "Beso",
          "Seducción",
          "Lencería",
          "Masaje",
          "Fantasía",
          "Ligoteo",
          "Pasión",
          "Secreto",
          "Desnudez",
          "Látigo",
          "Venda en los ojos",
          "Prohibido",
          "Ex",
          "Aventura",
          "Cita secreta",
          "Champán",
          "Cama",
          "Gemidos",
          "Pecado",
          "Luz de velas",
          "Habitación de hotel",
          "Lío",
          "Striptease",
          "Vino tinto",
          "Tentación",
          "Sábanas de seda",
          "Chupetón",
          "Pintalabios",
          "Juego de rol",
          "Jacuzzi",
          "Condón",
          "Socorrista de piscina",
          "Foto desnudo",
          "Excitación",
          "Sensualidad",
          "Carta de amor",
          "Bragas",
          "Asiento de atrás",
          "Mariposas en el estómago",
          "Preliminares",
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.MindMeldWords = MINDMELD;
})(window);
