/*
 * content/most-likely.js — content for Most Likely To (NSFW, adults only)
 *
 * EDIT ME. Pure content. Each entry completes "Most likely to ___" — write just
 * the predicate, the game adds the prefix. Aim them at the group.
 *
 * Bilingual: global.Spielecke.MostLikely = { de:{...}, en:{...} }.
 * German predicates read after "Am wahrscheinlichsten…"; English after
 * "Most likely to". Same structure/keys in both languages.
 */
(function (global) {
  "use strict";

  var MOST_LIKELY = {
    de: {
      general: {
        label: "🎲 Allgemein",
        prompts: [
          "wird berühmt",
          "wird wegen etwas Dummem verhaftet",
          "heult bei einer Hochzeitsrede",
          "kommt zu spät zur eigenen Party",
          "gewinnt im Lotto und verzockt alles",
          "fängt grundlos einen Streit an",
          "wird mit 30 Millionär und postet ständig darüber",
          "geht mit einem peinlichen Video viral",
          "heiratet als Erstes aus der Gruppe",
          "ghostet alle und taucht zwei Jahre später wieder auf",
          "gründet ein Start-up, das niemand braucht",
          "landet in einer Reality-Show",
          "fällt auf jede Krypto-Masche rein",
          "wird Influencer für ein extrem nischiges Thema",
          "weint bei einer Versicherungswerbung",
          "verkauft am Ende doch einen Online-Kurs",
          "swipt sich durch die ganze Stadt",
          "wird Profisportler oder behauptet es zumindest",
          "gründet aus Versehen eine Sekte",
          "wird auf LinkedIn zum Motivations-Guru",
          "kennt den heißesten Promi-Klatsch zuerst",
        ],
      },
      party: {
        label: "🎉 Party",
        prompts: [
          "wird aus dem Club geworfen",
          "kotzt heute Abend als Erstes",
          "steht um 6 Uhr morgens noch",
          "verliert heute Abend das Handy",
          "fängt eine Tanz-Battle an",
          "schreibt heute Abend dem Ex",
          "macht als Erstes einen Filmriss",
          "freundet sich mit der gesamten Schlange an der Bar an",
          "übernimmt das Mikro und lässt es nicht mehr los",
          "gibt eine Runde Shots aus, die niemand bestellt hat",
          "verliert einen Schuh und merkt es erst morgen",
          "macht im Taxi schon die Augen zu",
          "stellt jeden seinem neuen besten Freund vor",
          "diskutiert um 4 Uhr mit dem Türsteher",
          "bestellt um 3 Uhr morgens das größte Döner-Menü",
          "startet das Afterparty-Gruppenchat-Chaos",
          "tanzt auf der Bar, obwohl niemand mehr tanzt",
          "verschüttet ein Getränk über ein fremdes Outfit",
          "schwört, dass das das letzte Bier war",
          "fängt an, Fremden den Sinn des Lebens zu erklären",
          "wettet betrunken um Geld und verliert",
        ],
      },
      leisure: {
        label: "🏖️ Freizeit & Urlaub",
        prompts: [
          "verpasst den Flug, weil noch ein Selfie sein musste",
          "verläuft sich in jeder fremden Stadt",
          "bucht den Urlaub eine Stunde vor Abflug",
          "packt für ein Wochenende wie für drei Wochen",
          "verbringt den ganzen Urlaub am Pool",
          "will jede Sehenswürdigkeit an einem Tag abklappern",
          "bekommt am ersten Tag den schlimmsten Sonnenbrand",
          "redet die ganze Busfahrt mit Fremden",
        ],
      },
      history: {
        label: "🏛️ Politik & Geschichte",
        prompts: [
          "führt aus Versehen eine kleine Revolution an",
          "gewinnt jedes Geschichtsquiz",
          "diskutiert auf jeder Feier über Politik",
          "würde sich am liebsten zum König krönen lassen",
          "kennt jede Jahreszahl auswendig",
          "geht später in die Politik",
          "hält eine Rede, die keiner hören will",
          "würde eine Zeitmaschine sofort missbrauchen",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "reißt heute Abend einen Fremden auf",
          "hat den wildesten Suchverlauf",
          "verschickt gerade jetzt eine heiße Nachricht",
          "hat heimlich ein OnlyFans",
          "küsst jemanden in diesem Raum",
          "hat einen geheimen Kink",
          "schläft im Urlaub mit jemandem",
          "wird beim Sex in der Öffentlichkeit erwischt",
          "hat irgendwo ein Sextape",
          "datet zwei Leute gleichzeitig",
          "schickt aus Versehen Nudes in den Gruppenchat",
          "täuscht es vor, um es hinter sich zu bringen",
          "hat hier die höchste Bodycount",
          "geht heute Abend mit jemandem nach Hause",
          "hat einen One-Night-Stand und fängt Gefühle",
        ],
      },
    },
    en: {
      general: {
        label: "🎲 General",
        prompts: [
          "become famous",
          "get arrested for something stupid",
          "cry during a wedding speech",
          "show up late to their own party",
          "win the lottery and lose it all",
          "start an argument over nothing",
          "be a millionaire by 30 and never shut up about it",
          "go viral for an embarrassing video",
          "be the first to get married",
          "ghost everyone and resurface two years later",
          "start a startup nobody needs",
          "end up on a reality TV show",
          "fall for every crypto scam going",
          "become an influencer for an oddly specific niche",
          "cry at an insurance advert",
          "end up selling an online course",
          "swipe their way through the whole city",
          "go pro in a sport, or at least claim to",
          "accidentally start a cult",
          "become a motivational guru on LinkedIn",
          "always hear the juiciest celebrity gossip first",
        ],
      },
      party: {
        label: "🎉 Party",
        prompts: [
          "get kicked out of the club",
          "throw up first tonight",
          "still be standing at 6am",
          "lose their phone tonight",
          "start a dance-off",
          "text their ex tonight",
          "black out first tonight",
          "befriend the entire queue at the bar",
          "grab the mic and never give it back",
          "buy a round of shots nobody asked for",
          "lose a shoe and not notice till morning",
          "fall asleep in the taxi home",
          "introduce everyone to their new best friend",
          "argue with the bouncer at 4am",
          "order the biggest kebab at 3am",
          "kick off the afterparty group-chat chaos",
          "dance on the bar when nobody else is dancing",
          "spill a drink down a stranger's outfit",
          "swear that was the last beer",
          "start explaining the meaning of life to strangers",
          "make a drunk bet for money and lose",
        ],
      },
      leisure: {
        label: "🏖️ Leisure & Travel",
        prompts: [
          "miss the flight for one more selfie",
          "get lost in every new city",
          "book the holiday an hour before takeoff",
          "pack for three weeks for a weekend trip",
          "spend the whole holiday by the pool",
          "try to see every sight in one day",
          "get the worst sunburn on day one",
          "talk to strangers the whole bus ride",
        ],
      },
      history: {
        label: "🏛️ Politics & History",
        prompts: [
          "accidentally start a small revolution",
          "win every history quiz",
          "argue about politics at every party",
          "have themselves crowned king",
          "know every date by heart",
          "go into politics one day",
          "give a speech nobody asked for",
          "instantly misuse a time machine",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "hook up with a stranger tonight",
          "have the wildest search history",
          "send a risky text right now",
          "have a secret OnlyFans",
          "kiss someone in this room",
          "have a secret kink",
          "sleep with someone on holiday",
          "get caught having sex in public",
          "have a sex tape out there",
          "date two people at once",
          "send nudes to the group chat by accident",
          "fake it to get it over with",
          "have the highest body count here",
          "go home with someone tonight",
          "have a one-night stand and catch feelings",
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.MostLikely = MOST_LIKELY;
})(window);
