// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/most-likely.js — content for Most Likely To (NSFW, adults only)
 *
 * EDIT ME. Pure content. Each entry completes "Most likely to ___" — write just
 * the predicate, the game adds the prefix. Aim them at the group.
 *
 * Bilingual: global.Spielecke.MostLikely = { de:{...}, en:{...} }.
 * German predicates read after "Am wahrscheinlichsten…"; English after
 * "Most likely to". Same structure/keys in both languages.
 */
(function (global) {
  "use strict";

  var MOST_LIKELY = {
    de: {
      general: {
        label: "🎲 Allgemein",
        prompts: [
          "wird berühmt",
          "wird wegen etwas Dummem verhaftet",
          "heult bei einer Hochzeitsrede",
          "kommt zu spät zur eigenen Party",
          "gewinnt im Lotto und verzockt alles",
          "fängt grundlos einen Streit an",
          "wird mit 30 Millionär und postet ständig darüber",
          "geht mit einem peinlichen Video viral",
          "heiratet als Erstes aus der Gruppe",
          "ghostet alle und taucht zwei Jahre später wieder auf",
          "gründet ein Start-up, das niemand braucht",
          "landet in einer Reality-Show",
          "fällt auf jede Krypto-Masche rein",
          "wird Influencer für ein extrem nischiges Thema",
          "weint bei einer Versicherungswerbung",
          "verkauft am Ende doch einen Online-Kurs",
          "swipt sich durch die ganze Stadt",
          "wird Profisportler oder behauptet es zumindest",
          "gründet aus Versehen eine Sekte",
          "wird auf LinkedIn zum Motivations-Guru",
          "kennt den heißesten Promi-Klatsch zuerst",
        ],
      },
      party: {
        label: "🎉 Party",
        prompts: [
          "wird aus dem Club geworfen",
          "kotzt heute Abend als Erstes",
          "steht um 6 Uhr morgens noch",
          "verliert heute Abend das Handy",
          "fängt eine Tanz-Battle an",
          "schreibt heute Abend dem Ex",
          "macht als Erstes einen Filmriss",
          "freundet sich mit der gesamten Schlange an der Bar an",
          "übernimmt das Mikro und lässt es nicht mehr los",
          "gibt eine Runde Shots aus, die niemand bestellt hat",
          "verliert einen Schuh und merkt es erst morgen",
          "macht im Taxi schon die Augen zu",
          "stellt jeden seinem neuen besten Freund vor",
          "diskutiert um 4 Uhr mit dem Türsteher",
          "bestellt um 3 Uhr morgens das größte Döner-Menü",
          "startet das Afterparty-Gruppenchat-Chaos",
          "tanzt auf der Bar, obwohl niemand mehr tanzt",
          "verschüttet ein Getränk über ein fremdes Outfit",
          "schwört, dass das das letzte Bier war",
          "fängt an, Fremden den Sinn des Lebens zu erklären",
          "wettet betrunken um Geld und verliert",
          "verschwindet heimlich um 23 Uhr, ohne Tschüss zu sagen",
          "räumt auf der Hausparty heimlich schon mal auf",
        ],
      },
      leisure: {
        label: "🏖️ Freizeit & Urlaub",
        prompts: [
          "verpasst den Flug, weil noch ein Selfie sein musste",
          "verläuft sich in jeder fremden Stadt",
          "bucht den Urlaub eine Stunde vor Abflug",
          "packt für ein Wochenende wie für drei Wochen",
          "verbringt den ganzen Urlaub am Pool",
          "will jede Sehenswürdigkeit an einem Tag abklappern",
          "bekommt am ersten Tag den schlimmsten Sonnenbrand",
          "redet die ganze Busfahrt mit Fremden",
          "hat die Reiseapotheke für die ganze Gruppe dabei",
          "plant den Trip mit Excel-Tabelle und Plan B",
        ],
      },
      history: {
        label: "🏛️ Politik & Geschichte",
        prompts: [
          "führt aus Versehen eine kleine Revolution an",
          "gewinnt jedes Geschichtsquiz",
          "diskutiert auf jeder Feier über Politik",
          "würde sich am liebsten zum König krönen lassen",
          "kennt jede Jahreszahl auswendig",
          "geht später in die Politik",
          "hält eine Rede, die keiner hören will",
          "würde eine Zeitmaschine sofort missbrauchen",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "reißt heute Abend einen Fremden auf",
          "hat den wildesten Suchverlauf",
          "verschickt gerade jetzt eine heiße Nachricht",
          "hat heimlich ein OnlyFans",
          "küsst jemanden in diesem Raum",
          "hat einen geheimen Kink",
          "schläft im Urlaub mit jemandem",
          "wird beim Sex in der Öffentlichkeit erwischt",
          "hat irgendwo ein Sextape",
          "datet zwei Leute gleichzeitig",
          "schickt aus Versehen Nudes in den Gruppenchat",
          "täuscht es vor, um es hinter sich zu bringen",
          "hat hier die höchste Bodycount",
          "geht heute Abend mit jemandem nach Hause",
          "hat einen One-Night-Stand und fängt Gefühle",
          "hatte schon ein Date, von dem hier niemand je erfahren hat",
          "würde bei einem Lapdance knallrot werden",
          "flirtet sich in einen Rabatt rein",
          "hat sich schon mal in den DMs an jemanden rangeschmissen",
          "würde bei Wahrheit oder Pflicht am ehesten schummeln",
          "hat schon mal mit dem Ex/der Ex von jemandem hier rumgemacht",
          "verschickt in einer neuen Beziehung als Erstes ein Nacktfoto",
          "hat beim Sex schon mal den falschen Namen gerufen",
          "würde für einen One-Night-Stand quer durch die Stadt fahren",
          "hat ein geheimes Zweitprofil auf einer Dating-App",
          "bereut den One-Night-Stand von letztem Wochenende am meisten",
          "hat schon mal jemanden geghostet, direkt nachdem es intim wurde",
        ],
      },
      date: {
        label: "🌹 Date",
        prompts: [
          "steht heimlich drauf, beim Sex gewürgt zu werden",
          "übernimmt im Bett gern die Kontrolle",
          "gibt im Bett lieber die Kontrolle ab",
          "macht heute Abend den ersten Schritt",
          "denkt gerade an einen Kuss",
          "wird im Bett am lautesten",
          "fängt nach gutem Sex schneller Gefühle",
          "hat gerade den versauteren Gedanken im Kopf",
          "zieht den anderen zuerst zu sich ran",
          "hat einen Kink, mit dem keiner rechnet",
          "küsst zuerst, ohne zu fragen",
          "lässt sich am längsten hinhalten",
          "schreibt nach dem ersten Date als Erstes",
          "macht aus einem Blick sofort mehr",
          "hält beim Blickkontakt am längsten durch",
          "redet im Bett am meisten",
          "wird rot, wenn's konkret wird",
          "verliebt sich nach einer einzigen Nacht",
          "sagt nie, was er oder sie eigentlich will",
          "flirtet, ohne es selbst zu merken",
          "landet am Ende des Abends zuerst bei jemandem zuhause",
          "lässt sich am leichtesten verführen",
          "nimmt sich im Bett am meisten Zeit",
          "stellt die direktesten Fragen",
          "hat am meisten Erfahrung, gibt's aber nicht zu",
          "macht beim Abschied den letzten Schritt",
        ],
      },
    },
    en: {
      general: {
        label: "🎲 General",
        prompts: [
          "become famous",
          "get arrested for something stupid",
          "cry during a wedding speech",
          "show up late to their own party",
          "win the lottery and lose it all",
          "start an argument over nothing",
          "be a millionaire by 30 and never shut up about it",
          "go viral for an embarrassing video",
          "be the first to get married",
          "ghost everyone and resurface two years later",
          "start a startup nobody needs",
          "end up on a reality TV show",
          "fall for every crypto scam going",
          "become an influencer for an oddly specific niche",
          "cry at an insurance advert",
          "end up selling an online course",
          "swipe their way through the whole city",
          "go pro in a sport, or at least claim to",
          "accidentally start a cult",
          "become a motivational guru on LinkedIn",
          "always hear the juiciest celebrity gossip first",
        ],
      },
      party: {
        label: "🎉 Party",
        prompts: [
          "get kicked out of the club",
          "throw up first tonight",
          "still be standing at 6am",
          "lose their phone tonight",
          "start a dance-off",
          "text their ex tonight",
          "black out first tonight",
          "befriend the entire queue at the bar",
          "grab the mic and never give it back",
          "buy a round of shots nobody asked for",
          "lose a shoe and not notice till morning",
          "fall asleep in the taxi home",
          "introduce everyone to their new best friend",
          "argue with the bouncer at 4am",
          "order the biggest kebab at 3am",
          "kick off the afterparty group-chat chaos",
          "dance on the bar when nobody else is dancing",
          "spill a drink down a stranger's outfit",
          "swear that was the last beer",
          "start explaining the meaning of life to strangers",
          "make a drunk bet for money and lose",
          "sneak out at 11pm without saying goodbye",
          "quietly start cleaning up mid-house-party",
        ],
      },
      leisure: {
        label: "🏖️ Leisure & Travel",
        prompts: [
          "miss the flight for one more selfie",
          "get lost in every new city",
          "book the holiday an hour before takeoff",
          "pack for three weeks for a weekend trip",
          "spend the whole holiday by the pool",
          "try to see every sight in one day",
          "get the worst sunburn on day one",
          "talk to strangers the whole bus ride",
          "carry the first-aid kit for the whole group",
          "plan the trip with a spreadsheet and a plan B",
        ],
      },
      history: {
        label: "🏛️ Politics & History",
        prompts: [
          "accidentally start a small revolution",
          "win every history quiz",
          "argue about politics at every party",
          "have themselves crowned king",
          "know every date by heart",
          "go into politics one day",
          "give a speech nobody asked for",
          "instantly misuse a time machine",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "hook up with a stranger tonight",
          "have the wildest search history",
          "send a risky text right now",
          "have a secret OnlyFans",
          "kiss someone in this room",
          "have a secret kink",
          "sleep with someone on holiday",
          "get caught having sex in public",
          "have a sex tape out there",
          "date two people at once",
          "send nudes to the group chat by accident",
          "fake it to get it over with",
          "have the highest body count here",
          "go home with someone tonight",
          "have a one-night stand and catch feelings",
          "have been on a date nobody here ever found out about",
          "blush bright red during a lap dance",
          "flirt their way into a discount",
          "have slid into someone's DMs and never told anyone",
          "cheat first at Truth or Dare",
          "have hooked up with someone's ex in this room",
          "send the first nude in a new relationship",
          "have called out the wrong name in bed",
          "would drive across town for a one-night stand",
          "have a secret second profile on a dating app",
          "regret last weekend's hookup the most",
          "have ghosted someone right after things got intimate",
        ],
      },
      date: {
        label: "🌹 Date",
        prompts: [
          "secretly be into being choked in bed",
          "love taking control in bed",
          "rather give up control in bed",
          "make the first move tonight",
          "be thinking about a kiss right now",
          "be the loudest in bed",
          "catch feelings faster after good sex",
          "have the filthier thought right now",
          "pull the other one in first",
          "have a kink nobody would guess",
          "kiss first without asking",
          "get strung along the longest",
          "text first after a first date",
          "turn one look into something more",
          "hold eye contact the longest",
          "talk the most in bed",
          "go red when it gets specific",
          "fall in love after a single night",
          "never say what they actually want",
          "flirt without realising they're doing it",
          "end up at someone's place first at the end of the night",
          "be the easiest to seduce",
          "take the most time in bed",
          "ask the most direct questions",
          "have the most experience but never admit it",
          "make the last move when saying goodbye",
        ],
      },
    },
    es: {
      general: {
        label: "🎲 General",
        prompts: [
          "se haga famoso",
          "acabe detenido por una tontería",
          "llore durante un discurso de boda",
          "llegue tarde a su propia fiesta",
          "gane la lotería y lo pierda todo",
          "monte una discusión por nada",
          "sea millonario a los 30 y no pare de hablar de ello",
          "se haga viral con un vídeo vergonzoso",
          "sea el primero en casarse",
          "desaparezca para todos y reaparezca dos años después",
          "monte una startup que nadie necesita",
          "acabe en un reality",
          "caiga en todas las estafas cripto",
          "se haga influencer de un nicho rarísimo",
          "llore con un anuncio de seguros",
          "acabe vendiendo un curso online",
          "haga swipe por toda la ciudad",
          "se haga profesional de un deporte, o al menos lo diga",
          "funde una secta sin querer",
          "se convierta en gurú motivacional de LinkedIn",
          "se entere siempre el primero del cotilleo más jugoso de famosos",
        ],
      },
      party: {
        label: "🎉 Fiesta",
        prompts: [
          "acabe expulsado de la discoteca",
          "vomite el primero esta noche",
          "siga en pie a las 6 de la mañana",
          "pierda el móvil esta noche",
          "empiece un duelo de baile",
          "le escriba a su ex esta noche",
          "pierda el conocimiento el primero esta noche",
          "se haga amigo de toda la cola de la barra",
          "coja el micro y no lo suelte nunca",
          "pida una ronda de chupitos que nadie ha pedido",
          "pierda un zapato y no se dé cuenta hasta la mañana",
          "se duerma en el taxi de vuelta",
          "presente a todos a su nuevo mejor amigo",
          "discuta con el portero a las 4 de la mañana",
          "pida el kebab más grande a las 3 de la mañana",
          "desate el caos en el grupo del after",
          "baile en la barra cuando nadie más baila",
          "le tire una copa encima a un desconocido",
          "jure que esa era la última cerveza",
          "se ponga a explicar el sentido de la vida a desconocidos",
          "haga una apuesta borracho por dinero y la pierda",
          "se escape a las 11 sin despedirse",
          "se ponga a recoger en mitad de una fiesta en casa",
        ],
      },
      leisure: {
        label: "🏖️ Ocio y viajes",
        prompts: [
          "pierda el vuelo por un selfie más",
          "se pierda en cada ciudad nueva",
          "reserve las vacaciones una hora antes del despegue",
          "haga la maleta para tres semanas para un fin de semana",
          "se pase todas las vacaciones en la piscina",
          "intente ver todos los monumentos en un día",
          "se queme con el sol el primer día",
          "hable con desconocidos todo el viaje en bus",
          "lleve el botiquín de todo el grupo",
          "planifique el viaje con un Excel y un plan B",
        ],
      },
      history: {
        label: "🏛️ Política e historia",
        prompts: [
          "empiece una pequeña revolución sin querer",
          "gane todos los quizzes de historia",
          "discuta de política en todas las fiestas",
          "se haga coronar rey",
          "se sepa todas las fechas de memoria",
          "se meta en política algún día",
          "dé un discurso que nadie ha pedido",
          "use mal una máquina del tiempo al instante",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "se líe con un desconocido esta noche",
          "tenga el historial de búsqueda más salvaje",
          "mande un mensaje arriesgado ahora mismo",
          "tenga un OnlyFans secreto",
          "bese a alguien de esta sala",
          "tenga un fetiche secreto",
          "se acueste con alguien en vacaciones",
          "lo pillen teniendo sexo en público",
          "tenga un vídeo porno circulando por ahí",
          "salga con dos personas a la vez",
          "mande nudes al grupo sin querer",
          "lo finja para terminar antes",
          "tenga la lista de ligues más larga de aquí",
          "se vaya a casa con alguien esta noche",
          "tenga un rollo de una noche y se pille",
          "haya tenido una cita de la que nadie aquí se enteró",
          "se ponga rojo como un tomate durante un lap dance",
          "consiga un descuento ligando",
          "le haya escrito por privado a alguien y nunca lo haya contado",
          "haga trampa el primero en Verdad o Reto",
          "se haya liado con el ex de alguien de esta sala",
          "mande el primer nude en una relación nueva",
          "haya dicho el nombre equivocado en la cama",
          "cruce la ciudad por un rollo de una noche",
          "tenga un segundo perfil secreto en una app de citas",
          "se arrepienta más del rollo del fin de semana pasado",
          "le haya hecho ghosting a alguien justo después de intimar",
        ],
      },
      date: {
        label: "🌹 Cita",
        prompts: [
          "en secreto disfrute de que le agarren del cuello en la cama",
          "disfrute llevando el control en la cama",
          "prefiera ceder el control en la cama",
          "dé el primer paso esta noche",
          "esté pensando en un beso ahora mismo",
          "sea el más ruidoso en la cama",
          "se pille antes después de un buen polvo",
          "tenga el pensamiento más guarro ahora mismo",
          "atraiga al otro primero",
          "tenga un fetiche que nadie adivinaría",
          "bese primero sin preguntar",
          "se deje dar largas más tiempo",
          "escriba primero después de una primera cita",
          "convierta una mirada en algo más",
          "aguante la mirada más tiempo",
          "hable más en la cama",
          "se ponga rojo cuando la cosa se pone concreta",
          "se enamore después de una sola noche",
          "nunca diga lo que realmente quiere",
          "ligue sin darse cuenta",
          "acabe el primero en casa de alguien al final de la noche",
          "sea el más fácil de seducir",
          "se tome más tiempo en la cama",
          "haga las preguntas más directas",
          "tenga más experiencia pero nunca lo admita",
          "dé el último paso al despedirse",
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.MostLikely = MOST_LIKELY;
})(window);
