// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/nhie.js — content for Never Have I Ever (NSFW, adults only)
 *
 * EDIT ME. Pure content. Each entry completes "Never have I ever ___" — write
 * just the predicate (lowercase verb phrase), the game adds the prefix. Keep
 * them confession-worthy. The 🔞 pool is where it bites.
 */
(function (global) {
  "use strict";

  var NHIE = {
    de: {
      general: {
        label: "🎲 Allgemein",
        prompts: [
          "auf einer Party eingeschlafen",
          "jemanden geghostet",
          "über mein Alter gelogen",
          "mir einen Knochen gebrochen",
          "nüchtern Karaoke gesungen",
          "im Kino bei einem Film geweint",
          "das Profil meiner/meines Ex heimlich gestalkt",
          "krankgemacht, obwohl ich kerngesund war",
          "im Lebenslauf geflunkert",
          "wegen eines TikToks geheult",
          "eine Freundin oder einen Freund geghostet",
          "so getan, als hätte ich ein Buch gelesen",
          "absichtlich einen Anruf weggedrückt",
          "meinen eigenen Namen gegoogelt",
          "ein Geschenk weiterverschenkt",
          "wegen eines Spielergebnisses geweint",
          "auf jemanden auf einer Dating-App gematcht und nie geschrieben",
          "einen ganzen Monatslohn an einem Wochenende verprasst",
          "stundenlang den Liefer-Tracker meiner Bestellung angestarrt",
          "einen alten Post von mir gelöscht, weil er mir peinlich war",
          "einer Influencerin oder einem Influencer geglaubt und Geld verschwendet",
        ],
      },
      party: {
        label: "🎉 Party",
        prompts: [
          "vom Trinken gekotzt",
          "einen Filmriss gehabt und eine Nacht vergessen",
          "betrunken einer/einem Ex geschrieben",
          "auf einer Partynacht mein Handy verloren",
          "einen Walk of Shame hingelegt",
          "aus einer Bar geflogen",
          "an einem fremden Ort aufgewacht und nicht gewusst, wo ich bin",
          "betrunken einen kompletten Fremden geküsst",
          "die letzte Runde Shots bestellt, die keiner mehr wollte",
          "auf dem Heimweg in ein Gebüsch gekotzt",
          "betrunken Essen für 50 Euro bestellt",
          "auf einer Party in fremden Klamotten aufgewacht",
          "betrunken meiner Chefin oder meinem Chef geschrieben",
          "morgens noch in Partyklamotten zur Arbeit gegangen",
          "auf einer Party geweint und niemandem gesagt, warum",
          "betrunken einer ganzen Bar eine Runde ausgegeben",
          "auf einem Tisch getanzt",
          "in der falschen WhatsApp-Gruppe etwas Peinliches geschrieben",
          "betrunken behauptet, ich sei der beste Tänzer der Welt",
          "im Club die Schuhe verloren",
          "bei einem Afterparty-Streit den Schiedsrichter gespielt",
        ],
      },
      leisure: {
        label: "🏖️ Freizeit & Urlaub",
        prompts: [
          "im Flugzeug eingeschlafen",
          "einen Flug verpasst",
          "im Urlaub einen Sonnenstich bekommen",
          "im Meer nackt gebadet",
          "mich im Urlaub komplett verlaufen",
          "auf einem Festival im Matsch geschlafen",
          "den Koffer am Flughafen verloren",
          "im Hotel das Buffet komplett geplündert",
          "einen Roadtrip ohne festen Plan gemacht",
          "im Urlaub viel mehr ausgegeben als geplant",
        ],
      },
      history: {
        label: "🏛️ Politik & Geschichte",
        prompts: [
          "freiwillig ein Museum besucht",
          "im Geschichtsunterricht eingeschlafen",
          "eine historische Stätte besichtigt",
          "eine ganze Geschichts-Doku zu Ende geschaut",
          "an einer Demo teilgenommen",
          "bei einer Wahl gewählt",
          "mit jemandem über Politik gestritten",
          "den Namen meines Bürgermeisters nicht gewusst",
          "eine Burg oder ein Schloss besichtigt",
          "ein Geschichtsbuch freiwillig gelesen",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "einen One-Night-Stand gehabt",
          "ein Nacktfoto verschickt",
          "mit jemandem in diesem Raum was gehabt",
          "es vorgetäuscht",
          "es dem Mile-High-Club gleichgetan",
          "einen Dreier gehabt",
          "mit einer Kollegin/einem Kollegen was gehabt",
          "heute Porno geschaut",
          "an einem öffentlichen Ort Sex gehabt",
          "Handschellen im Bett benutzt",
          "ein Nacktfoto an die falsche Person geschickt",
          "eine Freundschaft Plus gehabt",
          "in flagranti erwischt worden",
          "einen One-Night-Stand gehabt, von dem ich nie jemandem erzählt habe",
          "für einen Lapdance bezahlt",
          "jemanden vom gleichen Geschlecht geküsst",
          "schon beim ersten Date was gehabt",
          "irgendwo in diesem Gebäude Sex gehabt",
          "beim Sex den falschen Namen gerufen",
          "ein Sexspielzeug benutzt",
          "mit jemandem geschlafen, den ich online kennengelernt habe",
          "zu zweit geduscht",
          "beim Sex die Nachbarn gestört",
          "ein Rollenspiel im Bett ausprobiert",
          "jemanden beim Fremdgehen erwischt",
          "schon am ersten Date übernachtet",
          "mit dem Licht an geschlafen, obwohl ich's sonst nie mache",
          "während eines Dates an jemand anderen gedacht",
        ],
      },
      date: {
        label: "🌹 Date",
        prompts: [
          "es geliebt, beim Sex gewürgt zu werden",
          "auf einem ersten Date schon gewusst, dass heute noch was geht",
          "mir mitten im Gespräch vorgestellt, wie mein Date im Bett ist",
          "jemanden nur mit ein paar Nachrichten total angemacht",
          "im Bett komplett die Kontrolle abgegeben",
          "jemanden geküsst, weil die Spannung einfach zu krass war",
          "es geliebt, gegen die Wand gedrückt zu werden",
          "jemandem auf die Lippen gestarrt, während er geredet hat",
          "im Bett ausgesprochen, worauf ich wirklich Bock hab",
          "jemanden gesehen und sofort gedacht: den/die will ich",
          "beim Küssen die Augen aufgemacht, um zu gucken",
          "vor einem Date überlegt, wie weit der Abend geht",
          "jemandem am Hals geküsst und gemerkt, dass es sofort wirkt",
          "mich extra zurückgehalten, um die Spannung länger auszuhalten",
          "auf einem Date unter dem Tisch berührt worden",
          "jemandem direkt gesagt, was ich mit ihm oder ihr machen will",
          "mitten im Bett angefangen zu lachen",
          "jemanden angeschrieben, nur weil ich gerade Lust hatte",
          "nach einem Kuss nicht mehr klar denken können",
          "jemandem beim Ausziehen zugesehen und nichts gesagt",
          "eine ganze Nacht wach geblieben, nur um zu reden und zu küssen",
          "gemerkt, dass jemand mich will, bevor ein Wort gefallen ist",
          "jemanden verlassen wollen und trotzdem geblieben, weil der Sex zu gut war",
          "beim Sex an eine Fantasie gedacht, die ich nie erzählt habe",
          "jemandem den Nacken geküsst, nur um zu sehen, was passiert",
          "mich in jemanden verguckt, nur weil er oder sie gut geküsst hat",
        ],
      },
    },
    en: {
      general: {
        label: "🎲 General",
        prompts: [
          "fallen asleep at a party",
          "ghosted someone",
          "lied about my age",
          "broken a bone",
          "sung karaoke sober",
          "cried at a film in the cinema",
          "stalked an ex's profile online",
          "called in sick when I was perfectly fine",
          "lied on my CV",
          "cried over a TikTok",
          "ghosted a friend",
          "pretended I'd read a book",
          "ignored a call on purpose",
          "googled my own name",
          "re-gifted a present",
          "cried over a match result",
          "matched with someone on a dating app and never messaged them",
          "blown a whole month's pay in one weekend",
          "stared at the delivery tracker for hours",
          "deleted an old post because it embarrassed me",
          "wasted money because an influencer told me to",
        ],
      },
      party: {
        label: "🎉 Party",
        prompts: [
          "thrown up from drinking",
          "blacked out and forgotten a night",
          "texted an ex while drunk",
          "lost my phone on a night out",
          "done a walk of shame",
          "been kicked out of a bar",
          "woken up somewhere random with no idea where I was",
          "drunkenly kissed a complete stranger",
          "ordered a last round of shots nobody wanted",
          "thrown up in a bush on the way home",
          "drunk-ordered 50 euros of food",
          "woken up wearing someone else's clothes",
          "drunk-texted my boss",
          "gone to work still in last night's clothes",
          "cried at a party and told no one why",
          "drunkenly bought the whole bar a round",
          "danced on a table",
          "posted something embarrassing in the wrong group chat",
          "drunkenly claimed I was the best dancer alive",
          "lost my shoes in the club",
          "played referee in an after-party argument",
        ],
      },
      leisure: {
        label: "🏖️ Leisure & Travel",
        prompts: [
          "fallen asleep on a plane",
          "missed a flight",
          "got heatstroke on holiday",
          "skinny dipped in the sea",
          "got completely lost on holiday",
          "slept in the mud at a festival",
          "lost my suitcase at the airport",
          "completely raided a hotel buffet",
          "done a road trip with no real plan",
          "spent way more on holiday than planned",
        ],
      },
      history: {
        label: "🏛️ Politics & History",
        prompts: [
          "visited a museum voluntarily",
          "fallen asleep in history class",
          "toured a historical site",
          "finished a whole history documentary",
          "been to a protest",
          "voted in an election",
          "argued with someone about politics",
          "forgotten my mayor's name",
          "toured a castle",
          "read a history book for fun",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "had a one-night stand",
          "sent a nude",
          "hooked up with someone in this room",
          "faked it",
          "joined the mile-high club",
          "had a threesome",
          "hooked up with a coworker",
          "watched porn today",
          "had sex in a public place",
          "used handcuffs in bed",
          "sent a nude to the wrong person",
          "had a friend with benefits",
          "been caught in the act",
          "had a one-night stand I never told anyone about",
          "paid for a lap dance",
          "kissed someone of the same sex",
          "hooked up on a first date",
          "had sex somewhere in this building",
          "called out the wrong name during sex",
          "used a sex toy",
          "slept with someone I met online",
          "showered with someone",
          "annoyed the neighbours having sex",
          "tried roleplay in bed",
          "caught someone cheating",
          "stayed over on a first date",
          "kept the lights on even though I never usually do",
          "thought about someone else during a date",
        ],
      },
      date: {
        label: "🌹 Date",
        prompts: [
          "loved being choked in bed",
          "known on a first date it was definitely happening tonight",
          "pictured what my date is like in bed, mid-conversation",
          "turned someone on with just a few texts",
          "completely given up control in bed",
          "kissed someone because the tension was just too much",
          "loved being pushed up against a wall",
          "stared at someone's lips while they were talking",
          "said out loud in bed exactly what I was into",
          "seen someone and instantly thought: I want them",
          "opened my eyes mid-kiss just to look",
          "worked out before a date how far the night would go",
          "kissed someone's neck and felt it land instantly",
          "deliberately held back just to draw the tension out longer",
          "been touched under the table on a date",
          "told someone straight up what I wanted to do to them",
          "started laughing in the middle of sex",
          "texted someone purely because I was in the mood",
          "been unable to think straight after a kiss",
          "watched someone undress and said nothing",
          "stayed up all night just talking and kissing",
          "known someone wanted me before a word was said",
          "wanted to leave someone but stayed because the sex was too good",
          "thought about a fantasy during sex that I've never told anyone",
          "kissed the back of someone's neck just to see what happened",
          "caught feelings for someone just because they kissed well",
        ],
      },
    },
    es: {
      general: {
        label: "🎲 General",
        prompts: [
          "me he quedado dormido en una fiesta",
          "le he hecho ghosting a alguien",
          "he mentido sobre mi edad",
          "me he roto un hueso",
          "he cantado karaoke sobrio",
          "he llorado con una peli en el cine",
          "he cotilleado el perfil de un ex",
          "he llamado diciendo que estaba enfermo estando perfectamente",
          "he mentido en mi currículum",
          "he llorado con un TikTok",
          "le he hecho ghosting a un amigo",
          "he fingido haber leído un libro",
          "he ignorado una llamada a propósito",
          "me he buscado en Google",
          "he regalado un regalo que me habían hecho a mí",
          "he llorado por el resultado de un partido",
          "he hecho match con alguien en una app de citas y nunca le he escrito",
          "me he fundido el sueldo de un mes en un fin de semana",
          "me he pasado horas mirando el seguimiento de un pedido",
          "he borrado una publicación antigua porque me daba vergüenza",
          "he tirado el dinero porque me lo dijo un influencer",
        ],
      },
      party: {
        label: "🎉 Fiesta",
        prompts: [
          "he vomitado por beber",
          "he perdido el recuerdo de una noche entera",
          "le he escrito a un ex estando borracho",
          "he perdido el móvil de fiesta",
          "he hecho el paseo de la vergüenza",
          "me han echado de un bar",
          "me he despertado en un sitio random sin saber dónde estaba",
          "me he liado borracho con un completo desconocido",
          "he pedido una última ronda de chupitos que nadie quería",
          "he vomitado en un arbusto de camino a casa",
          "he pedido 50 euros de comida a domicilio estando borracho",
          "me he despertado con la ropa de otra persona",
          "le he escrito a mi jefe estando borracho",
          "he ido a trabajar con la ropa de la noche anterior",
          "he llorado en una fiesta sin contarle a nadie por qué",
          "he invitado borracho a todo el bar a una ronda",
          "he bailado encima de una mesa",
          "he mandado algo vergonzoso al grupo equivocado",
          "he asegurado borracho que era el mejor bailarín del mundo",
          "he perdido los zapatos en la discoteca",
          "he hecho de árbitro en una pelea en el after",
        ],
      },
      leisure: {
        label: "🏖️ Ocio y viajes",
        prompts: [
          "me he dormido en un avión",
          "he perdido un vuelo",
          "he pillado una insolación de vacaciones",
          "me he bañado desnudo en el mar",
          "me he perdido por completo de vacaciones",
          "he dormido en el barro en un festival",
          "he perdido la maleta en el aeropuerto",
          "he arrasado con un bufé de hotel",
          "he hecho un road trip sin ningún plan",
          "me he gastado en vacaciones mucho más de lo previsto",
        ],
      },
      history: {
        label: "🏛️ Política e historia",
        prompts: [
          "he visitado un museo por voluntad propia",
          "me he dormido en clase de historia",
          "he visitado un lugar histórico",
          "he terminado un documental de historia entero",
          "he ido a una manifestación",
          "he votado en unas elecciones",
          "he discutido con alguien sobre política",
          "he olvidado el nombre de mi alcalde",
          "he visitado un castillo",
          "he leído un libro de historia por gusto",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "he tenido un rollo de una noche",
          "he mandado un nude",
          "me he liado con alguien de esta sala",
          "he fingido un orgasmo",
          "lo he hecho en un avión",
          "he hecho un trío",
          "me he liado con un compañero de trabajo",
          "he visto porno hoy",
          "he tenido sexo en un lugar público",
          "he usado esposas en la cama",
          "le he mandado un nude a la persona equivocada",
          "he tenido un follamigo",
          "me han pillado en plena faena",
          "he tenido un rollo de una noche que no le he contado a nadie",
          "he pagado por un lap dance",
          "he besado a alguien de mi mismo sexo",
          "me he liado con alguien en la primera cita",
          "he tenido sexo en algún lugar de este edificio",
          "he dicho el nombre equivocado durante el sexo",
          "he usado un juguete sexual",
          "me he acostado con alguien que conocí por internet",
          "me he duchado con alguien",
          "he molestado a los vecinos teniendo sexo",
          "he probado un juego de rol en la cama",
          "he pillado a alguien poniendo los cuernos",
          "me he quedado a dormir en una primera cita",
          "he dejado la luz encendida aunque normalmente nunca lo hago",
          "he pensado en otra persona durante una cita",
        ],
      },
      date: {
        label: "🌹 Cita",
        prompts: [
          "he disfrutado de que me agarren del cuello en la cama",
          "he sabido en la primera cita que esa noche pasaba algo seguro",
          "me he imaginado cómo es mi cita en la cama en mitad de la conversación",
          "he puesto cachondo a alguien con solo unos mensajes",
          "he cedido el control por completo en la cama",
          "he besado a alguien porque la tensión era insoportable",
          "he disfrutado de que me empujen contra la pared",
          "me he quedado mirando los labios de alguien mientras hablaba",
          "he dicho en voz alta en la cama exactamente lo que me ponía",
          "he visto a alguien y he pensado al instante: lo quiero",
          "he abierto los ojos en mitad de un beso solo para mirar",
          "he calculado antes de una cita hasta dónde llegaría la noche",
          "he besado el cuello de alguien y he notado que le llegaba al instante",
          "me he contenido a propósito para alargar la tensión",
          "me han tocado por debajo de la mesa en una cita",
          "le he dicho a alguien sin rodeos lo que quería hacerle",
          "me he echado a reír en mitad del sexo",
          "le he escrito a alguien solo porque me apetecía",
          "no he podido pensar con claridad después de un beso",
          "he visto a alguien desnudarse sin decir nada",
          "me he pasado la noche entera hablando y besándome",
          "he sabido que alguien me deseaba antes de que dijera una palabra",
          "he querido dejar a alguien pero me he quedado porque el sexo era demasiado bueno",
          "he pensado durante el sexo en una fantasía que nunca le he contado a nadie",
          "he besado a alguien en la nuca solo para ver qué pasaba",
          "me he pillado de alguien solo porque besaba bien",
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.NHIE = NHIE;
})(window);
