// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/princess.js — content for Princess Treatment (NSFW-ish, adults)
 *
 * EDIT ME. Pure content. Each round shows a thing a partner does; the table
 * debates: is it Princess Treatment 👑 (going above and beyond) or just the
 * Bare Minimum 😐? The target alternates every round between Princess (aimed at
 * the women) and King (aimed at the men), so prompts are split by gender and
 * grouped by category.
 *
 * AUDIENCE: this is played by early-20s singles on dates / in the talking
 * stage, not by settled couples — so prompts lean dating-app era: first dates,
 * sleepovers, stories, read receipts, club nights. The best prompts are the
 * ones the table will actually FIGHT over (~70% split the room, ~30% are
 * clear-cut for rhythm and laughs).
 *
 * Bilingual: Spielecke.Princess = { de:{...}, en:{...} }. Both languages share
 * the SAME category keys and the same princess/king field names; the game reads
 * the current language's subtree via Spielecke.L(...).
 *
 * Structure: category -> { label, princess: [...], king: [...] }.
 *   - `princess` entries describe what's done FOR a woman.
 *   - `king` entries describe what's done FOR a man.
 */
(function (global) {
  "use strict";

  var PRINCESS = {
    de: {
      romance: {
        label: "💘 Romantik",
        princess: [
          "Er plant das ganze Date und zahlt",
          "Er schickt dir jeden Morgen eine Guten-Morgen-Nachricht",
          "Er merkt sich deinen halben Geburtstag",
          "Er schreibt dir einen handgeschriebenen Zettel",
          "Er gibt dir seine Jacke, wenn dir kalt ist",
          "Er fährt 40 Minuten, nur um dich 20 Minuten zu sehen",
          "Er merkt sich beim ersten Date deinen Lieblingsdrink — und bestellt ihn beim zweiten",
          "Er löscht seine Dating-Apps nach dem dritten Date von selbst",
          "Er stellt dich seinen Jungs schon nach zwei Wochen vor",
          "Er sagt dir nach dem ersten Kuss, dass er nur noch dich treffen will",
        ],
        king: [
          "Sie plant ein Überraschungs-Date am Abend",
          "Sie macht ihm vor seinen Freunden Komplimente",
          "Sie merkt sich den Namen seines besten Kumpels",
          "Sie stellt ihm eine Playlist zusammen",
          "Sie sagt Ja zum gemeinsamen Spiele-Schauen",
          "Sie schreibt dir nach dem Date zuerst, dass es schön war",
          "Sie löscht ihre Dating-Apps, ohne dass ihr drüber geredet habt",
          "Sie merkt sich, dass du eine Prüfung hattest, und fragt danach",
          "Sie stellt dich ihren Mädels schon nach dem dritten Date vor",
          "Sie zahlt beim zweiten Date wie selbstverständlich",
        ],
      },
      dailyLife: {
        label: "🏠 Alltag",
        princess: [
          "Er heizt dir das Auto vor",
          "Er schreibt innerhalb einer Stunde zurück",
          "Er spült ab, ohne dass du fragen musst",
          "Er trägt die schweren Tüten",
          "Er lässt dich das Restaurant aussuchen",
          "Er hat beim dritten Übernachten schon eine Zahnbürste für dich da",
          "Er bringt dir am Morgen danach Kaffee ans Bett",
          "Er leiht dir seinen Hoodie und sagt, du sollst ihn behalten",
          "Er bestellt dir Pommes mit, weil du „keinen Hunger“ hast",
          "Er bringt dich nachts nach Hause, obwohl er in die andere Richtung muss",
        ],
        king: [
          "Sie kocht unter der Woche Abendessen",
          "Sie lässt ihn einen Männerabend machen, ohne Fragen",
          "Sie tankt ihm das Auto voll",
          "Sie bringt ihm Kaffee ans Bett",
          "Sie schreibt nicht 20 Mal, wenn er unterwegs ist",
          "Sie macht dir am Morgen danach Frühstück",
          "Sie bringt zum Spontanbesuch was zu essen mit",
          "Sie gibt dir deinen Hoodie irgendwann freiwillig zurück",
          "Sie fragt, bevor sie sich aus deinem Kühlschrank bedient",
          "Sie lässt nicht nach zwei Übernachtungen schon Zeug bei dir liegen",
        ],
      },
      digital: {
        label: "📱 Digital",
        princess: [
          "Er antwortet auf deine Story, statt sie nur zu liken",
          "Er teilt seinen Live-Standort, ohne dass du fragen musst",
          "Er hat ein Foto von euch als Sperrbildschirm",
          "Er entfolgt seiner Ex, ohne dass du es ansprechen musst",
          "Er schreibt Absätze zurück, wenn du Absätze schreibst",
          "Er ruft an, statt nur zu texten",
          "Er antwortet dir auch, wenn er mit den Jungs unterwegs ist",
          "Er kommentiert öffentlich unter dein Bild, statt nur still zu liken",
          "Er schreibt „gut angekommen?“, ohne dass du es erwartest",
          "Er lässt dich nie auf „Gelesen“ hängen",
        ],
        king: [
          "Sie antwortet nicht erst nach drei Stunden mit „haha ja“",
          "Sie liket keine Bilder von anderen Typen mehr",
          "Sie postet dich in ihrer richtigen Story, nicht nur bei Close Friends",
          "Sie schickt dir Memes, die sie an dich erinnern",
          "Sie ruft dich betrunken an, weil sie an dich denken muss",
          "Sie schreibt dir zuerst „bist du noch wach?“",
          "Sie hat euren Chat oben angepinnt",
          "Sie nimmt deine FaceTime-Anrufe auch ungeschminkt an",
          "Sie hypet dein neues Bild in den Kommentaren",
          "Sie lässt dich nicht auf „Zugestellt“, während sie Storys postet",
        ],
      },
      goingOut: {
        label: "🎉 Ausgehen",
        princess: [
          "Er hält dir im Club die Hand, damit ihr euch nicht verliert",
          "Er sagt anderen Frauen von selbst, dass er hier mit dir ist",
          "Er holt dir zwischen den Drinks ungefragt ein Wasser",
          "Er hält dir die Haare, wenn der Abend zu lang war",
          "Er wartet, bis du sicher in deiner Wohnung bist, bevor er geht",
          "Er tanzt mit dir, obwohl er eigentlich nie tanzt",
          "Er verteidigt dich, wenn jemand blöd über dich redet",
          "Er zahlt deine Drinks den ganzen Abend",
          "Er lässt seine Jungs warten, um dich noch ins Taxi zu setzen",
          "Er merkt von allein, wenn dir ein Typ zu aufdringlich wird",
        ],
        king: [
          "Sie stellt dich nicht als „nur ein Freund“ vor",
          "Sie tanzt den ganzen Abend nur mit dir",
          "Sie bringt dir von der Raucherpause Pommes mit",
          "Sie teilt ihre Pommes mit dir",
          "Sie passt auf deinen Drink auf, wenn du aufs Klo gehst",
          "Sie schwärmt ihren Mädels von dir vor, während du danebenstehst",
          "Sie küsst dich vor allen Leuten, nicht nur heimlich",
          "Sie geht früher mit, weil du müde bist",
          "Sie flirtet nicht mit dem Barkeeper für Freigetränke",
          "Sie bleibt bei dir, statt die ganze Nacht mit ihren Mädels zu verschwinden",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        princess: [
          "Er sorgt immer dafür, dass du zuerst kommst",
          "Er schickt mitten im Arbeitstag eine versaute Nachricht",
          "Er weckt dich mit Morgensex",
          "Er lässt dir ein Bad ein und steigt mit rein",
          "Er geht gern runter, ohne etwas zurückzuerwarten",
          "Er sorgt auch beim One-Night-Stand dafür, dass du zuerst kommst",
          "Er holt dir danach ungefragt ein Glas Wasser",
          "Er bleibt danach zum Kuscheln, statt sich sofort anzuziehen",
          "Er schreibt dir am Morgen nach der ersten Nacht zuerst",
          "Er macht dir danach ein Kompliment, das nichts mit deinem Körper zu tun hat",
          "Er merkt sich, was du im Bett magst, ohne dass du's zweimal sagen musst",
          "Er fragt aktiv nach, ob's dir gefällt, statt einfach weiterzumachen",
          "Er lässt dich nach dem ersten Mal nicht komisch dastehen mit einer Ausrede",
          "Er räumt danach das Zimmer auf, ohne dass du fragst",
          "Er sorgt dafür, dass du dich sicher fühlst, bevor überhaupt was passiert",
          "Er nennt dich am nächsten Tag beim Namen, nicht „Babe“",
        ],
        king: [
          "Sie schickt ihm tagsüber ein freches Foto",
          "Sie ergreift mehr als die Hälfte der Zeit die Initiative",
          "Sie überrascht ihn mit einem Striptease",
          "Sie lässt ihn im Bett alles aussuchen",
          "Sie schreibt ihm zuerst was Versautes, während er unterwegs ist",
          "Sie sagt dir im Bett genau, was sie will, statt dich raten zu lassen",
          "Sie schreibt dir nach der ersten gemeinsamen Nacht zuerst",
          "Sie macht den ersten Schritt, wenn du zu lange zögerst",
          "Sie bleibt danach zum Kuscheln, statt sofort das Handy zu checken",
          "Sie erzählt ihren Mädels nur die guten Details",
          "Sie merkt sich seine Vorlieben, ohne dass er's erklären muss",
          "Sie fragt ihn, was er mag, statt automatisch das eigene Ding durchzuziehen",
          "Sie macht ihm keinen Vorwurf, wenn's beim ersten Mal nicht perfekt läuft",
          "Sie bleibt entspannt, wenn er nervös ist, statt es komisch zu finden",
          "Sie lädt ihn aktiv zu einem zweiten Date ein, statt abzuwarten",
          "Sie schreibt ihm nach dem Date, dass sie's genossen hat",
        ],
      },
      date: {
        label: "🌹 Date",
        princess: [
          "Er legt dir beim Knutschen die Hand an den Hals",
          "Er drückt dich beim Küssen gegen die Wand",
          "Er flüstert dir ins Ohr, was er später mit dir vorhat",
          "Er guckt dir beim Küssen in die Augen",
          "Er zieht dich am ersten Abend eng an sich",
          "Er packt dir beim Küssen in die Haare",
          "Er küsst dich zuerst am Hals, nicht auf den Mund",
          "Er hält beim Küssen die Augen offen",
          "Er sagt dir, was ihm an dir gefällt, bevor überhaupt was passiert",
          "Er fragt dich, was du willst, statt es einfach zu machen",
          "Er lässt dich beim ersten Mal das Tempo bestimmen",
          "Er zieht dich am Handgelenk zu sich",
          "Er küsst dich mitten im Satz",
          "Er hört auf, nur um dich anzusehen",
          "Er flüstert dir zu, dass du bleiben sollst",
          "Er nimmt sich Zeit, bevor irgendwas passiert",
        ],
        king: [
          "Sie sagt ihm, dass sie auf 'ne Hand am Hals steht",
          "Sie macht beim ersten Mal den ersten Schritt",
          "Sie flüstert ihm ins Ohr, worauf sie Bock hat",
          "Sie zieht ihn am Kragen zu sich ran",
          "Sie übernimmt im Bett mal komplett",
          "Sie sagt ihm direkt, worauf sie steht",
          "Sie legt ihm beim Küssen die Hand ins Gesicht",
          "Sie setzt sich ihm auf den Schoß, ohne zu fragen",
          "Sie sagt ihm, dass sie ihn will, statt zu warten",
          "Sie beißt ihm sanft in die Lippe",
          "Sie zieht ihn an der Hand ins Schlafzimmer",
          "Sie hält beim Küssen den Blickkontakt",
          "Sie lässt ihn beim ersten Mal führen",
          "Sie küsst ihn mitten im Streit",
          "Sie sagt ihm hinterher, was ihr am besten gefallen hat",
          "Sie macht den ersten Schritt, obwohl sie nervös ist",
        ],
      },
    },
    en: {
      romance: {
        label: "💘 Romance",
        princess: [
          "He plans the whole date and pays",
          "He sends good-morning texts every day",
          "He remembers your half-birthday",
          "He writes you a handwritten note",
          "He gives you his jacket when you're cold",
          "He drives 40 minutes just to see you for 20",
          "He remembers your favourite drink from the first date — and orders it on the second",
          "He deletes his dating apps after the third date, unprompted",
          "He introduces you to his boys after just two weeks",
          "He tells you after the first kiss that you're the only one he wants to see",
        ],
        king: [
          "She plans a surprise date night",
          "She compliments him in front of his friends",
          "She remembers his best mate's name",
          "She makes him a playlist",
          "She says yes to watching the game",
          "She texts you first after the date to say she had a great time",
          "She deletes her dating apps without you two ever talking about it",
          "She remembers you had an exam and asks how it went",
          "She introduces you to her girls by the third date",
          "She pays on the second date like it's nothing",
        ],
      },
      dailyLife: {
        label: "🏠 Daily Life",
        princess: [
          "He warms up the car for you",
          "He texts back within an hour",
          "He does the dishes without being asked",
          "He carries the heavy bags",
          "He lets you pick the restaurant",
          "He has a spare toothbrush ready by the third sleepover",
          "He brings you coffee in bed the morning after",
          "He lends you his hoodie and tells you to keep it",
          "He orders you fries too because you're \"not hungry\"",
          "He takes you home at night even though he lives the other way",
        ],
        king: [
          "She cooks dinner on a weeknight",
          "She lets him have a guys' night, no questions",
          "She fills up his car with petrol",
          "She brings him a coffee in bed",
          "She doesn't text 20 times when he's out",
          "She makes you breakfast the morning after",
          "She brings food when she comes over spontaneously",
          "She actually gives your hoodie back one day, unprompted",
          "She asks before raiding your fridge",
          "She doesn't start leaving her stuff at yours after two sleepovers",
        ],
      },
      digital: {
        label: "📱 Digital",
        princess: [
          "He replies to your story instead of just liking it",
          "He shares his live location without you having to ask",
          "He has a photo of you two as his lock screen",
          "He unfollows his ex without you having to bring it up",
          "He texts paragraphs back when you text paragraphs",
          "He calls instead of just texting",
          "He still replies when he's out with the boys",
          "He comments on your post publicly instead of just quietly liking it",
          "He texts \"home safe?\" without you having to expect it",
          "He never leaves you on read",
        ],
        king: [
          "She doesn't reply \"haha yeah\" three hours later",
          "She stops liking other guys' pictures",
          "She posts you on her main story, not just close friends",
          "She sends you memes that made her think of you",
          "She drunk-calls you because she can't stop thinking about you",
          "She texts you first asking \"you still up?\"",
          "She has your chat pinned to the top",
          "She answers your FaceTime calls without makeup on",
          "She hypes up your new picture in the comments",
          "She doesn't leave you on delivered while posting stories",
        ],
      },
      goingOut: {
        label: "🎉 Going Out",
        princess: [
          "He holds your hand in the club so you don't lose each other",
          "He tells other women himself that he's here with you",
          "He gets you a water between drinks without being asked",
          "He holds your hair back when the night got too long",
          "He waits until you're safely inside before leaving",
          "He dances with you even though he never dances",
          "He defends you when someone talks trash about you",
          "He pays for your drinks all night",
          "He keeps his boys waiting to put you in a taxi first",
          "He notices on his own when a guy won't leave you alone",
        ],
        king: [
          "She doesn't introduce you as \"just a friend\"",
          "She dances only with you all night",
          "She brings you fries back from the smoking break",
          "She shares her fries with you",
          "She watches your drink when you go to the bathroom",
          "She gushes about you to her girls while you're standing right there",
          "She kisses you in front of everyone, not just in secret",
          "She leaves early with you because you're tired",
          "She doesn't flirt with the bartender for free drinks",
          "She stays with you instead of vanishing with her girls all night",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        princess: [
          "He always makes sure you finish first",
          "He sends a filthy text in the middle of your work day",
          "He wakes you up with morning sex",
          "He runs you a bath and gets in too",
          "He's happy to go down with nothing in return",
          "He makes sure you finish first, even on a one-night stand",
          "He gets you a glass of water after, unasked",
          "He stays to cuddle instead of getting dressed right away",
          "He texts you first the morning after your first night",
          "He compliments you after on something that isn't your body",
          "He remembers what you like in bed without being told twice",
          "He actually checks in that you're enjoying it instead of just continuing",
          "He doesn't leave you standing there awkwardly with an excuse after the first time",
          "He tidies the room after, without you asking",
          "He makes sure you feel safe before anything happens",
          "He uses your actual name the next day, not \"babe\"",
        ],
        king: [
          "She sends him a cheeky pic during the day",
          "She initiates more than half the time",
          "She surprises him with a striptease",
          "She lets him pick anything in the bedroom",
          "She sexts him first while he's out",
          "She tells you exactly what she wants in bed instead of making you guess",
          "She texts you first after your first night together",
          "She makes the first move when you hesitate too long",
          "She stays to cuddle instead of checking her phone right after",
          "She only tells her girls the good details",
          "She remembers his preferences without him having to explain",
          "She asks what he likes instead of just doing her own thing",
          "She doesn't make him feel bad if the first time isn't perfect",
          "She stays chill if he's nervous instead of making it weird",
          "She's the one who suggests a second date instead of waiting",
          "She texts him after the date to say she had a good time",
        ],
      },
      date: {
        label: "🌹 Date",
        princess: [
          "He puts his hand on your throat while you make out",
          "He pushes you against the wall when he kisses you",
          "He whispers in your ear what he's gonna do to you later",
          "He looks you in the eyes while kissing you",
          "He pulls you in close on the first night",
          "He grabs a handful of your hair when he kisses you",
          "He kisses your neck before your mouth",
          "He keeps his eyes open when he kisses you",
          "He tells you what he likes about you before anything even happens",
          "He asks what you want instead of just doing it",
          "He lets you set the pace the first time",
          "He pulls you in by the wrist",
          "He kisses you mid-sentence",
          "He stops just to look at you",
          "He whispers that he wants you to stay",
          "He takes his time before anything happens",
        ],
        king: [
          "She tells him she's into a hand on her throat",
          "She makes the first move the first time",
          "She whispers in his ear what she's up for",
          "She pulls him in by the collar",
          "She takes over completely in bed",
          "She tells him straight up what she's into",
          "She puts her hand on his face when she kisses him",
          "She sits on his lap without asking",
          "She tells him she wants him instead of waiting",
          "She bites his lip gently",
          "She pulls him to the bedroom by the hand",
          "She holds eye contact while kissing him",
          "She lets him lead the first time",
          "She kisses him in the middle of an argument",
          "She tells him afterwards what she liked most",
          "She makes the first move even though she's nervous",
        ],
      },
    },
    es: {
      romance: {
        label: "💘 Romance",
        princess: [
          "Él planea toda la cita y paga",
          "Él te manda un mensaje de buenos días cada día",
          "Él se acuerda de tu medio cumpleaños",
          "Él te escribe una nota a mano",
          "Él te deja su chaqueta cuando tienes frío",
          "Él conduce 40 minutos solo para verte 20",
          "Él recuerda tu bebida favorita de la primera cita — y te la pide en la segunda",
          "Él borra sus apps de citas tras la tercera cita, sin que se lo pidas",
          "Él te presenta a sus amigos a las dos semanas",
          "Él te dice tras el primer beso que eres la única a la que quiere ver",
        ],
        king: [
          "Ella planea una noche de cita sorpresa",
          "Ella le hace un cumplido delante de sus amigos",
          "Ella se acuerda del nombre de su mejor amigo",
          "Ella le hace una playlist",
          "Ella dice que sí a ver el partido",
          "Ella te escribe primero después de la cita para decirte que se lo pasó genial",
          "Ella borra sus apps de citas sin que lo hayáis hablado nunca",
          "Ella se acuerda de que tenías un examen y te pregunta qué tal fue",
          "Ella te presenta a sus amigas en la tercera cita",
          "Ella paga en la segunda cita como si nada",
        ],
      },
      dailyLife: {
        label: "🏠 Día a día",
        princess: [
          "Él te calienta el coche",
          "Él contesta en menos de una hora",
          "Él friega los platos sin que se lo pidan",
          "Él carga con las bolsas pesadas",
          "Él te deja elegir el restaurante",
          "Él tiene un cepillo de dientes de repuesto listo a la tercera noche",
          "Él te lleva café a la cama a la mañana siguiente",
          "Él te presta su sudadera y te dice que te la quedes",
          "Él te pide patatas también porque \"no tienes hambre\"",
          "Él te acompaña a casa por la noche aunque vive en la otra dirección",
        ],
        king: [
          "Ella hace la cena un día entre semana",
          "Ella le deja tener noche de chicos, sin preguntas",
          "Ella le llena el depósito del coche",
          "Ella le lleva un café a la cama",
          "Ella no le escribe 20 veces cuando sale",
          "Ella te hace el desayuno a la mañana siguiente",
          "Ella trae comida cuando se presenta de improviso",
          "Ella te devuelve un día la sudadera, sin que se lo pidas",
          "Ella pregunta antes de asaltar tu nevera",
          "Ella no empieza a dejar sus cosas en tu casa tras dos noches",
        ],
      },
      digital: {
        label: "📱 Digital",
        princess: [
          "Él responde a tu story en vez de solo darle like",
          "Él comparte su ubicación en tiempo real sin que se lo pidas",
          "Él tiene una foto de los dos en la pantalla de bloqueo",
          "Él deja de seguir a su ex sin que tengas que sacar el tema",
          "Él te contesta con párrafos cuando tú le escribes párrafos",
          "Él llama en vez de solo escribir",
          "Él sigue contestando cuando está con sus amigos",
          "Él comenta tu publicación en público en vez de solo darle like en silencio",
          "Él te escribe \"¿llegaste bien?\" sin que tengas que esperarlo",
          "Él nunca te deja en visto",
        ],
        king: [
          "Ella no contesta \"jaja sí\" tres horas después",
          "Ella deja de dar like a las fotos de otros chicos",
          "Ella te sube a su story principal, no solo a mejores amigos",
          "Ella te manda memes que le hicieron pensar en ti",
          "Ella te llama borracha porque no puede dejar de pensar en ti",
          "Ella te escribe primero preguntando \"¿sigues despierto?\"",
          "Ella tiene tu chat fijado arriba del todo",
          "Ella te coge el FaceTime sin maquillaje",
          "Ella te aplaude la foto nueva en los comentarios",
          "Ella no te deja en entregado mientras sube stories",
        ],
      },
      goingOut: {
        label: "🎉 Salir de fiesta",
        princess: [
          "Él te coge de la mano en la discoteca para no perderos",
          "Él les dice él mismo a otras chicas que ha venido contigo",
          "Él te trae agua entre copa y copa sin que se lo pidas",
          "Él te sujeta el pelo cuando la noche se ha alargado demasiado",
          "Él espera a que entres en casa antes de irse",
          "Él baila contigo aunque nunca baila",
          "Él te defiende cuando alguien habla mal de ti",
          "Él te paga las copas toda la noche",
          "Él hace esperar a sus amigos para meterte primero en un taxi",
          "Él se da cuenta solo cuando un tío no te deja en paz",
        ],
        king: [
          "Ella no te presenta como \"solo un amigo\"",
          "Ella baila solo contigo toda la noche",
          "Ella te trae patatas al volver de fumar",
          "Ella comparte sus patatas contigo",
          "Ella vigila tu copa cuando vas al baño",
          "Ella habla maravillas de ti a sus amigas estando tú delante",
          "Ella te besa delante de todos, no solo a escondidas",
          "Ella se va pronto contigo porque estás cansado",
          "Ella no tontea con el camarero para conseguir copas gratis",
          "Ella se queda contigo en vez de desaparecer toda la noche con sus amigas",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        princess: [
          "Él siempre se asegura de que tú acabes primero",
          "Él te manda un mensaje guarro en mitad de tu jornada de trabajo",
          "Él te despierta con sexo mañanero",
          "Él te prepara un baño y se mete contigo",
          "Él baja al pilón encantado sin esperar nada a cambio",
          "Él se asegura de que acabes primero, incluso en un rollo de una noche",
          "Él te trae un vaso de agua después, sin que se lo pidas",
          "Él se queda a hacer cucharita en vez de vestirse enseguida",
          "Él te escribe primero la mañana después de vuestra primera noche",
          "Él te hace un cumplido después sobre algo que no es tu cuerpo",
          "Él recuerda lo que te gusta en la cama sin que se lo digas dos veces",
          "Él te pregunta de verdad si lo estás disfrutando en vez de seguir sin más",
          "Él no te deja ahí plantada con una excusa después de la primera vez",
          "Él ordena la habitación después, sin que se lo pidas",
          "Él se asegura de que te sientas segura antes de que pase nada",
          "Él usa tu nombre de verdad al día siguiente, no \"cariño\"",
        ],
        king: [
          "Ella le manda una foto pícara durante el día",
          "Ella toma la iniciativa más de la mitad de las veces",
          "Ella le sorprende con un striptease",
          "Ella le deja elegir lo que quiera en la cama",
          "Ella le manda sexting primero mientras está fuera",
          "Ella te dice exactamente lo que quiere en la cama en vez de hacerte adivinar",
          "Ella te escribe primero después de vuestra primera noche juntos",
          "Ella da el primer paso cuando tú dudas demasiado",
          "Ella se queda a hacer cucharita en vez de mirar el móvil justo después",
          "Ella solo les cuenta a sus amigas los detalles buenos",
          "Ella recuerda sus preferencias sin que él tenga que explicarlas",
          "Ella le pregunta qué le gusta en vez de ir a lo suyo",
          "Ella no le hace sentir mal si la primera vez no es perfecta",
          "Ella se lo toma con calma si él está nervioso en vez de hacerlo raro",
          "Ella es quien propone una segunda cita en vez de esperar",
          "Ella le escribe después de la cita para decirle que se lo pasó bien",
        ],
      },
      date: {
        label: "🌹 Cita",
        princess: [
          "Él te pone la mano en el cuello mientras os enrolláis",
          "Él te empuja contra la pared cuando te besa",
          "Él te susurra al oído lo que te va a hacer luego",
          "Él te mira a los ojos mientras te besa",
          "Él te atrae hacia él la primera noche",
          "Él te agarra del pelo cuando te besa",
          "Él te besa el cuello antes que la boca",
          "Él mantiene los ojos abiertos cuando te besa",
          "Él te dice lo que le gusta de ti antes de que pase nada",
          "Él te pregunta qué quieres en vez de hacerlo sin más",
          "Él te deja marcar el ritmo la primera vez",
          "Él te atrae tirando de tu muñeca",
          "Él te besa en mitad de una frase",
          "Él se para solo para mirarte",
          "Él te susurra que quiere que te quedes",
          "Él se toma su tiempo antes de que pase nada",
        ],
        king: [
          "Ella le dice que le gusta una mano en el cuello",
          "Ella da el primer paso la primera vez",
          "Ella le susurra al oído lo que le apetece",
          "Ella tira de él por el cuello de la camisa",
          "Ella toma el control total en la cama",
          "Ella le dice sin rodeos lo que le pone",
          "Ella le pone la mano en la cara cuando le besa",
          "Ella se sienta en su regazo sin preguntar",
          "Ella le dice que le desea en vez de esperar",
          "Ella le muerde el labio suavemente",
          "Ella le lleva de la mano al dormitorio",
          "Ella le mantiene la mirada mientras le besa",
          "Ella le deja llevar la iniciativa la primera vez",
          "Ella le besa en mitad de una discusión",
          "Ella le dice después lo que más le gustó",
          "Ella da el primer paso aunque esté nerviosa",
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.Princess = PRINCESS;
})(window);
