// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/rankit.js — content for Rank It (NSFW, adults only)
 *
 * EDIT ME. Pure content. Bilingual: the export is a { de, en } bundle and the
 * game reads the current language's subtree via Spielecke.L(...). Each language
 * holds the same pool keys; within a pool, each SET is one round: a `title`
 * stating the axis you rank along (best → worst, biggest → smallest, …) and an
 * `items` list (aim for 5) that everyone privately puts in order. Drift from the
 * group's consensus and you lose. Item count is flexible — the game adapts.
 *
 * Each pool ALSO carries a `people` list: axis titles (title only, no items) used
 * by Rank It's "Mitspieler" mode, where the items are the current roster instead
 * of static content. The chosen category just decides the flavour of the axis
 * (Party → "Kotzt am ehesten → am spätesten", 18+ → "Steht am ehesten → am
 * wenigsten auf BDSM", …). Same `people` phrasing rules as `sets` titles.
 *
 * The title MUST contain a "→": the game splits on it to label the top/bottom
 * poles of the rail. Keep the DE and EN pool keys
 * (general/party/videogames/minecraft/leisure/history/football/nsfw) in sync so the
 * category chips line up in both languages.
 */
(function (global) {
  "use strict";

  var RANKIT = {
    de: {
      general: {
        label: "🎲 Allgemein",
        people: [
          { title: "Wird am ehesten → am spätesten berühmt" },
          { title: "Überlebt am längsten → am kürzesten in der Wildnis" },
          { title: "Käme am ehesten → am wenigsten ins Gefängnis" },
          { title: "Hat den vollsten → leersten Kühlschrank" },
          { title: "Überlebt am ehesten → am wenigsten die Zombie-Apokalypse" },
          { title: "Ist am ehesten → am wenigsten heimlich ein Genie" },
          { title: "Kommt am ehesten → am seltensten zu spät" },
          { title: "Würde am ehesten → am wenigsten für 1 Mio. € einen Finger opfern" },
        ],
        sets: [
          { title: "Beste → schlechteste Superkraft", items: ["Unsichtbarkeit", "Fliegen", "Zeitreise", "Gedankenlesen", "Teleportation"] },
          { title: "Bester → schlechtester Pizzabelag", items: ["Ananas", "Salami", "Pilze", "Extra Käse", "Sardellen"] },
          { title: "Wichtigste → unnötigste App", items: ["WhatsApp", "Instagram", "TikTok", "Google Maps", "Spotify"] },
          { title: "Traum- → Albtraum-Urlaub", items: ["Strandresort", "Städtetrip", "Camping", "Kreuzfahrt", "Skifahren"] },
          { title: "Bester → schlechtester Sonntag", items: ["Verkatert im Bett", "Großer Brunch", "Lange Wanderung", "Den ganzen Tag zocken", "Familienbesuch"] },
          { title: "Nützlichstes → nutzlosestes Schulfach", items: ["Mathe", "Sport", "Geschichte", "Kunst", "Religion"] },
          { title: "Bestes → schlechtestes Fast Food", items: ["McDonald's", "Burger King", "KFC", "Subway", "Der Döner um die Ecke"] },
          { title: "Wichtigste → unnötigste Erfindung", items: ["Internet", "Waschmaschine", "Smartphone", "Mikrowelle", "Selfie-Stick"] },
          { title: "Bester → schlechtester Streamingdienst", items: ["Netflix", "Disney+", "Amazon Prime", "YouTube Premium", "DAZN"] },
          { title: "Nervigster → harmlosester Mitbewohner-Typ", items: ["Der Geschirr-Stapler", "Der Dauerlaute", "Der Schmarotzer", "Der Putz-Nazi", "Der Geist (nie da)"] },
          { title: "Bestes → schlechtestes Haustier", items: ["Hund", "Katze", "Hamster", "Schlange", "Vogelspinne"] },
          { title: "Coolster → uncoolster Beruf", items: ["Pilot", "YouTuber", "Arzt", "Steuerberater", "Politiker"] },
          { title: "Wichtigstes → unwichtigstes Handy-Feature", items: ["Akkulaufzeit", "Kamera", "Speicherplatz", "Bildschirmgröße", "Die Farbe"] },
          { title: "Bester → schlechtester Wochentag", items: ["Freitag", "Samstag", "Sonntag", "Mittwoch", "Montag"] },
          { title: "Beste → schlechteste Jahreszeit", items: ["Sommer", "Frühling", "Herbst", "Winter", "Die nasse Woche dazwischen"] },
          { title: "Genialste → dümmste Ausrede fürs Zuspätkommen", items: ["Stau", "Wecker nicht gehört", "Bahn ausgefallen", "Dem Hund ging's schlecht", "Zeit vergessen"] },
          { title: "Nützlichste → überbewertetste Lebenskompetenz", items: ["Mit Geld umgehen", "Kochen", "Smalltalk", "Autofahren", "Schöne Handschrift"] },
          { title: "Bester → schlechtester Snack", items: ["Schokoriegel", "Chips", "Apfel", "Studentenfutter", "Kalter Kaffee"] },
          { title: "Beeindruckendster → lahmster Flex", items: ["Eigene Wohnung mit 22", "Teures Auto", "Viele Follower", "Sixpack", "Teures Wasser trinken"] },
          { title: "Bestes → schlechtestes Date-Gesprächsthema", items: ["Reisen", "Lieblingsmusik", "Familie", "Politik", "Der/die Ex"] },
          { title: "Wichtigster → unwichtigster Wert in einer Freundschaft", items: ["Ehrlichkeit", "Loyalität", "Humor", "Pünktlichkeit", "Gleicher Musikgeschmack"] },
        ],
      },
      party: {
        label: "🎉 Party",
        people: [
          { title: "Kotzt am ehesten → am spätesten" },
          { title: "Verträgt am meisten → am wenigsten" },
          { title: "Tanzt am wildesten → am steifsten" },
          { title: "Schreibt besoffen am ehesten → nie dem Ex" },
          { title: "Wird als Erstes → als Letztes rausgeworfen" },
          { title: "Pennt am ehesten → am spätesten weg" },
          { title: "Zettelt am ehesten → am wenigsten eine Schlägerei an" },
          { title: "Ist am ehesten → am wenigsten der/die Letzte auf der Tanzfläche" },
        ],
        sets: [
          { title: "Akzeptabelstes → schlimmstes Besoffen-Verhalten", items: ["Aufm Klo heulen", "Dem Ex schreiben", "Streit anzetteln", "Wegpennen", "Yappen"] },
          { title: "Stilvollster → peinlichster Drink", items: ["Champagner", "Craft Beer", "Tequila-Shots", "Tetrapack-Wein", "Jägerbombs"] },
          { title: "Größtes → kleinstes Party-Foul", items: ["Drinnen kotzen", "Alles kaputt machen", "Drink verschütten", "Früh abhauen", "Songs skippen"] },
          { title: "Bestes → schlechtestes Kater-Mittel", items: ["Fettiges Essen", "Konterbier", "Bis mittags pennen", "Wasser & Aspirin", "Gym"] },
          { title: "Fliegst am ehesten → am wenigsten raus", items: ["Schlägerei anzetteln", "Nacktbaden", "Den Gastgeber dissen", "In die Pflanze pinkeln", "Wegpennen"] },
          { title: "Bester → schlimmster, neben dem du festhängst", items: ["Der Vollsuff", "Der Yapper", "Der DJ", "Der Ex", "Der Chef"] },
          { title: "Bester → schlechtester Vorglüh-Drink", items: ["Aperol Spritz", "Wegbier", "Wodka-Mische", "Glühwein", "Lauwarmer Sekt"] },
          { title: "Bester → schlechtester Begleiter auf dem Heimweg", items: ["Der Nüchterne mit Snacks", "Der, der den Nachtbus kennt", "Der Taxi-Sponsor", "Der, der alle 50 Meter kotzen muss", "Der, der unbedingt noch weiterziehen will"] },
          { title: "Legendärste → peinlichste Tanzflächen-Aktion", items: ["Der Moonwalk", "Luftgitarre", "Wilder Breakdance", "An der Box twerken", "Einfach hinfallen"] },
          { title: "Beste → schlechteste Afterparty-Location", items: ["Hausi", "Am See", "Im Park", "Aufm Parkplatz", "An der Tanke"] },
          { title: "Größter → kleinster Partyheld", items: ["Der DJ", "Der mit dem Nachschub", "Der Gastgeber", "Der den Türsteher kennt", "Der Aufräumer"] },
          { title: "Bester → schlechtester Shot", items: ["Tequila", "Jägermeister", "Sambuca", "Wodka", "Mystery-Shot"] },
          { title: "Größtes → kleinstes WG-Party-Drama", items: ["Die Bullen kommen", "Nachbarn beschweren sich", "Jemand kotzt aufs Sofa", "Der Alk ist alle", "Aux-Kabel-Krieg"] },
          { title: "Bester → schlechtester Grund, eine Runde auszugeben", items: ["Geburtstag", "Beförderung", "Trennung überstanden", "Einfach so", "Aus schlechtem Gewissen"] },
          { title: "Coolster → cringigster Partytrick", items: ["Bier mitm Feuerzeug öffnen", "Kartentrick", "Beatboxen", "Bauchreden", "Witze, die keiner checkt"] },
          { title: "Beste → schlechteste Ausrede, früher zu gehen", items: ["Muss morgen früh raus", "Babysitter wartet", "Hund muss raus", "Bin einfach durch", "Einfach ghosten"] },
          { title: "Größte → kleinste Gefahr auf einer Hausparty", items: ["Die Treppe", "Der Pool", "Der Grill", "Die weiße Couch", "Der Wackelkontakt der Box"] },
          { title: "Bester → schlechtester Bier-Pong-Partner", items: ["Der Sniper", "Das Pick-me-Girl", "Der Trash-Talker", "Der Zittrige", "Der schon Dichte"] },
        ],
      },
      videogames: {
        label: "🎮 Videospiele",
        people: [
          { title: "Ragequittet am ehesten → nie" },
          { title: "Ist der/die beste → schlechteste Gamer:in" },
          { title: "Spammt am meisten → am wenigsten das Mic" },
          { title: "Schiebt die Schuld am ehesten → nie aufs Team" },
          { title: "Zockt am längsten → am kürzesten am Stück" },
          { title: "Gibt am meisten → am wenigsten Geld für Skins aus" },
          { title: "Campt am ehesten → pusht am ehesten" },
          { title: "Wirft am ehesten → nie den Controller" },
        ],
        sets: [
          // ── Allgemein ──
          { title: "Nervigster → harmlosester Gamer-Typ", items: ["Der Rage-Quitter", "Der Mic-Spammer", "Der Smurf", "Der Try-Hard", "Der AFK-Farmer"] },
          { title: "Beste → schlechteste Ausrede nach einer Niederlage", items: ["Lag", "Team war schuld", "Maus hat gesponnen", "Sonne im Auge", "Controller-Drift"] },
          { title: "Beste → schlechteste Gaming-Plattform", items: ["PC", "PlayStation", "Xbox", "Switch", "Handy"] },
          { title: "Toxischste → chilligste Community", items: ["League of Legends", "Counter-Strike", "Overwatch", "Dark Souls", "Stardew Valley"] },
          { title: "Bester → schlechtester Gaming-Snack", items: ["Tiefkühlpizza", "Chips", "Energy Drink", "Schokoriegel", "Kalte Pommes von gestern"] },
          { title: "Größter → kleinster Flex beim Zocken", items: ["1v5-Clutch", "Ranked Top 500", "Seltener Skin", "Speedrun-Rekord", "Teurer Gaming-Stuhl"] },
          // (Minecraft has its own category now — see the ⛏️ pool.)
          // ── Overwatch ──
          { title: "Meist gehasste → am wenigsten gehasste Held:in", items: ["Widowmaker", "Mei", "Sombra", "Hanzo", "Genji"] },
          { title: "Nervigste → harmloseste Ult zum Gegnertreffen", items: ["Genji Blade", "Junkrat Tire", "Pharah Barrage", "Reaper Death Blossom", "Mei Blizzard"] },
          { title: "Bester → schlechtester Support", items: ["Ana", "Kiriko", "Mercy", "Lúcio", "Moira"] },
          { title: "Dankbarste → undankbarste Rolle", items: ["DPS", "Flex-Support", "Main Tank", "Off-Tank", "Main Support"] },
          { title: "Größter → kleinster Tilt-Moment", items: ["Kein Heiler im Team", "Gegnerische Bastion im Choke", "Mercy rezzt im falschen Moment", "DPS, die nichts treffen", "Niemand geht aufs Ziel"] },
          // ── Counter-Strike ──
          { title: "Beste → schlechteste Map", items: ["Mirage", "Inferno", "Dust 2", "Nuke", "Vertigo"] },
          { title: "Stylischster → uncoolster Kill", items: ["AWP No-Scope", "Messer von hinten", "Deagle-Headshot", "AK-Spray", "P90 zugespammt"] },
          { title: "Größter → kleinster Tilt-Moment (CS)", items: ["Teamkill in der ersten Sekunde", "16:14 verloren", "Ace vom Teammate geklaut", "Eco-Runde verloren", "Granate ins eigene Team"] },
          { title: "Nervigster → harmlosester Mitspieler (CS)", items: ["Ragequit nach Pistol", "Schreit dauernd Rush B", "Pickt AWP und whiffed alles", "Mic-Spammer mit Musik", "Wirft Flashes ins eigene Team"] },
          { title: "Beste → schlechteste Eco-Waffe", items: ["Deagle", "Tec-9", "P250", "Dual Berettas", "Glock-Spray"] },
        ],
      },
      starwars: {
        label: "⭐ Star Wars",
        people: [
          { title: "Würde am ehesten → am wenigsten zur dunklen Seite wechseln" },
          { title: "Spürt am meisten → am wenigsten die Macht in sich" },
          { title: "Wäre der/die beste → schlechteste Jedi-Meister:in" },
          { title: "Würde am ehesten → am wenigsten Han Solo verraten" },
          { title: "Überlebt am längsten → am kürzesten auf Tatooine" },
          { title: "Klingt am meisten → am wenigsten nach Yoda" },
          { title: "Würde am ehesten → am wenigsten ein eigenes Lichtschwert bauen" },
          { title: "Wäre am ehesten → am wenigsten Anführer:in der Rebellion" },
        ],
        sets: [
          { title: "Bester → schlechtester Star-Wars-Film", items: ["Das Imperium schlägt zurück", "Eine neue Hoffnung", "Die Rückkehr der Jedi-Ritter", "Das Erwachen der Macht", "Angriff der Klonkrieger"] },
          { title: "Mächtigster → schwächster Jedi", items: ["Yoda", "Obi-Wan Kenobi", "Mace Windu", "Anakin Skywalker", "Luke Skywalker"] },
          { title: "Fieseste → harmloseste Sith-Figur", items: ["Darth Sidious", "Darth Vader", "Darth Maul", "Count Dooku", "Kylo Ren"] },
          { title: "Coolste → langweiligste Lichtschwertfarbe", items: ["Lila", "Blau", "Grün", "Rot", "Gelb"] },
          { title: "Bestes → schlechtestes Raumschiff", items: ["Millennium Falke", "X-Wing", "Sternzerstörer", "TIE-Jäger", "Todesstern"] },
          { title: "Loyalster → nutzlosester Droide", items: ["R2-D2", "C-3PO", "BB-8", "K-2SO", "IG-11"] },
          { title: "Bester → schlechtester Kopfgeldjäger", items: ["Boba Fett", "Din Djarin", "Jango Fett", "Cad Bane", "Dengar"] },
          { title: "Ikonischster → vergessenster Spruch", items: ["„Möge die Macht mit dir sein“", "„Ich bin dein Vater“", "„Tu es oder tu es nicht, es gibt kein Versuchen“", "„Es ist eine Falle!“", "„Ich hab da so ein ungutes Gefühl“"] },
          { title: "Schönster → trostlosester Planet", items: ["Naboo", "Coruscant", "Endor", "Tatooine", "Hoth"] },
          { title: "Beste → nervigste Alien-Spezies", items: ["Wookiees", "Ewoks", "Jawas", "Hutten", "Gungans"] },
          { title: "Epischster → lahmster Kampf", items: ["Duell der Schicksale", "Order 66", "Vader gegen Luke", "Rey gegen Kylo im Thronsaal", "Yoda gegen Dooku"] },
          { title: "Bester → schwächster Bösewicht-Tod", items: ["Darth Vader", "Darth Maul", "Palpatine", "Kylo Ren", "General Grievous"] },
        ],
      },
      minecraft: {
        label: "⛏️ Minecraft",
        people: [
          { title: "Überlebt am längsten → am kürzesten die erste Nacht" },
          { title: "Baut am schönsten → am hässlichsten" },
          { title: "Gräbt am ehesten → nie direkt nach unten" },
          { title: "Wird am ehesten → am wenigsten süchtig nach Minecraft" },
          { title: "Ist am ehesten → am wenigsten der Redstone-Nerd der Gruppe" },
          { title: "Fällt am ehesten → nie in die eigene Lava" },
          { title: "Verirrt sich am ehesten → nie im Nether" },
          { title: "Ragequittet am ehesten → nie, wenn die Base explodiert" },
        ],
        sets: [
          { title: "Gruseligster → harmlosester Mob", items: ["Der Warden", "Enderman", "Creeper", "Zombie", "Huhn"] },
          { title: "Wertvollstes → wertlosestes Erz", items: ["Netherite", "Diamant", "Smaragd", "Redstone", "Kohle"] },
          { title: "Beste → schlechteste Art zu sterben", items: ["Creeper von hinten", "In Lava gefallen", "Vom hohen Gerüst gefallen", "Im Wasser ertrunken", "Beim Bauen verhungert"] },
          { title: "Beeindruckendster → lahmster Bau", items: ["Riesiges Schloss", "Automatische Farm", "Pixel-Art", "Cobblestone-Turm in den Himmel", "Dirt House"] },
          { title: "Erste → letzte Priorität an Nacht 1", items: ["Holz farmen", "Werkzeug craften", "Essen suchen", "Haus bauen", "In ein Loch graben"] },
          { title: "Nützlichstes → nutzlosestes Werkzeug", items: ["Diamantspitzhacke", "Elytra", "Wassereimer", "Angel", "Schere"] },
          { title: "Bestes → schlechtestes Enchantment", items: ["Reparatur", "Schutz", "Effizienz", "Behutsamkeit", "Fluch der Bindung"] },
          { title: "Gefährlichster → sicherster Ort", items: ["Ancient City", "Nether-Festung", "Woodland Mansion", "Dunkle Höhle", "Dorf"] },
          { title: "Bester → schlechtester Trank", items: ["Regeneration", "Feuerresistenz", "Nachtsicht", "Sprungkraft", "Trank der Schwäche"] },
          { title: "Bestes → schlechtestes Biom zum Spawnen", items: ["Ebene", "Wald", "Mesa", "Sumpf", "Eiszapfen-Tundra"] },
          { title: "Nervigster → harmlosester Moment", items: ["Creeper sprengt den Bau", "Nachts kein Bett", "Im Nether verlaufen", "Werkzeug kaputt beim Minen", "Schaf frisst dein Gras"] },
        ],
      },
      leisure: {
        label: "🏖️ Freizeit & Urlaub",
        people: [
          { title: "Packt den größten → kleinsten Koffer" },
          { title: "Verpasst am ehesten → nie den Flug" },
          { title: "Wird am schnellsten braun → verbrennt zuerst" },
          { title: "Plant den Urlaub am meisten → am wenigsten" },
          { title: "Beschwert sich im Urlaub am meisten → am wenigsten" },
          { title: "Ist am ehesten → am wenigsten der/die spontane Abenteurer:in" },
          { title: "Verliert am ehesten → nie den Koffer" },
          { title: "Gibt im Urlaub am meisten → am wenigsten Geld aus" },
        ],
        sets: [
          { title: "Bester → schlechtester Urlaubstyp", items: ["Strandresort", "Backpacking", "Städtetrip", "Kreuzfahrt", "All-Inclusive-Pauschal"] },
          { title: "Entspannendste → stressigste Urlaubsaktivität", items: ["Am Pool liegen", "Stadtführung", "Wandern", "Souvenirshopping", "Flughafen-Transfer"] },
          { title: "Größtes → kleinstes Urlaubs-Drama", items: ["Koffer verloren", "Sonnenbrand an Tag 1", "Flug verpasst", "Magen-Darm im Hotel", "Handy-Akku leer"] },
          { title: "Bestes → schlechtestes Festival-Erlebnis", items: ["Headliner live sehen", "Crowdsurfen", "Dixie-Klo um 3 Uhr", "Matschschlacht", "Zelt säuft im Regen ab"] },
          { title: "Entspannendstes → anstrengendstes Hobby", items: ["Lesen", "Yoga", "Zocken", "Marathon-Training", "Möbel selbst aufbauen"] },
          { title: "Schönstes → nervigstes Reisesouvenir", items: ["Kühlschrankmagnet", "Sand in jeder Tasche", "Sonnenbrand-Streifen", "3000 Handyfotos", "Eine neue Sprach-App"] },
        ],
      },
      history: {
        label: "🏛️ Politik & Geschichte",
        people: [
          { title: "Würde am besten → am schlechtesten regieren" },
          { title: "Hat am meisten → am wenigsten Geld aufm Konto" },
          { title: "Überlebt am längsten → am kürzesten im Mittelalter" },
          { title: "Zettelt am ehesten → am wenigsten eine Revolution an" },
          { title: "Glaubt am ehesten → am wenigsten an Verschwörungstheorien" },
          { title: "Wird am ehesten → am wenigsten Millionär:in" },
          { title: "Wäre der/die beste → schlechteste Diktator:in" },
          { title: "Hat am meisten → am wenigsten Macht in dieser Gruppe" },
        ],
        sets: [
          { title: "Wichtigste → überschätzteste Erfindung der Geschichte", items: ["Buchdruck", "Internet", "Das Rad", "Penicillin", "Selfie-Stick"] },
          { title: "Beste → unnötigste Eigenschaft eines Politikers", items: ["Ehrlichkeit", "Rückgrat", "Charisma", "Gutes Gedächtnis", "Schöne Reden"] },
          { title: "Größter → kleinster Wendepunkt der Geschichte", items: ["Mauerfall", "Mondlandung", "Erfindung des Internets", "Französische Revolution", "Erfindung des Kaffees"] },
          { title: "Coolste → langweiligste Epoche zum Zeitreisen", items: ["Antikes Rom", "Wilder Westen", "Die 80er", "Mittelalter", "Steinzeit"] },
          { title: "Glaubwürdigste → absurdeste Verschwörungstheorie", items: ["Mondlandung gefakt", "Echsenmenschen", "Flache Erde", "Aliens in Area 51", "Vögel sind Drohnen"] },
          { title: "Mächtigste → machtloseste Position", items: ["US-Präsident", "Großkonzern-CEO", "Influencer", "Bürgermeister", "Klassensprecher"] },
        ],
      },
      football: {
        label: "⚽ Fußball (WM)",
        people: [
          { title: "Würde am ehesten → am wenigsten Nationalspieler:in" },
          { title: "Feiert ein Tor am wildesten → am nüchternsten" },
          { title: "Würde am ehesten → am wenigsten schwalben" },
          { title: "Verpasst am ehesten → nie ein WM-Spiel wegen Arbeit" },
          { title: "Schreit am lautesten → am leisesten beim Elfmeter" },
          { title: "Hat das meiste → wenigste Trikot-Sammlung" },
          { title: "Würde am ehesten → am wenigsten Schiri werden" },
          { title: "Kennt die meisten → wenigsten Nationalhymnen" },
        ],
        sets: [
          { title: "Beste → schlechteste Nationalmannschaft bei der WM", items: ["Brasilien", "Argentinien", "Frankreich", "Deutschland", "England"] },
          { title: "Größter → kleinster Superstar dieser WM", items: ["Mbappé", "Messi", "Haaland", "Bellingham", "Vinícius Júnior"] },
          { title: "Bester → schlechtester WM-Gastgeber", items: ["USA", "Mexiko", "Kanada", "Katar 2022", "Brasilien 2014"] },
          { title: "Wichtigste → unnötigste Regel im Fußball", items: ["Abseits", "VAR", "Gelbe Karte", "Einwurf", "Vorteilsregel"] },
          { title: "Bester → schlechtester Elfmeterschütze-Typ", items: ["Eiskalter Panenka", "Volle Wucht ins Eck", "Kurzer Anlauf, sicher", "Der Zitterer", "Der Rebound-Verschwender"] },
          { title: "Legendärster → vergessenster WM-Moment", items: ["Hand Gottes", "Zidane-Kopfstoß", "Deutschland 7:1 Brasilien", "Elfmeterkrimi im Finale", "Last-Minute-Ausgleich"] },
          { title: "Beste → schlechteste Fanausstattung", items: ["Trikot", "Schminke im Landesfarben", "Vuvuzela", "Riesenflagge", "Perücke in Landesfarben"] },
          { title: "Nervigster → harmlosester Stadion-Nachbar beim Public Viewing", items: ["Der Alles-Besserwisser", "Der Dauerschreier", "Der, der ständig aufs Klo muss", "Der Handy-Dauerglotzer", "Der, der jedes Foul überzieht"] },
          { title: "Bester → schlechtester Job auf dem Platz", items: ["Torschütze", "Torwart", "Kapitän", "Ersatzbank", "Linienrichter"] },
          { title: "Größtes → kleinstes WM-Drama", items: ["Frühes Ausscheiden der Favoriten", "Verletzter Superstar", "Elfmeterschießen im Finale", "Skandal um den Schiri", "Wetterchaos im Stadion"] },
          { title: "Bestes → schlechtestes Public-Viewing-Essen", items: ["Bratwurst vom Grill", "Chips & Dip", "Pizza-Lieferservice", "Popcorn", "Kalter Toast"] },
          { title: "Beeindruckendstes → überflüssigstes Tor-Jubel", items: ["Salto", "Trikot ausziehen", "Zur Bank sprinten", "Baby-Wiege-Geste", "Einfach nur laufen"] },
          { title: "Bester → schlechtester Kommentatoren-Spruch", items: ["'Das Runde muss ins Eckige'", "Übertriebenes Gebrüll beim Tor", "Statistik-Overkill", "Falscher Spielername", "Stille nach dem Tor"] },
          { title: "Größte → kleinste Fußball-Rivalität", items: ["Deutschland – Niederlande", "Argentinien – Brasilien", "England – Deutschland", "Frankreich – Italien", "Nachbardorf-Derby"] },
          { title: "Bester → schlechtester Ort, ein WM-Spiel zu schauen", items: ["Public Viewing mit der ganzen Stadt", "Kneipe mit Kumpels", "Zuhause auf dem Sofa", "Stadion live", "Handy heimlich bei der Arbeit"] },
        ],
      },
      nsfw: {
        label: "🔞 18+",
        people: [
          { title: "Steht am ehesten → am wenigsten auf BDSM" },
          { title: "Hatte die meisten → wenigsten Partner:innen" },
          { title: "Ist am lautesten → am leisesten im Bett" },
          { title: "Schickt am ehesten → nie Nudes" },
          { title: "Ist am kinkiesten → am vanilligsten" },
          { title: "Hatte an den meisten → wenigsten Orten Sex" },
          { title: "Redet am dreckigsten → am unschuldigsten" },
          { title: "Würde am ehesten → am wenigsten einen Dreier machen" },
          { title: "Hat den wildesten → zahmsten Suchverlauf" },
          { title: "Übernimmt am ehesten → am wenigsten die Kontrolle im Bett" },
          { title: "Würde am ehesten → am wenigsten mit einem/einer Ex nochmal" },
          { title: "Hat die längste → kürzeste Dürre hinter sich" },
          { title: "Erwischt man am ehesten → nie beim Fremdgehen" },
          { title: "Würde am ehesten → am wenigsten Sex an einem öffentlichen Ort haben" },
          { title: "Hat das größte → kleinste Geheimnis in diesem Raum" },
          { title: "Würde am ehesten → am wenigsten mit jemandem hier was anfangen" },
          { title: "Hat den seltsamsten → normalsten Kink" },
          { title: "Bekommt am ehesten → am seltensten ein zweites Date" },
          { title: "Ist am ehesten → am wenigsten schon mal erwischt worden" },
          { title: "Ghostet am ehesten → antwortet immer" },
          { title: "Würde am ehesten → am wenigsten für Geld strippen" },
          { title: "Hat die meiste → wenigste Erfahrung, die niemand ahnt" },
          { title: "Würde am ehesten → am wenigsten eine offene Beziehung führen" },
        ],
        sets: [
          // ── Soft entry ──
          { title: "Größter → verzeihlichster Ick", items: ["Schlechter Küsser", "Schreibt viel zu viel", "Wohnt noch bei den Eltern", "Null Ehrgeiz", "Quatscht im Kino"] },
          { title: "Bester → schlechtester Ort zum Rummachen", items: ["Ein echtes Bett (langweilig)", "Die Rückbank", "Ein Festivalzelt", "Bei den Eltern", "Im Büro"] },
          { title: "Größte → kleinste Red Flag", items: ["Schreibt noch dem Ex", "Hat keine Freunde", "Hasst Tiere", "Gibt mies Trinkgeld", "Liebt Comic Sans"] },
          { title: "Attraktivste → unwichtigste Eigenschaft", items: ["Selbstbewusstsein", "Geld", "Versauter Humor", "Sixpack", "Antwortet wirklich auf Nachrichten"] },
          { title: "Größter → kleinster Dealbreaker im Bett", items: ["Egoistisch", "Keine Mühe", "Hört nicht auf zu reden", "Lässt die Socken an", "Schläft danach sofort ein"] },
          { title: "Am meisten → am wenigsten überbewertet", items: ["Nacktbilder verschicken", "Sex unter der Dusche", "Knutschflecke", "Sexting", "Kuscheln am Morgen danach"] },
          // ── Härtere Sachen ──
          { title: "Heißeste → harmloseste Kink", items: ["Würgen", "Gefesselt werden", "Spanking", "Dirty Talk", "Augenbinde"] },
          { title: "Größtes → kleinstes Tabu, das dich trotzdem anmacht", items: ["Beim Sex beobachtet werden", "Ein Dreier", "Sex in der Öffentlichkeit", "Festgebunden werden", "Rollenspiel mit Kostüm"] },
          { title: "Am meisten → am wenigsten überbewertete Sexstellung", items: ["Doggy", "Reverse Cowgirl", "69", "Missionar", "Im Stehen"] },
          { title: "Versautestes → harmlosestes Sextoy", items: ["Strap-on", "Handschellen", "Vibrator", "Augenbinde", "Federpeitsche"] },
          { title: "Würde ich am ehesten → niemals ausprobieren", items: ["Ein Dreier", "Ein Sextape drehen", "Swingerparty", "BDSM-Dungeon", "Sex am FKK-Strand"] },
          { title: "Heißeste → unschuldigste Stelle zum Beißen", items: ["Innenschenkel", "Hals", "Nacken", "Ohrläppchen", "Bauch"] },
          { title: "Größter → kleinster Turn-on im Bett", items: ["Wird dominant", "Stöhnt deinen Namen", "Kratzt den Rücken auf", "Beißt in die Lippe", "Flüstert dreckig ins Ohr"] },
          { title: "Schmutzigster → harmlosester Ort, an dem du es getrieben hast", items: ["Auf der Arbeit", "Im Auto am Straßenrand", "Festival-Klo", "Im Hausflur", "Im Bett von Freunden"] },
          { title: "Bestes → schlimmstes Geräusch beim Sex", items: ["Lautes Stöhnen", "Deinen Namen stöhnen", "Dreckig reden", "Plötzliche Stille", "Aus Versehen lachen"] },
          { title: "Macht beim Sexting am meisten → am wenigsten an", items: ["Nacktbild ohne Vorwarnung", "Detaillierte Beschreibung", "Versaute Sprachnachricht", "Einfach 'komm vorbei'", "Emoji-Andeutungen"] },
          { title: "Heißester → langweiligster Dreier-Aufbau", items: ["Zwei Frauen", "Zwei Männer", "Paar plus eine:r", "Zwei Fremde aus der Bar", "Mit guten Freunden"] },
          { title: "Größte → harmloseste Bett-Sünde", items: ["An jemand anderen denken", "Den Namen verwechseln", "Mittendrin aufhören", "Heimlich filmen wollen", "Danach sofort einschlafen"] },
        ],
      },
      date: {
        label: "🌹 Date",
        sets: [
          { title: "Am heißesten → am harmlosesten", items: ["Hand am Hals", "Haare gepackt", "Gegen die Wand gedrückt", "Festgehalten", "Nägel auf dem Rücken"] },
          { title: "Würd ich heute Abend am ehesten → am wenigsten machen", items: ["Knutschen", "In den Nacken küssen", "Die Kontrolle abgeben", "Den ersten Schritt machen", "Es beim Reden lassen"] },
          { title: "So knistert's am meisten → am wenigsten", items: ["Erster Kuss", "Hand auf dem Oberschenkel", "Was ins Ohr flüstern", "Dieser eine Blick", "Wie zufällig berühren"] },
          { title: "Beim ersten Mal guck ich zuerst → zuletzt auf …", items: ["Augen", "Lächeln", "Stimme", "Hände", "Wie er/sie riecht"] },
          { title: "Macht mich am meisten → am wenigsten an", items: ["Wer die Führung übernimmt", "Dreckig ins Ohr geflüstert", "Langsam ausgezogen werden", "Festgehalten werden", "Geneckt werden"] },
          { title: "So soll der Abend am liebsten → am wenigsten enden", items: ["Bei dir", "Bei mir", "Langer Kuss an der Tür", "Noch ein Drink", "Im Taxi schon übereinander her"] },
          { title: "Bester erster Move → schlechtester", items: ["Hand auf den Rücken", "Haare hinters Ohr", "Am Handgelenk ranziehen", "Einfach küssen", "Erst fragen"] },
          { title: "Größter Turn-on → kleinster", items: ["Selbstbewusstsein", "Stimme", "Humor", "Geruch", "Aussehen"] },
          { title: "Heißester Ort → harmlosester", items: ["Im Auto", "In der Dusche", "Auf dem Küchentisch", "Im Hotel", "Im eigenen Bett"] },
          { title: "Am schwersten zu widerstehen → am leichtesten", items: ["Nacken küssen", "Ins Ohr flüstern", "Hand am Oberschenkel", "Langer Blick", "Kompliment"] },
          { title: "Wichtigster Teil einer Nacht → unwichtigster", items: ["Das Vorspiel", "Das Küssen", "Der Sex selbst", "Danach reden", "Zusammen einschlafen"] },
          { title: "Größte Red Flag im Bett → kleinste", items: ["Fragt nie, was du willst", "Handy in Reichweite", "Redet über den Ex", "Macht keinen Ton", "Steht sofort auf"] },
          { title: "Am heißesten am Morgen danach → am wenigsten", items: ["Sie oder er ist noch da", "Frühstück", "Nochmal", "Eine Nachricht später", "Direkt gehen"] },
          { title: "Beste Nachricht um 23 Uhr → schlechteste", items: ["Bist du noch wach?", "Ich denk grad an dich", "Komm vorbei", "Wie war dein Tag?", "Hey"] },
          { title: "Am meisten unterschätzt → am wenigsten", items: ["Küssen im Stehen", "Händchen halten", "Blickkontakt", "Zusammen duschen", "Nackt einschlafen"] },
          { title: "Bringt am meisten Spannung → am wenigsten", items: ["Warten müssen", "Etwas Verbotenes", "Ein Geheimnis", "Leute im Nebenzimmer", "Zeitdruck"] },
          { title: "Am schwersten zuzugeben → am leichtesten", items: ["Ein Kink", "Eine Fantasie", "Eine Unsicherheit", "Eine Zahl", "Ein Ex"] },
          { title: "Am heißesten gesagt → am wenigsten", items: ["Dein Name", "Nicht aufhören", "Sieh mich an", "Bitte", "Nichts"] },
          { title: "Bestes Date-Ende → schlechtestes", items: ["Kuss an der Tür", "Mit reinkommen", "Noch ein Drink", "Umarmung", "Handschlag"] },
          { title: "Bleibt am längsten in Erinnerung → am kürzesten", items: ["Der erste Kuss", "Die erste Nacht", "Das erste Lachen", "Der erste Streit", "Das erste Übernachten"] },
        ],
      },
    },

    en: {
      general: {
        label: "🎲 General",
        people: [
          { title: "Most → least likely to get famous" },
          { title: "Survives longest → shortest in the wild" },
          { title: "Most → least likely to end up in jail" },
          { title: "Has the fullest → emptiest fridge" },
          { title: "Most → least likely to survive the zombie apocalypse" },
          { title: "Most → least likely to secretly be a genius" },
          { title: "Most → least likely to show up late" },
          { title: "Most → least likely to sacrifice a finger for €1M" },
        ],
        sets: [
          { title: "Best → worst superpower", items: ["Invisibility", "Flying", "Time travel", "Reading minds", "Teleportation"] },
          { title: "Best → worst pizza topping", items: ["Pineapple", "Pepperoni", "Mushroom", "Extra cheese", "Anchovies"] },
          { title: "Most → least essential app", items: ["WhatsApp", "Instagram", "TikTok", "Google Maps", "Spotify"] },
          { title: "Dream → nightmare holiday", items: ["Beach resort", "City trip", "Camping", "Cruise", "Skiing"] },
          { title: "Best → worst way to spend a Sunday", items: ["Hungover in bed", "Big brunch", "A long hike", "Gaming all day", "Family visit"] },
          { title: "Most → least useful school subject", items: ["Maths", "PE", "History", "Art", "Religion"] },
          { title: "Best → worst fast food", items: ["McDonald's", "Burger King", "KFC", "Subway", "The kebab shop round the corner"] },
          { title: "Most → least important invention", items: ["The internet", "The washing machine", "The smartphone", "The microwave", "The selfie stick"] },
          { title: "Best → worst streaming service", items: ["Netflix", "Disney+", "Amazon Prime", "YouTube Premium", "DAZN"] },
          { title: "Most → least annoying flatmate type", items: ["The dish-stacker", "The constantly loud one", "The freeloader", "The cleaning freak", "The ghost (never home)"] },
          { title: "Best → worst pet", items: ["Dog", "Cat", "Hamster", "Snake", "Tarantula"] },
          { title: "Coolest → least cool job", items: ["Pilot", "YouTuber", "Doctor", "Tax advisor", "Politician"] },
          { title: "Most → least important phone feature", items: ["Battery life", "Camera", "Storage", "Screen size", "The colour"] },
          { title: "Best → worst day of the week", items: ["Friday", "Saturday", "Sunday", "Wednesday", "Monday"] },
          { title: "Best → worst season", items: ["Summer", "Spring", "Autumn", "Winter", "The wet week in between"] },
          { title: "Smartest → dumbest excuse for being late", items: ["Traffic jam", "Didn't hear the alarm", "Train got cancelled", "The dog was sick", "Lost track of time"] },
          { title: "Most useful → most overrated life skill", items: ["Managing money", "Cooking", "Small talk", "Driving", "Nice handwriting"] },
          { title: "Best → worst snack", items: ["Chocolate bar", "Crisps", "An apple", "Trail mix", "Cold coffee"] },
          { title: "Most impressive → lamest flex", items: ["Own flat at 22", "Expensive car", "Loads of followers", "A six-pack", "Drinking fancy water"] },
          { title: "Best → worst first-date topic", items: ["Travel", "Favourite music", "Family", "Politics", "The ex"] },
          { title: "Most → least important value in a friendship", items: ["Honesty", "Loyalty", "Humour", "Punctuality", "Same taste in music"] },
        ],
      },
      party: {
        label: "🎉 Party",
        people: [
          { title: "First → last to throw up" },
          { title: "Can handle the most → least booze" },
          { title: "Dances the wildest → stiffest" },
          { title: "Most → least likely to drunk-text the ex" },
          { title: "First → last to get kicked out" },
          { title: "First → last to pass out" },
          { title: "Most → least likely to start a fight" },
          { title: "Most → least likely to be last on the dance floor" },
        ],
        sets: [
          { title: "Most → least acceptable drunk behaviour", items: ["Crying in the toilets", "Texting your ex", "Starting beef", "Passing out", "Yapping"] },
          { title: "Most → least classy drink", items: ["Champagne", "Craft beer", "Tequila shots", "Boxed wine", "Jägerbombs"] },
          { title: "Biggest → smallest party foul", items: ["Throwing up indoors", "Breaking stuff", "Spilling a drink", "Leaving early", "Skipping songs"] },
          { title: "Best → worst hangover cure", items: ["Greasy food", "Hair of the dog", "Sleeping till noon", "Water & ibuprofen", "Gym"] },
          { title: "Most → least likely to get you kicked out", items: ["Starting a fight", "Skinny dipping", "Dissing the host", "Peeing in the plant pot", "Passing out"] },
          { title: "Best → worst person to be stuck next to at a party", items: ["The mess", "The yapper", "The DJ", "The ex", "The boss"] },
          { title: "Best → worst pre-game drink", items: ["Aperol Spritz", "Road beer", "Vodka mixer", "Mulled wine", "Warm prosecco"] },
          { title: "Best → worst person to walk home with", items: ["The sober one with snacks", "The one who knows the night bus", "The taxi sponsor", "The one who pukes every 50 metres", "The one who insists on going on"] },
          { title: "Most legendary → most embarrassing dance-floor move", items: ["The moonwalk", "Air guitar", "Wild breakdance", "Twerking on the speaker", "Just falling over"] },
          { title: "Best → worst afterparty spot", items: ["A house party", "By the lake", "In the park", "The car park", "The petrol station"] },
          { title: "Biggest → smallest party hero", items: ["The DJ", "The one with the refills", "The host", "The one who knows the bouncer", "The cleanup crew"] },
          { title: "Best → worst shot", items: ["Tequila", "Jägermeister", "Sambuca", "Vodka", "Mystery shot"] },
          { title: "Biggest → smallest house-party drama", items: ["The cops show up", "Neighbours complain", "Someone throws up on the sofa", "The booze runs out", "Aux cord war"] },
          { title: "Best → worst reason to buy a round", items: ["A birthday", "A promotion", "Surviving a breakup", "Just because", "Out of guilt"] },
          { title: "Coolest → most cringe party trick", items: ["Opening a beer with a lighter", "A card trick", "Beatboxing", "Ventriloquism", "Jokes nobody gets"] },
          { title: "Best → worst excuse to leave early", items: ["Early start tomorrow", "The babysitter's waiting", "Gotta walk the dog", "Just done", "Just ghosting"] },
          { title: "Biggest → smallest hazard at a house party", items: ["The stairs", "The pool", "The barbecue", "The white couch", "The dodgy speaker"] },
          { title: "Best → worst beer-pong teammate", items: ["The sniper", "The pick-me girl", "The trash-talker", "The shaky one", "The already-plastered one"] },
        ],
      },
      videogames: {
        label: "🎮 Video Games",
        people: [
          { title: "Most → least likely to rage-quit" },
          { title: "The best → worst gamer" },
          { title: "Spams the mic the most → least" },
          { title: "Most → least likely to blame the team" },
          { title: "Games the longest → shortest in one sitting" },
          { title: "Spends the most → least on skins" },
          { title: "Camps the most → pushes the most" },
          { title: "Most → least likely to throw the controller" },
        ],
        sets: [
          // ── General ──
          { title: "Most → least annoying gamer type", items: ["The rage-quitter", "The mic spammer", "The smurf", "The try-hard", "The AFK farmer"] },
          { title: "Best → worst excuse after a loss", items: ["Lag", "The team's fault", "My mouse glitched", "Sun in my eyes", "Controller drift"] },
          { title: "Best → worst gaming platform", items: ["PC", "PlayStation", "Xbox", "Switch", "Phone"] },
          { title: "Most toxic → most chill community", items: ["League of Legends", "Counter-Strike", "Overwatch", "Dark Souls", "Stardew Valley"] },
          { title: "Best → worst gaming snack", items: ["Frozen pizza", "Crisps", "Energy drink", "Chocolate bar", "Yesterday's cold fries"] },
          { title: "Biggest → smallest gaming flex", items: ["1v5 clutch", "Ranked top 500", "A rare skin", "Speedrun record", "Expensive gaming chair"] },
          // (Minecraft has its own category now — see the ⛏️ pool.)
          // ── Overwatch ──
          { title: "Most → least hated hero", items: ["Widowmaker", "Mei", "Sombra", "Hanzo", "Genji"] },
          { title: "Most → least annoying ult to get hit by", items: ["Genji Blade", "Junkrat Tire", "Pharah Barrage", "Reaper Death Blossom", "Mei Blizzard"] },
          { title: "Best → worst support", items: ["Ana", "Kiriko", "Mercy", "Lúcio", "Moira"] },
          { title: "Most → least rewarding role", items: ["DPS", "Flex support", "Main tank", "Off-tank", "Main support"] },
          { title: "Biggest → smallest tilt moment", items: ["No healer on the team", "Enemy Bastion in the choke", "Mercy rezzes at the worst time", "DPS who hit nothing", "Nobody goes on the objective"] },
          // ── Counter-Strike ──
          { title: "Best → worst map", items: ["Mirage", "Inferno", "Dust 2", "Nuke", "Vertigo"] },
          { title: "Most → least stylish kill", items: ["AWP no-scope", "Knife from behind", "Deagle headshot", "AK spray", "P90 spam"] },
          { title: "Biggest → smallest tilt moment (CS)", items: ["Teamkill in the first second", "Lost 16:14", "Ace stolen by a teammate", "Lost the eco round", "Grenade into your own team"] },
          { title: "Most → least annoying teammate (CS)", items: ["Rage-quits after pistol", "Constantly yells Rush B", "Picks AWP and whiffs everything", "Mic spammer with music", "Throws flashes into your own team"] },
          { title: "Best → worst eco weapon", items: ["Deagle", "Tec-9", "P250", "Dual Berettas", "Glock spray"] },
        ],
      },
      starwars: {
        label: "⭐ Star Wars",
        people: [
          { title: "Most → least likely to turn to the dark side" },
          { title: "Feels the Force the strongest → weakest" },
          { title: "Would be the best → worst Jedi Master" },
          { title: "Most → least likely to betray Han Solo" },
          { title: "Survives longest → shortest on Tatooine" },
          { title: "Sounds most → least like Yoda" },
          { title: "Most → least likely to build their own lightsaber" },
          { title: "Would make the best → worst Rebel leader" },
        ],
        sets: [
          { title: "Best → worst Star Wars film", items: ["The Empire Strikes Back", "A New Hope", "Return of the Jedi", "The Force Awakens", "Attack of the Clones"] },
          { title: "Most → least powerful Jedi", items: ["Yoda", "Obi-Wan Kenobi", "Mace Windu", "Anakin Skywalker", "Luke Skywalker"] },
          { title: "Most → least evil Sith", items: ["Darth Sidious", "Darth Vader", "Darth Maul", "Count Dooku", "Kylo Ren"] },
          { title: "Coolest → most boring lightsaber colour", items: ["Purple", "Blue", "Green", "Red", "Yellow"] },
          { title: "Best → worst ship", items: ["Millennium Falcon", "X-Wing", "Star Destroyer", "TIE Fighter", "Death Star"] },
          { title: "Most → least loyal droid", items: ["R2-D2", "C-3PO", "BB-8", "K-2SO", "IG-11"] },
          { title: "Best → worst bounty hunter", items: ["Boba Fett", "Din Djarin", "Jango Fett", "Cad Bane", "Dengar"] },
          { title: "Most → least iconic line", items: ["“May the Force be with you”", "“I am your father”", "“Do or do not, there is no try”", "“It's a trap!”", "“I have a bad feeling about this”"] },
          { title: "Most beautiful → most desolate planet", items: ["Naboo", "Coruscant", "Endor", "Tatooine", "Hoth"] },
          { title: "Best → most annoying alien species", items: ["Wookiees", "Ewoks", "Jawas", "Hutts", "Gungans"] },
          { title: "Most epic → lamest fight", items: ["Duel of the Fates", "Order 66", "Vader vs Luke", "Rey vs Kylo in the throne room", "Yoda vs Dooku"] },
          { title: "Best → weakest villain death", items: ["Darth Vader", "Darth Maul", "Palpatine", "Kylo Ren", "General Grievous"] },
        ],
      },
      minecraft: {
        label: "⛏️ Minecraft",
        people: [
          { title: "Survives the first night the longest → shortest" },
          { title: "Builds the prettiest → ugliest" },
          { title: "Most → least likely to dig straight down" },
          { title: "Most → least likely to get addicted to Minecraft" },
          { title: "Most → least likely to be the group's redstone nerd" },
          { title: "Most → least likely to fall into their own lava" },
          { title: "Most → least likely to get lost in the Nether" },
          { title: "Most → least likely to rage-quit when the base blows up" },
        ],
        sets: [
          { title: "Scariest → most harmless mob", items: ["The Warden", "Enderman", "Creeper", "Zombie", "Chicken"] },
          { title: "Most → least valuable ore", items: ["Netherite", "Diamond", "Emerald", "Redstone", "Coal"] },
          { title: "Best → worst way to die", items: ["Creeper from behind", "Fell into lava", "Fell off the scaffolding", "Drowned", "Starved while building"] },
          { title: "Most impressive → lamest build", items: ["Huge castle", "Automatic farm", "Pixel art", "Cobblestone tower to the sky", "Dirt house"] },
          { title: "First → last priority on night 1", items: ["Farm wood", "Craft tools", "Find food", "Build a house", "Dig a hole"] },
          { title: "Most → least useful tool", items: ["Diamond pickaxe", "Elytra", "Water bucket", "Fishing rod", "Shears"] },
          { title: "Best → worst enchantment", items: ["Mending", "Protection", "Efficiency", "Silk Touch", "Curse of Binding"] },
          { title: "Most dangerous → safest place", items: ["Ancient City", "Nether fortress", "Woodland Mansion", "Dark cave", "Village"] },
          { title: "Best → worst potion", items: ["Regeneration", "Fire Resistance", "Night Vision", "Jump Boost", "Potion of Weakness"] },
          { title: "Best → worst biome to spawn in", items: ["Plains", "Forest", "Badlands", "Swamp", "Icy tundra"] },
          { title: "Most → least annoying moment", items: ["Creeper blows up your build", "No bed at night", "Lost in the Nether", "Tool breaks mid-mine", "A sheep eats your grass"] },
        ],
      },
      leisure: {
        label: "🏖️ Leisure & Travel",
        people: [
          { title: "Packs the biggest → smallest suitcase" },
          { title: "Most → least likely to miss the flight" },
          { title: "Tans the fastest → burns first" },
          { title: "Plans the holiday the most → least" },
          { title: "Complains the most → least on holiday" },
          { title: "Most → least likely to be the spontaneous adventurer" },
          { title: "Most → least likely to lose their luggage" },
          { title: "Spends the most → least on holiday" },
        ],
        sets: [
          { title: "Best → worst holiday type", items: ["Beach resort", "Backpacking", "City trip", "Cruise", "All-inclusive package"] },
          { title: "Most relaxing → most stressful holiday activity", items: ["Lying by the pool", "Guided city tour", "Hiking", "Souvenir shopping", "Airport transfer"] },
          { title: "Biggest → smallest holiday disaster", items: ["Lost luggage", "Day-1 sunburn", "Missed flight", "Food poisoning at the hotel", "Dead phone battery"] },
          { title: "Best → worst festival moment", items: ["Seeing the headliner live", "Crowd surfing", "Portaloo at 3am", "Mud fight", "Tent flooding in the rain"] },
          { title: "Most relaxing → most exhausting hobby", items: ["Reading", "Yoga", "Gaming", "Marathon training", "Building flat-pack furniture"] },
          { title: "Best → most annoying travel souvenir", items: ["Fridge magnet", "Sand in every bag", "Sunburn lines", "3000 phone photos", "A new language app"] },
        ],
      },
      history: {
        label: "🏛️ Politics & History",
        people: [
          { title: "Would rule the best → worst" },
          { title: "Has the most → least money in the bank" },
          { title: "Survives longest → shortest in the Middle Ages" },
          { title: "Most → least likely to start a revolution" },
          { title: "Most → least likely to believe conspiracy theories" },
          { title: "Most → least likely to become a millionaire" },
          { title: "Would be the best → worst dictator" },
          { title: "Has the most → least power in this group" },
        ],
        sets: [
          { title: "Most important → most overrated invention in history", items: ["The printing press", "The internet", "The wheel", "Penicillin", "The selfie stick"] },
          { title: "Best → most pointless trait in a politician", items: ["Honesty", "A spine", "Charisma", "A good memory", "Pretty speeches"] },
          { title: "Biggest → smallest turning point in history", items: ["Fall of the Berlin Wall", "Moon landing", "Invention of the internet", "French Revolution", "Invention of coffee"] },
          { title: "Coolest → most boring era to time-travel to", items: ["Ancient Rome", "Wild West", "The 80s", "The Middle Ages", "The Stone Age"] },
          { title: "Most believable → most absurd conspiracy theory", items: ["Faked moon landing", "Lizard people", "Flat earth", "Aliens in Area 51", "Birds are drones"] },
          { title: "Most → least powerful position", items: ["US President", "Megacorp CEO", "Influencer", "Mayor", "Class president"] },
        ],
      },
      football: {
        label: "⚽ Football (World Cup)",
        people: [
          { title: "Most → least likely to go pro" },
          { title: "Celebrates a goal the wildest → most reserved" },
          { title: "Most → least likely to flop for a penalty" },
          { title: "Most → least likely to miss a World Cup match for work" },
          { title: "Screams the loudest → quietest at a penalty" },
          { title: "Owns the biggest → smallest jersey collection" },
          { title: "Most → least likely to become a referee" },
          { title: "Knows the most → fewest national anthems" },
        ],
        sets: [
          { title: "Best → worst national team at the World Cup", items: ["Brazil", "Argentina", "France", "Germany", "England"] },
          { title: "Biggest → smallest superstar of this World Cup", items: ["Mbappé", "Messi", "Haaland", "Bellingham", "Vinícius Júnior"] },
          { title: "Best → worst World Cup host", items: ["USA", "Mexico", "Canada", "Qatar 2022", "Brazil 2014"] },
          { title: "Most → least necessary rule in football", items: ["Offside", "VAR", "Yellow card", "Throw-in", "Advantage rule"] },
          { title: "Best → worst penalty-taker type", items: ["Ice-cold Panenka", "Blast it in the corner", "Short run-up, sure thing", "The shaky one", "The rebound-waster"] },
          { title: "Most legendary → most forgotten World Cup moment", items: ["The Hand of God", "Zidane's headbutt", "Germany 7:1 Brazil", "Penalty shootout in the final", "Last-minute equaliser"] },
          { title: "Best → worst fan gear", items: ["Jersey", "Face paint in national colours", "Vuvuzela", "Giant flag", "Wig in national colours"] },
          { title: "Most → least annoying person next to you at a public viewing", items: ["The know-it-all", "The nonstop screamer", "The one who's always in the bathroom", "The phone zombie", "The one who oversells every foul"] },
          { title: "Best → worst job on the pitch", items: ["Goalscorer", "Goalkeeper", "Captain", "Substitute bench", "Linesman"] },
          { title: "Biggest → smallest World Cup drama", items: ["A favourite gets knocked out early", "A superstar gets injured", "Penalty shootout in the final", "A referee scandal", "Weather chaos in the stadium"] },
          { title: "Best → worst public-viewing food", items: ["Grilled sausage", "Chips & dip", "Delivery pizza", "Popcorn", "Cold toast"] },
          { title: "Most impressive → most pointless goal celebration", items: ["A backflip", "Ripping off the jersey", "Sprinting to the bench", "The baby-rocking gesture", "Just running"] },
          { title: "Best → worst commentator moment", items: ["The classic goaaal scream", "Over-the-top roaring at a goal", "Stat overkill", "Getting the player's name wrong", "Dead silence after a goal"] },
          { title: "Biggest → smallest football rivalry", items: ["Germany – Netherlands", "Argentina – Brazil", "England – Germany", "France – Italy", "The next-town derby"] },
          { title: "Best → worst place to watch a World Cup match", items: ["A public viewing with the whole city", "A pub with mates", "Home on the sofa", "Live in the stadium", "Sneaking a look at work"] },
        ],
      },
      nsfw: {
        label: "🔞 18+",
        people: [
          { title: "Most → least into BDSM" },
          { title: "Has had the most → fewest partners" },
          { title: "Loudest → quietest in bed" },
          { title: "Most → least likely to send nudes" },
          { title: "The kinkiest → most vanilla" },
          { title: "Has had sex in the most → fewest places" },
          { title: "Talks the dirtiest → most innocent" },
          { title: "Most → least likely to have a threesome" },
          { title: "Has the wildest → tamest search history" },
          { title: "Most → least likely to take control in bed" },
          { title: "Most → least likely to go back to an ex" },
          { title: "Has had the longest → shortest dry spell" },
          { title: "Most → least likely to get caught cheating" },
          { title: "Most → least likely to have sex in public" },
          { title: "Is keeping the biggest → smallest secret in this room" },
          { title: "Most → least likely to hook up with someone here" },
          { title: "Has the strangest → most normal kink" },
          { title: "Most → least likely to get a second date" },
          { title: "Most → least likely to have already been walked in on" },
          { title: "Most likely to ghost → always replies" },
          { title: "Most → least likely to strip for money" },
          { title: "Has the most → least experience nobody suspects" },
          { title: "Most → least likely to go for an open relationship" },
        ],
        sets: [
          // ── Soft entry ──
          { title: "Biggest → most forgivable ick", items: ["Bad kisser", "Texts way too much", "Still lives with parents", "Zero ambition", "Talks during the film"] },
          { title: "Best → worst place to hook up", items: ["A real bed (boring)", "The back seat", "A festival tent", "Parents' house", "The office"] },
          { title: "Biggest → smallest red flag", items: ["Still texts their ex", "Has no friends", "Hates animals", "Terrible tipper", "Loves Comic Sans"] },
          { title: "Most → least attractive trait", items: ["Confidence", "Money", "A filthy sense of humour", "Abs", "Actually replies to texts"] },
          { title: "Biggest → smallest dealbreaker in bed", items: ["Selfish", "No effort", "Won't stop talking", "Keeps socks on", "Falls asleep after"] },
          { title: "Most → least overrated", items: ["Sending nudes", "Shower sex", "Hickeys", "Sexting", "Morning after cuddles"] },
          // ── Harder stuff ──
          { title: "Hottest → most harmless kink", items: ["Choking", "Being tied up", "Spanking", "Dirty talk", "Blindfold"] },
          { title: "Biggest → smallest taboo that still turns you on", items: ["Being watched during sex", "A threesome", "Sex in public", "Being restrained", "Roleplay with a costume"] },
          { title: "Most → least overrated sex position", items: ["Doggy", "Reverse cowgirl", "69", "Missionary", "Standing up"] },
          { title: "Filthiest → most harmless sex toy", items: ["Strap-on", "Handcuffs", "Vibrator", "Blindfold", "Feather whip"] },
          { title: "Most → least likely to try", items: ["A threesome", "Filming a sextape", "Swingers' party", "BDSM dungeon", "Sex on a nude beach"] },
          { title: "Hottest → most innocent spot to bite", items: ["Inner thigh", "Throat", "Back of the neck", "Earlobe", "Stomach"] },
          { title: "Biggest → smallest turn-on in bed", items: ["Gets dominant", "Moans your name", "Scratches your back up", "Bites your lip", "Whispers something filthy"] },
          { title: "Filthiest → most harmless place you've done it", items: ["At work", "In a car on the roadside", "Festival toilet", "The stairwell", "In a friend's bed"] },
          { title: "Best → worst sound during sex", items: ["Loud moaning", "Moaning your name", "Talking dirty", "Sudden silence", "Accidental laughing"] },
          { title: "Turns you on most → least when sexting", items: ["A nude with no warning", "A detailed description", "A filthy voice note", "Just 'come over'", "Emoji hints"] },
          { title: "Hottest → most boring threesome setup", items: ["Two women", "Two men", "Couple plus one", "Two strangers from the bar", "With close friends"] },
          { title: "Biggest → most harmless sin in bed", items: ["Thinking of someone else", "Saying the wrong name", "Stopping halfway", "Wanting to film it secretly", "Falling asleep right after"] },
        ],
      },
      date: {
        label: "🌹 Date",
        sets: [
          { title: "Hottest → most innocent", items: ["Hand on your throat", "Hair grabbed", "Pushed against the wall", "Held down", "Nails down your back"] },
          { title: "Most → least likely I'd do tonight", items: ["Make out", "Kiss your neck", "Give up control", "Make the first move", "Keep it to talking"] },
          { title: "Makes it spark the most → least", items: ["First kiss", "Hand on the thigh", "Whisper in the ear", "That one look", "An 'accidental' touch"] },
          { title: "First time, I notice first → last …", items: ["Eyes", "Smile", "Voice", "Hands", "How they smell"] },
          { title: "Turns me on most → least", items: ["When they take the lead", "Filthy whispers", "Being slowly undressed", "Being held down", "Being teased"] },
          { title: "How I'd most → least want tonight to end", items: ["At yours", "At mine", "A long kiss at the door", "One more drink", "All over each other in the taxi"] },
          { title: "Best first move → worst", items: ["Hand on the back", "Hair behind the ear", "Pulled in by the wrist", "Just kiss them", "Ask first"] },
          { title: "Biggest turn-on → smallest", items: ["Confidence", "Voice", "Humour", "Smell", "Looks"] },
          { title: "Hottest place → most innocent", items: ["In the car", "In the shower", "On the kitchen table", "In a hotel", "In your own bed"] },
          { title: "Hardest to resist → easiest", items: ["A kiss on the neck", "A whisper in the ear", "A hand on the thigh", "A long look", "A compliment"] },
          { title: "Most important part of the night → least", items: ["The build-up", "The kissing", "The sex itself", "Talking after", "Falling asleep together"] },
          { title: "Biggest red flag in bed → smallest", items: ["Never asks what you want", "Phone within reach", "Brings up their ex", "Makes no sound at all", "Gets up straight after"] },
          { title: "Hottest morning after → least", items: ["They're still there", "Breakfast", "Round two", "A text later", "Leaving right away"] },
          { title: "Best 11pm text → worst", items: ["You still up?", "Thinking about you", "Come over", "How was your day?", "Hey"] },
          { title: "Most underrated → least", items: ["Kissing standing up", "Holding hands", "Eye contact", "Showering together", "Falling asleep naked"] },
          { title: "Builds the most tension → least", items: ["Having to wait", "Something forbidden", "A secret", "People in the next room", "A time limit"] },
          { title: "Hardest to admit → easiest", items: ["A kink", "A fantasy", "An insecurity", "A number", "An ex"] },
          { title: "Hottest thing to hear → least", items: ["Your name", "Don't stop", "Look at me", "Please", "Nothing at all"] },
          { title: "Best way a date ends → worst", items: ["A kiss at the door", "Coming inside", "One more drink", "A hug", "A handshake"] },
          { title: "Sticks with you longest → shortest", items: ["The first kiss", "The first night", "The first laugh", "The first argument", "The first sleepover"] },
        ],
      },
    },
    es: {
      general: {
        label: "🎲 General",
        people: [
          { title: "Más → menos probable que se haga famoso" },
          { title: "Sobrevive más → menos tiempo en la naturaleza" },
          { title: "Más → menos probable que acabe en la cárcel" },
          { title: "Tiene la nevera más llena → más vacía" },
          { title: "Más → menos probable que sobreviva al apocalipsis zombi" },
          { title: "Más → menos probable que sea un genio en secreto" },
          { title: "Más → menos probable que llegue tarde" },
          { title: "Más → menos probable que se corte un dedo por 1 M€" },
        ],
        sets: [
          { title: "Mejor → peor superpoder", items: ["Invisibilidad", "Volar", "Viajar en el tiempo", "Leer mentes", "Teletransporte"] },
          { title: "Mejor → peor ingrediente de pizza", items: ["Piña", "Pepperoni", "Champiñones", "Extra de queso", "Anchoas"] },
          { title: "App más → menos imprescindible", items: ["WhatsApp", "Instagram", "TikTok", "Google Maps", "Spotify"] },
          { title: "Vacaciones de ensueño → de pesadilla", items: ["Resort de playa", "Escapada urbana", "Camping", "Crucero", "Esquí"] },
          { title: "Mejor → peor forma de pasar un domingo", items: ["En la cama con resaca", "Un buen brunch", "Una ruta larga de senderismo", "Jugar a la consola todo el día", "Visita familiar"] },
          { title: "Asignatura más → menos útil", items: ["Mates", "Educación física", "Historia", "Plástica", "Religión"] },
          { title: "Mejor → peor comida rápida", items: ["McDonald's", "Burger King", "KFC", "Subway", "El kebab de la esquina"] },
          { title: "Invento más → menos importante", items: ["Internet", "La lavadora", "El smartphone", "El microondas", "El palo selfie"] },
          { title: "Mejor → peor plataforma de streaming", items: ["Netflix", "Disney+", "Amazon Prime", "YouTube Premium", "DAZN"] },
          { title: "Tipo de compañero de piso más → menos insoportable", items: ["El que acumula platos", "El que siempre hace ruido", "El gorrón", "El obseso de la limpieza", "El fantasma (nunca está)"] },
          { title: "Mejor → peor mascota", items: ["Perro", "Gato", "Hámster", "Serpiente", "Tarántula"] },
          { title: "Trabajo más → menos guay", items: ["Piloto", "YouTuber", "Médico", "Asesor fiscal", "Político"] },
          { title: "Función del móvil más → menos importante", items: ["Batería", "Cámara", "Almacenamiento", "Tamaño de pantalla", "El color"] },
          { title: "Mejor → peor día de la semana", items: ["Viernes", "Sábado", "Domingo", "Miércoles", "Lunes"] },
          { title: "Mejor → peor estación", items: ["Verano", "Primavera", "Otoño", "Invierno", "La semana lluviosa de en medio"] },
          { title: "Excusa más lista → más tonta por llegar tarde", items: ["Atasco", "No oí el despertador", "Cancelaron el tren", "El perro estaba malo", "Se me fue el santo al cielo"] },
          { title: "Habilidad vital más útil → más sobrevalorada", items: ["Gestionar el dinero", "Cocinar", "Dar conversación", "Conducir", "Tener buena letra"] },
          { title: "Mejor → peor picoteo", items: ["Chocolatina", "Patatas fritas", "Una manzana", "Frutos secos", "Café frío"] },
          { title: "Fardada más impresionante → más cutre", items: ["Piso propio a los 22", "Coche caro", "Un montón de seguidores", "Tableta de chocolate", "Beber agua pija"] },
          { title: "Mejor → peor tema para una primera cita", items: ["Viajes", "Música favorita", "Familia", "Política", "El ex"] },
          { title: "Valor más → menos importante en una amistad", items: ["Sinceridad", "Lealtad", "Humor", "Puntualidad", "Mismo gusto musical"] },
        ],
      },
      party: {
        label: "🎉 Fiesta",
        people: [
          { title: "Vomita el primero → el último" },
          { title: "Aguanta más → menos alcohol" },
          { title: "Baila de forma más salvaje → más rígida" },
          { title: "Más → menos probable que le escriba borracho al ex" },
          { title: "El primero → el último al que echan" },
          { title: "El primero → el último en caer redondo" },
          { title: "Más → menos probable que empiece una pelea" },
          { title: "Más → menos probable que sea el último en la pista" },
        ],
        sets: [
          { title: "Comportamiento de borracho más → menos aceptable", items: ["Llorar en el baño", "Escribirle a tu ex", "Buscar bronca", "Caer redondo", "Hablar sin parar"] },
          { title: "Bebida más → menos elegante", items: ["Champán", "Cerveza artesana", "Chupitos de tequila", "Vino de tetrabrik", "Jägerbombs"] },
          { title: "Metedura de pata en una fiesta más → menos grave", items: ["Vomitar dentro de casa", "Romper cosas", "Derramar una copa", "Irse pronto", "Saltarse canciones"] },
          { title: "Mejor → peor cura para la resaca", items: ["Comida grasienta", "Una cerveza para la resaca", "Dormir hasta mediodía", "Agua e ibuprofeno", "Gimnasio"] },
          { title: "Lo que más → menos probablemente hace que te echen", items: ["Empezar una pelea", "Bañarse desnudo", "Criticar al anfitrión", "Mear en la maceta", "Caer redondo"] },
          { title: "Mejor → peor persona con la que quedarse atrapado en una fiesta", items: ["El que va fatal", "El que no calla", "El DJ", "El ex", "El jefe"] },
          { title: "Mejor → peor bebida para el precopeo", items: ["Aperol Spritz", "Cerveza para el camino", "Vodka con refresco", "Vino caliente", "Prosecco caliente"] },
          { title: "Mejor → peor persona para volver a casa", items: ["El sobrio con snacks", "El que se sabe el búho", "El que paga el taxi", "El que vomita cada 50 metros", "El que insiste en seguir"] },
          { title: "Movimiento en la pista más legendario → más vergonzoso", items: ["El moonwalk", "Guitarra imaginaria", "Breakdance salvaje", "Twerking encima del altavoz", "Simplemente caerse"] },
          { title: "Mejor → peor sitio para el after", items: ["Una fiesta en casa", "Junto al lago", "En el parque", "El parking", "La gasolinera"] },
          { title: "Héroe de la fiesta más → menos grande", items: ["El DJ", "El que rellena las copas", "El anfitrión", "El que conoce al portero", "El equipo de limpieza"] },
          { title: "Mejor → peor chupito", items: ["Tequila", "Jägermeister", "Sambuca", "Vodka", "Chupito misterioso"] },
          { title: "Drama de fiesta en casa más → menos grande", items: ["Aparece la policía", "Se quejan los vecinos", "Alguien vomita en el sofá", "Se acaba la bebida", "Guerra por el cable del altavoz"] },
          { title: "Mejor → peor motivo para pagar una ronda", items: ["Un cumpleaños", "Un ascenso", "Haber superado una ruptura", "Porque sí", "Por remordimiento"] },
          { title: "Truco de fiesta más guay → más cringe", items: ["Abrir una cerveza con un mechero", "Un truco de cartas", "Beatbox", "Ventriloquía", "Chistes que nadie pilla"] },
          { title: "Mejor → peor excusa para irse pronto", items: ["Mañana madrugo", "Me espera la canguro", "Tengo que sacar al perro", "Estoy muerto", "Irse a la francesa"] },
          { title: "Peligro más → menos grande en una fiesta en casa", items: ["Las escaleras", "La piscina", "La barbacoa", "El sofá blanco", "El altavoz cutre"] },
          { title: "Mejor → peor compañero de beer pong", items: ["El francotirador", "La pick-me", "El que pica a los rivales", "El del pulso tembloroso", "El que ya va pedo"] },
        ],
      },
      videogames: {
        label: "🎮 Videojuegos",
        people: [
          { title: "Más → menos probable que haga rage quit" },
          { title: "El mejor → peor gamer" },
          { title: "Spamea el micro más → menos" },
          { title: "Más → menos probable que culpe al equipo" },
          { title: "Juega más → menos rato del tirón" },
          { title: "Se gasta más → menos en skins" },
          { title: "Campea más → empuja más" },
          { title: "Más → menos probable que tire el mando" },
        ],
        sets: [
          // ── General ──
          { title: "Tipo de gamer más → menos insoportable", items: ["El que hace rage quit", "El que spamea el micro", "El smurf", "El tryhard", "El que farmea AFK"] },
          { title: "Mejor → peor excusa tras perder", items: ["Lag", "Culpa del equipo", "Se me buggeó el ratón", "Me daba el sol en los ojos", "Drift del mando"] },
          { title: "Mejor → peor plataforma para jugar", items: ["PC", "PlayStation", "Xbox", "Switch", "Móvil"] },
          { title: "Comunidad más tóxica → más tranquila", items: ["League of Legends", "Counter-Strike", "Overwatch", "Dark Souls", "Stardew Valley"] },
          { title: "Mejor → peor snack para jugar", items: ["Pizza congelada", "Patatas fritas", "Bebida energética", "Chocolatina", "Patatas frías de ayer"] },
          { title: "Fardada gamer más → menos grande", items: ["Clutch 1 contra 5", "Top 500 en ranked", "Una skin rara", "Récord de speedrun", "Silla gaming cara"] },
          // (Minecraft has its own category now — see the ⛏️ pool.)
          // ── Overwatch ──
          { title: "Héroe más → menos odiado", items: ["Widowmaker", "Mei", "Sombra", "Hanzo", "Genji"] },
          { title: "Definitiva más → menos molesta de recibir", items: ["Hoja del dragón de Genji", "Neumático de Junkrat", "Ráfaga de cohetes de Pharah", "Flor de la muerte de Reaper", "Ventisca de Mei"] },
          { title: "Mejor → peor apoyo", items: ["Ana", "Kiriko", "Mercy", "Lúcio", "Moira"] },
          { title: "Rol más → menos gratificante", items: ["DPS", "Apoyo flex", "Tanque principal", "Tanque secundario", "Apoyo principal"] },
          { title: "Momento de tilt más → menos grande", items: ["Ningún healer en el equipo", "Bastion enemigo en el embudo", "Mercy resucita en el peor momento", "DPS que no acierta nada", "Nadie va al objetivo"] },
          // ── Counter-Strike ──
          { title: "Mejor → peor mapa", items: ["Mirage", "Inferno", "Dust 2", "Nuke", "Vertigo"] },
          { title: "Kill más → menos estilosa", items: ["No-scope con la AWP", "Cuchillo por la espalda", "Headshot con la Deagle", "Spray con la AK", "Spam con la P90"] },
          { title: "Momento de tilt más → menos grande (CS)", items: ["Teamkill en el primer segundo", "Perder 16:14", "Un compañero te roba el ace", "Perder la ronda eco", "Granada a tu propio equipo"] },
          { title: "Compañero más → menos insoportable (CS)", items: ["Hace rage quit tras la ronda de pistolas", "Grita Rush B todo el rato", "Coge la AWP y falla todo", "Spamea el micro con música", "Tira flashes a su propio equipo"] },
          { title: "Mejor → peor arma de eco", items: ["Deagle", "Tec-9", "P250", "Berettas dobles", "Spray de Glock"] },
        ],
      },
      starwars: {
        label: "⭐ Star Wars",
        people: [
          { title: "Más → menos probable que se pase al lado oscuro" },
          { title: "Siente la Fuerza con más → menos intensidad" },
          { title: "Sería el mejor → peor Maestro Jedi" },
          { title: "Más → menos probable que traicione a Han Solo" },
          { title: "Sobrevive más → menos tiempo en Tatooine" },
          { title: "Suena más → menos como Yoda" },
          { title: "Más → menos probable que se construya su propio sable láser" },
          { title: "Sería el mejor → peor líder rebelde" },
        ],
        sets: [
          { title: "Mejor → peor película de Star Wars", items: ["El Imperio contraataca", "Una nueva esperanza", "El retorno del Jedi", "El despertar de la Fuerza", "El ataque de los clones"] },
          { title: "Jedi más → menos poderoso", items: ["Yoda", "Obi-Wan Kenobi", "Mace Windu", "Anakin Skywalker", "Luke Skywalker"] },
          { title: "Sith más → menos malvado", items: ["Darth Sidious", "Darth Vader", "Darth Maul", "Conde Dooku", "Kylo Ren"] },
          { title: "Color de sable láser más guay → más aburrido", items: ["Morado", "Azul", "Verde", "Rojo", "Amarillo"] },
          { title: "Mejor → peor nave", items: ["Halcón Milenario", "Ala-X", "Destructor Estelar", "Caza TIE", "Estrella de la Muerte"] },
          { title: "Droide más → menos leal", items: ["R2-D2", "C-3PO", "BB-8", "K-2SO", "IG-11"] },
          { title: "Mejor → peor cazarrecompensas", items: ["Boba Fett", "Din Djarin", "Jango Fett", "Cad Bane", "Dengar"] },
          { title: "Frase más → menos icónica", items: ["«Que la Fuerza te acompañe»", "«Yo soy tu padre»", "«Hazlo o no lo hagas, pero no lo intentes»", "«¡Es una trampa!»", "«Tengo un mal presentimiento»"] },
          { title: "Planeta más bonito → más desolado", items: ["Naboo", "Coruscant", "Endor", "Tatooine", "Hoth"] },
          { title: "Especie alienígena mejor → más insoportable", items: ["Wookiees", "Ewoks", "Jawas", "Hutts", "Gungans"] },
          { title: "Combate más épico → más cutre", items: ["El Duelo de los Destinos", "La Orden 66", "Vader contra Luke", "Rey contra Kylo en la sala del trono", "Yoda contra Dooku"] },
          { title: "Muerte de villano mejor → más floja", items: ["Darth Vader", "Darth Maul", "Palpatine", "Kylo Ren", "General Grievous"] },
        ],
      },
      minecraft: {
        label: "⛏️ Minecraft",
        people: [
          { title: "Sobrevive la primera noche más → menos tiempo" },
          { title: "Construye lo más bonito → más feo" },
          { title: "Más → menos probable que cave en vertical hacia abajo" },
          { title: "Más → menos probable que se vicie a Minecraft" },
          { title: "Más → menos probable que sea el friki de la redstone del grupo" },
          { title: "Más → menos probable que se caiga en su propia lava" },
          { title: "Más → menos probable que se pierda en el Nether" },
          { title: "Más → menos probable que haga rage quit cuando le vuelan la base" },
        ],
        sets: [
          { title: "Mob más aterrador → más inofensivo", items: ["El Warden", "Enderman", "Creeper", "Zombi", "Gallina"] },
          { title: "Mineral más → menos valioso", items: ["Netherita", "Diamante", "Esmeralda", "Redstone", "Carbón"] },
          { title: "Mejor → peor forma de morir", items: ["Creeper por la espalda", "Caerse a la lava", "Caerse del andamio", "Ahogarse", "Morir de hambre mientras construyes"] },
          { title: "Construcción más impresionante → más cutre", items: ["Castillo enorme", "Granja automática", "Pixel art", "Torre de roca hasta el cielo", "Casa de tierra"] },
          { title: "Primera → última prioridad la primera noche", items: ["Talar madera", "Fabricar herramientas", "Buscar comida", "Construir una casa", "Cavar un agujero"] },
          { title: "Herramienta más → menos útil", items: ["Pico de diamante", "Élitros", "Cubo de agua", "Caña de pescar", "Tijeras"] },
          { title: "Mejor → peor encantamiento", items: ["Reparación", "Protección", "Eficiencia", "Toque de seda", "Maldición de ligamiento"] },
          { title: "Lugar más peligroso → más seguro", items: ["Ciudad antigua", "Fortaleza del Nether", "Mansión del bosque", "Cueva oscura", "Aldea"] },
          { title: "Mejor → peor poción", items: ["Regeneración", "Resistencia al fuego", "Visión nocturna", "Salto mejorado", "Poción de debilidad"] },
          { title: "Mejor → peor bioma para aparecer", items: ["Llanura", "Bosque", "Tierras baldías", "Pantano", "Tundra helada"] },
          { title: "Momento más → menos molesto", items: ["Un creeper te vuela la construcción", "Sin cama por la noche", "Perdido en el Nether", "Se rompe la herramienta en plena mina", "Una oveja se come tu césped"] },
        ],
      },
      leisure: {
        label: "🏖️ Ocio y viajes",
        people: [
          { title: "Hace la maleta más grande → más pequeña" },
          { title: "Más → menos probable que pierda el vuelo" },
          { title: "Se pone moreno el primero → se quema el primero" },
          { title: "Planifica las vacaciones más → menos" },
          { title: "Se queja más → menos en vacaciones" },
          { title: "Más → menos probable que sea el aventurero espontáneo" },
          { title: "Más → menos probable que pierda el equipaje" },
          { title: "Gasta más → menos en vacaciones" },
        ],
        sets: [
          { title: "Mejor → peor tipo de vacaciones", items: ["Resort de playa", "Mochilero", "Escapada urbana", "Crucero", "Paquete todo incluido"] },
          { title: "Actividad de vacaciones más relajante → más estresante", items: ["Tumbarse en la piscina", "Visita guiada por la ciudad", "Senderismo", "Comprar souvenirs", "Traslado al aeropuerto"] },
          { title: "Desastre de vacaciones más → menos grande", items: ["Equipaje perdido", "Quemadura solar el primer día", "Vuelo perdido", "Intoxicación alimentaria en el hotel", "Móvil sin batería"] },
          { title: "Mejor → peor momento de festival", items: ["Ver al cabeza de cartel en directo", "Crowd surfing", "Baño químico a las 3 de la mañana", "Pelea en el barro", "Tienda inundada por la lluvia"] },
          { title: "Hobby más relajante → más agotador", items: ["Leer", "Yoga", "Videojuegos", "Entrenar para un maratón", "Montar muebles de IKEA"] },
          { title: "Recuerdo de viaje mejor → más molesto", items: ["Imán para la nevera", "Arena en todas las bolsas", "Marcas del bronceado", "3000 fotos en el móvil", "Una nueva app de idiomas"] },
        ],
      },
      history: {
        label: "🏛️ Política e historia",
        people: [
          { title: "Gobernaría mejor → peor" },
          { title: "Tiene más → menos dinero en el banco" },
          { title: "Sobrevive más → menos tiempo en la Edad Media" },
          { title: "Más → menos probable que empiece una revolución" },
          { title: "Más → menos probable que se crea teorías de la conspiración" },
          { title: "Más → menos probable que se haga millonario" },
          { title: "Sería el mejor → peor dictador" },
          { title: "Tiene más → menos poder en este grupo" },
        ],
        sets: [
          { title: "Invento más importante → más sobrevalorado de la historia", items: ["La imprenta", "Internet", "La rueda", "La penicilina", "El palo selfie"] },
          { title: "Cualidad más valiosa → más inútil en un político", items: ["Sinceridad", "Tener principios", "Carisma", "Buena memoria", "Discursos bonitos"] },
          { title: "Punto de inflexión de la historia más → menos grande", items: ["La caída del Muro de Berlín", "La llegada a la Luna", "La invención de internet", "La Revolución francesa", "La invención del café"] },
          { title: "Época más guay → más aburrida para viajar en el tiempo", items: ["La antigua Roma", "El Lejano Oeste", "Los 80", "La Edad Media", "La Edad de Piedra"] },
          { title: "Teoría de la conspiración más creíble → más absurda", items: ["La llegada a la Luna fue falsa", "Hombres lagarto", "Tierra plana", "Alienígenas en el Área 51", "Los pájaros son drones"] },
          { title: "Cargo más → menos poderoso", items: ["Presidente de EE. UU.", "CEO de una multinacional", "Influencer", "Alcalde", "Delegado de clase"] },
        ],
      },
      football: {
        label: "⚽ Fútbol (Mundial)",
        people: [
          { title: "Más → menos probable que se haga profesional" },
          { title: "Celebra un gol de forma más salvaje → más comedida" },
          { title: "Más → menos probable que se tire para forzar un penalti" },
          { title: "Más → menos probable que se pierda un partido del Mundial por trabajo" },
          { title: "Grita más → menos fuerte en un penalti" },
          { title: "Tiene la colección de camisetas más grande → más pequeña" },
          { title: "Más → menos probable que se haga árbitro" },
          { title: "Se sabe más → menos himnos nacionales" },
        ],
        sets: [
          { title: "Mejor → peor selección en el Mundial", items: ["Brasil", "Argentina", "Francia", "Alemania", "Inglaterra"] },
          { title: "Superestrella más → menos grande de este Mundial", items: ["Mbappé", "Messi", "Haaland", "Bellingham", "Vinícius Júnior"] },
          { title: "Mejor → peor anfitrión del Mundial", items: ["EE. UU.", "México", "Canadá", "Catar 2022", "Brasil 2014"] },
          { title: "Regla del fútbol más → menos necesaria", items: ["Fuera de juego", "VAR", "Tarjeta amarilla", "Saque de banda", "Ley de la ventaja"] },
          { title: "Mejor → peor tipo de lanzador de penaltis", items: ["Panenka a sangre fría", "Reventarla a la escuadra", "Carrerilla corta, a lo seguro", "El del pulso tembloroso", "El que falla hasta el rechace"] },
          { title: "Momento mundialista más legendario → más olvidado", items: ["La Mano de Dios", "El cabezazo de Zidane", "Alemania 7:1 Brasil", "Tanda de penaltis en la final", "Empate en el último minuto"] },
          { title: "Mejor → peor accesorio de hincha", items: ["Camiseta", "Cara pintada con los colores nacionales", "Vuvuzela", "Bandera gigante", "Peluca con los colores nacionales"] },
          { title: "Persona más → menos insoportable a tu lado en una pantalla gigante", items: ["El sabelotodo", "El que no para de gritar", "El que siempre está en el baño", "El zombi del móvil", "El que exagera cada falta"] },
          { title: "Mejor → peor puesto en el campo", items: ["Goleador", "Portero", "Capitán", "Banquillo", "Juez de línea"] },
          { title: "Drama mundialista más → menos grande", items: ["Un favorito cae eliminado pronto", "Se lesiona una superestrella", "Tanda de penaltis en la final", "Un escándalo arbitral", "Caos meteorológico en el estadio"] },
          { title: "Mejor → peor comida para ver el partido en grupo", items: ["Salchicha a la parrilla", "Patatas con salsa", "Pizza a domicilio", "Palomitas", "Tostada fría"] },
          { title: "Celebración de gol más impresionante → más absurda", items: ["Un mortal hacia atrás", "Quitarse la camiseta", "Correr al banquillo", "El gesto de acunar al bebé", "Simplemente correr"] },
          { title: "Mejor → peor momento de narrador", items: ["El clásico gooool", "Rugidos exagerados en un gol", "Sobredosis de estadísticas", "Equivocarse con el nombre del jugador", "Silencio absoluto tras un gol"] },
          { title: "Rivalidad futbolística más → menos grande", items: ["Alemania – Países Bajos", "Argentina – Brasil", "Inglaterra – Alemania", "Francia – Italia", "El derbi con el pueblo de al lado"] },
          { title: "Mejor → peor sitio para ver un partido del Mundial", items: ["Una pantalla gigante con toda la ciudad", "Un bar con los amigos", "En casa en el sofá", "En directo en el estadio", "A escondidas en el trabajo"] },
        ],
      },
      nsfw: {
        label: "🔞 18+",
        people: [
          { title: "Le va el BDSM más → menos" },
          { title: "Ha tenido más → menos parejas" },
          { title: "Más → menos ruidoso en la cama" },
          { title: "Más → menos probable que mande nudes" },
          { title: "El más pervertido → más vainilla" },
          { title: "Lo ha hecho en más → menos sitios" },
          { title: "Habla de forma más guarra → más inocente" },
          { title: "Más → menos probable que haga un trío" },
          { title: "Tiene el historial de búsqueda más salvaje → más soso" },
          { title: "Más → menos probable que tome el control en la cama" },
          { title: "Más → menos probable que vuelva con un ex" },
          { title: "Ha tenido la sequía más larga → más corta" },
          { title: "Más → menos probable que le pillen poniendo los cuernos" },
          { title: "Más → menos probable que lo haga en público" },
          { title: "Guarda el secreto más grande → más pequeño de esta sala" },
          { title: "Más → menos probable que se líe con alguien de aquí" },
          { title: "Tiene el fetiche más raro → más normal" },
          { title: "Más → menos probable que consiga una segunda cita" },
          { title: "Más → menos probable que ya le hayan pillado en plena faena" },
          { title: "Más probable que haga ghosting → siempre contesta" },
          { title: "Más → menos probable que se desnude por dinero" },
          { title: "Tiene más → menos experiencia de la que nadie sospecha" },
          { title: "Más → menos probable que acepte una relación abierta" },
        ],
        sets: [
          // ── Soft entry ──
          { title: "Grima más grande → más perdonable", items: ["Besa mal", "Escribe demasiado", "Sigue viviendo con sus padres", "Cero ambición", "Habla durante la peli"] },
          { title: "Mejor → peor sitio para liarse", items: ["Una cama de verdad (aburrido)", "El asiento de atrás", "Una tienda de campaña en un festival", "La casa de sus padres", "La oficina"] },
          { title: "Bandera roja más → menos grande", items: ["Sigue escribiéndose con su ex", "No tiene amigos", "Odia a los animales", "No deja propina nunca", "Le encanta la Comic Sans"] },
          { title: "Rasgo más → menos atractivo", items: ["Seguridad en uno mismo", "Dinero", "Un humor guarro", "Abdominales", "Contesta de verdad a los mensajes"] },
          { title: "Lo que más → menos te corta el rollo en la cama", items: ["Egoísta", "No se esfuerza", "No para de hablar", "Se deja los calcetines puestos", "Se duerme justo después"] },
          { title: "Más → menos sobrevalorado", items: ["Mandar nudes", "Sexo en la ducha", "Chupetones", "Sexting", "Mimos a la mañana siguiente"] },
          // ── Harder stuff ──
          { title: "Fetiche más caliente → más inofensivo", items: ["Que te agarren del cuello", "Que te aten", "Azotes", "Hablar sucio", "Venda en los ojos"] },
          { title: "Tabú más → menos grande que aun así te pone", items: ["Que te miren durante el sexo", "Un trío", "Sexo en público", "Que te inmovilicen", "Juego de rol con disfraz"] },
          { title: "Postura sexual más → menos sobrevalorada", items: ["Perrito", "Vaquera invertida", "69", "Misionero", "De pie"] },
          { title: "Juguete sexual más guarro → más inofensivo", items: ["Arnés", "Esposas", "Vibrador", "Venda en los ojos", "Plumero"] },
          { title: "Lo que más → menos probaría", items: ["Un trío", "Grabar un vídeo porno casero", "Fiesta de intercambio de parejas", "Mazmorra BDSM", "Sexo en una playa nudista"] },
          { title: "Sitio más caliente → más inocente para morder", items: ["Cara interna del muslo", "Cuello", "Nuca", "Lóbulo de la oreja", "Barriga"] },
          { title: "Lo que más → menos te pone en la cama", items: ["Se pone dominante", "Gime tu nombre", "Te araña la espalda", "Te muerde el labio", "Te susurra algo guarro"] },
          { title: "Sitio más guarro → más inofensivo donde lo has hecho", items: ["En el trabajo", "En un coche en el arcén", "En el baño de un festival", "En la escalera", "En la cama de un amigo"] },
          { title: "Mejor → peor sonido durante el sexo", items: ["Gemidos fuertes", "Que gima tu nombre", "Hablar sucio", "Silencio repentino", "Risa sin querer"] },
          { title: "Te pone más → menos en el sexting", items: ["Un nude sin avisar", "Una descripción detallada", "Un audio guarro", "Solo un «vente»", "Pistas con emojis"] },
          { title: "Trío más caliente → más aburrido", items: ["Dos mujeres", "Dos hombres", "Pareja más uno", "Dos desconocidos del bar", "Con amigos íntimos"] },
          { title: "Pecado más grave → más inofensivo en la cama", items: ["Pensar en otra persona", "Decir el nombre equivocado", "Parar a medias", "Querer grabarlo en secreto", "Dormirse justo después"] },
        ],
      },
      date: {
        label: "🌹 Cita",
        sets: [
          { title: "Más caliente → más inocente", items: ["Mano en el cuello", "Que te agarren del pelo", "Que te empujen contra la pared", "Que te sujeten", "Uñas por la espalda"] },
          { title: "Lo que más → menos probablemente haría esta noche", items: ["Enrollarnos", "Besarte el cuello", "Ceder el control", "Dar el primer paso", "Quedarnos en hablar"] },
          { title: "Lo que más → menos chispa enciende", items: ["El primer beso", "Mano en el muslo", "Un susurro al oído", "Esa mirada", "Un roce «sin querer»"] },
          { title: "La primera vez, en lo que me fijo primero → último …", items: ["Los ojos", "La sonrisa", "La voz", "Las manos", "Cómo huele"] },
          { title: "Me pone más → menos", items: ["Cuando toma la iniciativa", "Susurros guarros", "Que me desnuden despacio", "Que me sujeten", "Que me provoquen"] },
          { title: "Cómo me gustaría más → menos que acabara esta noche", items: ["En tu casa", "En mi casa", "Un beso largo en la puerta", "Una copa más", "Comiéndonos en el taxi"] },
          { title: "Mejor primer paso → peor", items: ["Mano en la espalda", "Apartarle el pelo detrás de la oreja", "Atraerle tirando de la muñeca", "Besarle sin más", "Preguntar primero"] },
          { title: "Lo que más → menos te pone", items: ["Seguridad en uno mismo", "La voz", "Humor", "El olor", "El físico"] },
          { title: "Sitio más caliente → más inocente", items: ["En el coche", "En la ducha", "En la mesa de la cocina", "En un hotel", "En tu propia cama"] },
          { title: "Más difícil → más fácil de resistir", items: ["Un beso en el cuello", "Un susurro al oído", "Una mano en el muslo", "Una mirada larga", "Un cumplido"] },
          { title: "Parte más → menos importante de la noche", items: ["La previa", "Los besos", "El sexo en sí", "Hablar después", "Dormirse juntos"] },
          { title: "Bandera roja en la cama más → menos grande", items: ["Nunca pregunta qué quieres", "El móvil al alcance de la mano", "Saca el tema de su ex", "No hace ningún ruido", "Se levanta justo después"] },
          { title: "Mañana siguiente más → menos excitante", items: ["Sigue ahí", "Desayuno", "Segundo asalto", "Un mensaje más tarde", "Irse enseguida"] },
          { title: "Mejor → peor mensaje a las 23:00", items: ["¿Sigues despierto?", "Pensando en ti", "Vente", "¿Qué tal el día?", "Hola"] },
          { title: "Más → menos infravalorado", items: ["Besarse de pie", "Ir de la mano", "Contacto visual", "Ducharse juntos", "Dormirse desnudos"] },
          { title: "Lo que más → menos tensión genera", items: ["Tener que esperar", "Algo prohibido", "Un secreto", "Gente en la habitación de al lado", "Un límite de tiempo"] },
          { title: "Lo más difícil → más fácil de admitir", items: ["Un fetiche", "Una fantasía", "Una inseguridad", "Una cifra", "Un ex"] },
          { title: "Lo más excitante → menos de oír", items: ["Tu nombre", "No pares", "Mírame", "Por favor", "Nada en absoluto"] },
          { title: "Mejor → peor final de una cita", items: ["Un beso en la puerta", "Entrar a casa", "Una copa más", "Un abrazo", "Un apretón de manos"] },
          { title: "Se te queda grabado más → menos tiempo", items: ["El primer beso", "La primera noche", "La primera risa", "La primera discusión", "La primera noche juntos"] },
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.RankItSets = RANKIT;
})(window);
