// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/rankit.js — content for Rank It (NSFW, adults only)
 *
 * EDIT ME. Pure content. Bilingual: the export is a { de, en } bundle and the
 * game reads the current language's subtree via Spielecke.L(...). Each language
 * holds the same pool keys; within a pool, each SET is one round: a `title`
 * stating the axis you rank along (best → worst, biggest → smallest, …) and an
 * `items` list (aim for 5) that everyone privately puts in order. Drift from the
 * group's consensus and you lose. Item count is flexible — the game adapts.
 *
 * Each pool ALSO carries a `people` list: axis titles (title only, no items) used
 * by Rank It's "Mitspieler" mode, where the items are the current roster instead
 * of static content. The chosen category just decides the flavour of the axis
 * (Party → "Kotzt am ehesten → am spätesten", 18+ → "Steht am ehesten → am
 * wenigsten auf BDSM", …). Same `people` phrasing rules as `sets` titles.
 *
 * The title MUST contain a "→": the game splits on it to label the top/bottom
 * poles of the rail. Keep the DE and EN pool keys
 * (general/party/videogames/minecraft/leisure/history/football/nsfw) in sync so the
 * category chips line up in both languages.
 */
(function (global) {
  "use strict";

  var RANKIT = {
    de: {
      general: {
        label: "🎲 Allgemein",
        people: [
          { title: "Wird am ehesten → am spätesten berühmt" },
          { title: "Überlebt am längsten → am kürzesten in der Wildnis" },
          { title: "Käme am ehesten → am wenigsten ins Gefängnis" },
          { title: "Hat den vollsten → leersten Kühlschrank" },
          { title: "Überlebt am ehesten → am wenigsten die Zombie-Apokalypse" },
          { title: "Ist am ehesten → am wenigsten heimlich ein Genie" },
          { title: "Kommt am ehesten → am seltensten zu spät" },
          { title: "Würde am ehesten → am wenigsten für 1 Mio. € einen Finger opfern" },
        ],
        sets: [
          { title: "Beste → schlechteste Superkraft", items: ["Unsichtbarkeit", "Fliegen", "Zeitreise", "Gedankenlesen", "Teleportation"] },
          { title: "Bester → schlechtester Pizzabelag", items: ["Ananas", "Salami", "Pilze", "Extra Käse", "Sardellen"] },
          { title: "Wichtigste → unnötigste App", items: ["WhatsApp", "Instagram", "TikTok", "Google Maps", "Spotify"] },
          { title: "Traum- → Albtraum-Urlaub", items: ["Strandresort", "Städtetrip", "Camping", "Kreuzfahrt", "Skifahren"] },
          { title: "Bester → schlechtester Sonntag", items: ["Verkatert im Bett", "Großer Brunch", "Lange Wanderung", "Den ganzen Tag zocken", "Familienbesuch"] },
          { title: "Nützlichstes → nutzlosestes Schulfach", items: ["Mathe", "Sport", "Geschichte", "Kunst", "Religion"] },
          { title: "Bestes → schlechtestes Fast Food", items: ["McDonald's", "Burger King", "KFC", "Subway", "Der Döner um die Ecke"] },
          { title: "Wichtigste → unnötigste Erfindung", items: ["Internet", "Waschmaschine", "Smartphone", "Mikrowelle", "Selfie-Stick"] },
          { title: "Bester → schlechtester Streamingdienst", items: ["Netflix", "Disney+", "Amazon Prime", "YouTube Premium", "DAZN"] },
          { title: "Nervigster → harmlosester Mitbewohner-Typ", items: ["Der Geschirr-Stapler", "Der Dauerlaute", "Der Schmarotzer", "Der Putz-Nazi", "Der Geist (nie da)"] },
          { title: "Bestes → schlechtestes Haustier", items: ["Hund", "Katze", "Hamster", "Schlange", "Vogelspinne"] },
          { title: "Coolster → uncoolster Beruf", items: ["Pilot", "YouTuber", "Arzt", "Steuerberater", "Politiker"] },
          { title: "Wichtigstes → unwichtigstes Handy-Feature", items: ["Akkulaufzeit", "Kamera", "Speicherplatz", "Bildschirmgröße", "Die Farbe"] },
          { title: "Bester → schlechtester Wochentag", items: ["Freitag", "Samstag", "Sonntag", "Mittwoch", "Montag"] },
          { title: "Beste → schlechteste Jahreszeit", items: ["Sommer", "Frühling", "Herbst", "Winter", "Die nasse Woche dazwischen"] },
          { title: "Genialste → dümmste Ausrede fürs Zuspätkommen", items: ["Stau", "Wecker nicht gehört", "Bahn ausgefallen", "Dem Hund ging's schlecht", "Zeit vergessen"] },
          { title: "Nützlichste → überbewertetste Lebenskompetenz", items: ["Mit Geld umgehen", "Kochen", "Smalltalk", "Autofahren", "Schöne Handschrift"] },
          { title: "Bester → schlechtester Snack", items: ["Schokoriegel", "Chips", "Apfel", "Studentenfutter", "Kalter Kaffee"] },
          { title: "Beeindruckendster → lahmster Flex", items: ["Eigene Wohnung mit 22", "Teures Auto", "Viele Follower", "Sixpack", "Teures Wasser trinken"] },
          { title: "Bestes → schlechtestes Date-Gesprächsthema", items: ["Reisen", "Lieblingsmusik", "Familie", "Politik", "Der/die Ex"] },
          { title: "Wichtigster → unwichtigster Wert in einer Freundschaft", items: ["Ehrlichkeit", "Loyalität", "Humor", "Pünktlichkeit", "Gleicher Musikgeschmack"] },
        ],
      },
      party: {
        label: "🎉 Party",
        people: [
          { title: "Kotzt am ehesten → am spätesten" },
          { title: "Verträgt am meisten → am wenigsten" },
          { title: "Tanzt am wildesten → am steifsten" },
          { title: "Schreibt besoffen am ehesten → nie dem Ex" },
          { title: "Wird als Erstes → als Letztes rausgeworfen" },
          { title: "Pennt am ehesten → am spätesten weg" },
          { title: "Zettelt am ehesten → am wenigsten eine Schlägerei an" },
          { title: "Ist am ehesten → am wenigsten der/die Letzte auf der Tanzfläche" },
        ],
        sets: [
          { title: "Akzeptabelstes → schlimmstes Besoffen-Verhalten", items: ["Aufm Klo heulen", "Dem Ex schreiben", "Streit anzetteln", "Wegpennen", "Yappen"] },
          { title: "Stilvollster → peinlichster Drink", items: ["Champagner", "Craft Beer", "Tequila-Shots", "Tetrapack-Wein", "Jägerbombs"] },
          { title: "Größtes → kleinstes Party-Foul", items: ["Drinnen kotzen", "Alles kaputt machen", "Drink verschütten", "Früh abhauen", "Songs skippen"] },
          { title: "Bestes → schlechtestes Kater-Mittel", items: ["Fettiges Essen", "Konterbier", "Bis mittags pennen", "Wasser & Aspirin", "Gym"] },
          { title: "Fliegst am ehesten → am wenigsten raus", items: ["Schlägerei anzetteln", "Nacktbaden", "Den Gastgeber dissen", "In die Pflanze pinkeln", "Wegpennen"] },
          { title: "Bester → schlimmster, neben dem du festhängst", items: ["Der Vollsuff", "Der Yapper", "Der DJ", "Der Ex", "Der Chef"] },
          { title: "Bester → schlechtester Vorglüh-Drink", items: ["Aperol Spritz", "Wegbier", "Wodka-Mische", "Glühwein", "Lauwarmer Sekt"] },
          { title: "Bester → schlechtester Begleiter auf dem Heimweg", items: ["Der Nüchterne mit Snacks", "Der, der den Nachtbus kennt", "Der Taxi-Sponsor", "Der, der alle 50 Meter kotzen muss", "Der, der unbedingt noch weiterziehen will"] },
          { title: "Legendärste → peinlichste Tanzflächen-Aktion", items: ["Der Moonwalk", "Luftgitarre", "Wilder Breakdance", "An der Box twerken", "Einfach hinfallen"] },
          { title: "Beste → schlechteste Afterparty-Location", items: ["Hausi", "Am See", "Im Park", "Aufm Parkplatz", "An der Tanke"] },
          { title: "Größter → kleinster Partyheld", items: ["Der DJ", "Der mit dem Nachschub", "Der Gastgeber", "Der den Türsteher kennt", "Der Aufräumer"] },
          { title: "Bester → schlechtester Shot", items: ["Tequila", "Jägermeister", "Sambuca", "Wodka", "Mystery-Shot"] },
          { title: "Größtes → kleinstes WG-Party-Drama", items: ["Die Bullen kommen", "Nachbarn beschweren sich", "Jemand kotzt aufs Sofa", "Der Alk ist alle", "Aux-Kabel-Krieg"] },
          { title: "Bester → schlechtester Grund, eine Runde auszugeben", items: ["Geburtstag", "Beförderung", "Trennung überstanden", "Einfach so", "Aus schlechtem Gewissen"] },
          { title: "Coolster → cringigster Partytrick", items: ["Bier mitm Feuerzeug öffnen", "Kartentrick", "Beatboxen", "Bauchreden", "Witze, die keiner checkt"] },
          { title: "Beste → schlechteste Ausrede, früher zu gehen", items: ["Muss morgen früh raus", "Babysitter wartet", "Hund muss raus", "Bin einfach durch", "Einfach ghosten"] },
          { title: "Größte → kleinste Gefahr auf einer Hausparty", items: ["Die Treppe", "Der Pool", "Der Grill", "Die weiße Couch", "Der Wackelkontakt der Box"] },
          { title: "Bester → schlechtester Bier-Pong-Partner", items: ["Der Sniper", "Das Pick-me-Girl", "Der Trash-Talker", "Der Zittrige", "Der schon Dichte"] },
        ],
      },
      videogames: {
        label: "🎮 Videospiele",
        people: [
          { title: "Ragequittet am ehesten → nie" },
          { title: "Ist der/die beste → schlechteste Gamer:in" },
          { title: "Spammt am meisten → am wenigsten das Mic" },
          { title: "Schiebt die Schuld am ehesten → nie aufs Team" },
          { title: "Zockt am längsten → am kürzesten am Stück" },
          { title: "Gibt am meisten → am wenigsten Geld für Skins aus" },
          { title: "Campt am ehesten → pusht am ehesten" },
          { title: "Wirft am ehesten → nie den Controller" },
        ],
        sets: [
          // ── Allgemein ──
          { title: "Nervigster → harmlosester Gamer-Typ", items: ["Der Rage-Quitter", "Der Mic-Spammer", "Der Smurf", "Der Try-Hard", "Der AFK-Farmer"] },
          { title: "Beste → schlechteste Ausrede nach einer Niederlage", items: ["Lag", "Team war schuld", "Maus hat gesponnen", "Sonne im Auge", "Controller-Drift"] },
          { title: "Beste → schlechteste Gaming-Plattform", items: ["PC", "PlayStation", "Xbox", "Switch", "Handy"] },
          { title: "Toxischste → chilligste Community", items: ["League of Legends", "Counter-Strike", "Overwatch", "Dark Souls", "Stardew Valley"] },
          { title: "Bester → schlechtester Gaming-Snack", items: ["Tiefkühlpizza", "Chips", "Energy Drink", "Schokoriegel", "Kalte Pommes von gestern"] },
          { title: "Größter → kleinster Flex beim Zocken", items: ["1v5-Clutch", "Ranked Top 500", "Seltener Skin", "Speedrun-Rekord", "Teurer Gaming-Stuhl"] },
          // (Minecraft has its own category now — see the ⛏️ pool.)
          // ── Overwatch ──
          { title: "Meist gehasste → am wenigsten gehasste Held:in", items: ["Widowmaker", "Mei", "Sombra", "Hanzo", "Genji"] },
          { title: "Nervigste → harmloseste Ult zum Gegnertreffen", items: ["Genji Blade", "Junkrat Tire", "Pharah Barrage", "Reaper Death Blossom", "Mei Blizzard"] },
          { title: "Bester → schlechtester Support", items: ["Ana", "Kiriko", "Mercy", "Lúcio", "Moira"] },
          { title: "Dankbarste → undankbarste Rolle", items: ["DPS", "Flex-Support", "Main Tank", "Off-Tank", "Main Support"] },
          { title: "Größter → kleinster Tilt-Moment", items: ["Kein Heiler im Team", "Gegnerische Bastion im Choke", "Mercy rezzt im falschen Moment", "DPS, die nichts treffen", "Niemand geht aufs Ziel"] },
          // ── Counter-Strike ──
          { title: "Beste → schlechteste Map", items: ["Mirage", "Inferno", "Dust 2", "Nuke", "Vertigo"] },
          { title: "Stylischster → uncoolster Kill", items: ["AWP No-Scope", "Messer von hinten", "Deagle-Headshot", "AK-Spray", "P90 zugespammt"] },
          { title: "Größter → kleinster Tilt-Moment (CS)", items: ["Teamkill in der ersten Sekunde", "16:14 verloren", "Ace vom Teammate geklaut", "Eco-Runde verloren", "Granate ins eigene Team"] },
          { title: "Nervigster → harmlosester Mitspieler (CS)", items: ["Ragequit nach Pistol", "Schreit dauernd Rush B", "Pickt AWP und whiffed alles", "Mic-Spammer mit Musik", "Wirft Flashes ins eigene Team"] },
          { title: "Beste → schlechteste Eco-Waffe", items: ["Deagle", "Tec-9", "P250", "Dual Berettas", "Glock-Spray"] },
        ],
      },
      minecraft: {
        label: "⛏️ Minecraft",
        people: [
          { title: "Überlebt am längsten → am kürzesten die erste Nacht" },
          { title: "Baut am schönsten → am hässlichsten" },
          { title: "Gräbt am ehesten → nie direkt nach unten" },
          { title: "Wird am ehesten → am wenigsten süchtig nach Minecraft" },
          { title: "Ist am ehesten → am wenigsten der Redstone-Nerd der Gruppe" },
          { title: "Fällt am ehesten → nie in die eigene Lava" },
          { title: "Verirrt sich am ehesten → nie im Nether" },
          { title: "Ragequittet am ehesten → nie, wenn die Base explodiert" },
        ],
        sets: [
          { title: "Gruseligster → harmlosester Mob", items: ["Der Warden", "Enderman", "Creeper", "Zombie", "Huhn"] },
          { title: "Wertvollstes → wertlosestes Erz", items: ["Netherite", "Diamant", "Smaragd", "Redstone", "Kohle"] },
          { title: "Beste → schlechteste Art zu sterben", items: ["Creeper von hinten", "In Lava gefallen", "Vom hohen Gerüst gefallen", "Im Wasser ertrunken", "Beim Bauen verhungert"] },
          { title: "Beeindruckendster → lahmster Bau", items: ["Riesiges Schloss", "Automatische Farm", "Pixel-Art", "Cobblestone-Turm in den Himmel", "Dirt House"] },
          { title: "Erste → letzte Priorität an Nacht 1", items: ["Holz farmen", "Werkzeug craften", "Essen suchen", "Haus bauen", "In ein Loch graben"] },
          { title: "Nützlichstes → nutzlosestes Werkzeug", items: ["Diamantspitzhacke", "Elytra", "Wassereimer", "Angel", "Schere"] },
          { title: "Bestes → schlechtestes Enchantment", items: ["Reparatur", "Schutz", "Effizienz", "Behutsamkeit", "Fluch der Bindung"] },
          { title: "Gefährlichster → sicherster Ort", items: ["Ancient City", "Nether-Festung", "Woodland Mansion", "Dunkle Höhle", "Dorf"] },
          { title: "Bester → schlechtester Trank", items: ["Regeneration", "Feuerresistenz", "Nachtsicht", "Sprungkraft", "Trank der Schwäche"] },
          { title: "Bestes → schlechtestes Biom zum Spawnen", items: ["Ebene", "Wald", "Mesa", "Sumpf", "Eiszapfen-Tundra"] },
          { title: "Nervigster → harmlosester Moment", items: ["Creeper sprengt den Bau", "Nachts kein Bett", "Im Nether verlaufen", "Werkzeug kaputt beim Minen", "Schaf frisst dein Gras"] },
        ],
      },
      leisure: {
        label: "🏖️ Freizeit & Urlaub",
        people: [
          { title: "Packt den größten → kleinsten Koffer" },
          { title: "Verpasst am ehesten → nie den Flug" },
          { title: "Wird am schnellsten braun → verbrennt zuerst" },
          { title: "Plant den Urlaub am meisten → am wenigsten" },
          { title: "Beschwert sich im Urlaub am meisten → am wenigsten" },
          { title: "Ist am ehesten → am wenigsten der/die spontane Abenteurer:in" },
          { title: "Verliert am ehesten → nie den Koffer" },
          { title: "Gibt im Urlaub am meisten → am wenigsten Geld aus" },
        ],
        sets: [
          { title: "Bester → schlechtester Urlaubstyp", items: ["Strandresort", "Backpacking", "Städtetrip", "Kreuzfahrt", "All-Inclusive-Pauschal"] },
          { title: "Entspannendste → stressigste Urlaubsaktivität", items: ["Am Pool liegen", "Stadtführung", "Wandern", "Souvenirshopping", "Flughafen-Transfer"] },
          { title: "Größtes → kleinstes Urlaubs-Drama", items: ["Koffer verloren", "Sonnenbrand an Tag 1", "Flug verpasst", "Magen-Darm im Hotel", "Handy-Akku leer"] },
          { title: "Bestes → schlechtestes Festival-Erlebnis", items: ["Headliner live sehen", "Crowdsurfen", "Dixie-Klo um 3 Uhr", "Matschschlacht", "Zelt säuft im Regen ab"] },
          { title: "Entspannendstes → anstrengendstes Hobby", items: ["Lesen", "Yoga", "Zocken", "Marathon-Training", "Möbel selbst aufbauen"] },
          { title: "Schönstes → nervigstes Reisesouvenir", items: ["Kühlschrankmagnet", "Sand in jeder Tasche", "Sonnenbrand-Streifen", "3000 Handyfotos", "Eine neue Sprach-App"] },
        ],
      },
      history: {
        label: "🏛️ Politik & Geschichte",
        people: [
          { title: "Würde am besten → am schlechtesten regieren" },
          { title: "Hat am meisten → am wenigsten Geld aufm Konto" },
          { title: "Überlebt am längsten → am kürzesten im Mittelalter" },
          { title: "Zettelt am ehesten → am wenigsten eine Revolution an" },
          { title: "Glaubt am ehesten → am wenigsten an Verschwörungstheorien" },
          { title: "Wird am ehesten → am wenigsten Millionär:in" },
          { title: "Wäre der/die beste → schlechteste Diktator:in" },
          { title: "Hat am meisten → am wenigsten Macht in dieser Gruppe" },
        ],
        sets: [
          { title: "Wichtigste → überschätzteste Erfindung der Geschichte", items: ["Buchdruck", "Internet", "Das Rad", "Penicillin", "Selfie-Stick"] },
          { title: "Beste → unnötigste Eigenschaft eines Politikers", items: ["Ehrlichkeit", "Rückgrat", "Charisma", "Gutes Gedächtnis", "Schöne Reden"] },
          { title: "Größter → kleinster Wendepunkt der Geschichte", items: ["Mauerfall", "Mondlandung", "Erfindung des Internets", "Französische Revolution", "Erfindung des Kaffees"] },
          { title: "Coolste → langweiligste Epoche zum Zeitreisen", items: ["Antikes Rom", "Wilder Westen", "Die 80er", "Mittelalter", "Steinzeit"] },
          { title: "Glaubwürdigste → absurdeste Verschwörungstheorie", items: ["Mondlandung gefakt", "Echsenmenschen", "Flache Erde", "Aliens in Area 51", "Vögel sind Drohnen"] },
          { title: "Mächtigste → machtloseste Position", items: ["US-Präsident", "Großkonzern-CEO", "Influencer", "Bürgermeister", "Klassensprecher"] },
        ],
      },
      football: {
        label: "⚽ Fußball (WM)",
        people: [
          { title: "Würde am ehesten → am wenigsten Nationalspieler:in" },
          { title: "Feiert ein Tor am wildesten → am nüchternsten" },
          { title: "Würde am ehesten → am wenigsten schwalben" },
          { title: "Verpasst am ehesten → nie ein WM-Spiel wegen Arbeit" },
          { title: "Schreit am lautesten → am leisesten beim Elfmeter" },
          { title: "Hat das meiste → wenigste Trikot-Sammlung" },
          { title: "Würde am ehesten → am wenigsten Schiri werden" },
          { title: "Kennt die meisten → wenigsten Nationalhymnen" },
        ],
        sets: [
          { title: "Beste → schlechteste Nationalmannschaft bei der WM", items: ["Brasilien", "Argentinien", "Frankreich", "Deutschland", "England"] },
          { title: "Größter → kleinster Superstar dieser WM", items: ["Mbappé", "Messi", "Haaland", "Bellingham", "Vinícius Júnior"] },
          { title: "Bester → schlechtester WM-Gastgeber", items: ["USA", "Mexiko", "Kanada", "Katar 2022", "Brasilien 2014"] },
          { title: "Wichtigste → unnötigste Regel im Fußball", items: ["Abseits", "VAR", "Gelbe Karte", "Einwurf", "Vorteilsregel"] },
          { title: "Bester → schlechtester Elfmeterschütze-Typ", items: ["Eiskalter Panenka", "Volle Wucht ins Eck", "Kurzer Anlauf, sicher", "Der Zitterer", "Der Rebound-Verschwender"] },
          { title: "Legendärster → vergessenster WM-Moment", items: ["Hand Gottes", "Zidane-Kopfstoß", "Deutschland 7:1 Brasilien", "Elfmeterkrimi im Finale", "Last-Minute-Ausgleich"] },
          { title: "Beste → schlechteste Fanausstattung", items: ["Trikot", "Schminke im Landesfarben", "Vuvuzela", "Riesenflagge", "Perücke in Landesfarben"] },
          { title: "Nervigster → harmlosester Stadion-Nachbar beim Public Viewing", items: ["Der Alles-Besserwisser", "Der Dauerschreier", "Der, der ständig aufs Klo muss", "Der Handy-Dauerglotzer", "Der, der jedes Foul überzieht"] },
          { title: "Bester → schlechtester Job auf dem Platz", items: ["Torschütze", "Torwart", "Kapitän", "Ersatzbank", "Linienrichter"] },
          { title: "Größtes → kleinstes WM-Drama", items: ["Frühes Ausscheiden der Favoriten", "Verletzter Superstar", "Elfmeterschießen im Finale", "Skandal um den Schiri", "Wetterchaos im Stadion"] },
          { title: "Bestes → schlechtestes Public-Viewing-Essen", items: ["Bratwurst vom Grill", "Chips & Dip", "Pizza-Lieferservice", "Popcorn", "Kalter Toast"] },
          { title: "Beeindruckendstes → überflüssigstes Tor-Jubel", items: ["Salto", "Trikot ausziehen", "Zur Bank sprinten", "Baby-Wiege-Geste", "Einfach nur laufen"] },
          { title: "Bester → schlechtester Kommentatoren-Spruch", items: ["'Das Runde muss ins Eckige'", "Übertriebenes Gebrüll beim Tor", "Statistik-Overkill", "Falscher Spielername", "Stille nach dem Tor"] },
          { title: "Größte → kleinste Fußball-Rivalität", items: ["Deutschland – Niederlande", "Argentinien – Brasilien", "England – Deutschland", "Frankreich – Italien", "Nachbardorf-Derby"] },
          { title: "Bester → schlechtester Ort, ein WM-Spiel zu schauen", items: ["Public Viewing mit der ganzen Stadt", "Kneipe mit Kumpels", "Zuhause auf dem Sofa", "Stadion live", "Handy heimlich bei der Arbeit"] },
        ],
      },
      nsfw: {
        label: "🔞 18+",
        people: [
          { title: "Steht am ehesten → am wenigsten auf BDSM" },
          { title: "Hatte die meisten → wenigsten Partner:innen" },
          { title: "Ist am lautesten → am leisesten im Bett" },
          { title: "Schickt am ehesten → nie Nudes" },
          { title: "Ist am kinkiesten → am vanilligsten" },
          { title: "Hatte an den meisten → wenigsten Orten Sex" },
          { title: "Redet am dreckigsten → am unschuldigsten" },
          { title: "Würde am ehesten → am wenigsten einen Dreier machen" },
        ],
        sets: [
          // ── Soft entry ──
          { title: "Größter → verzeihlichster Ick", items: ["Schlechter Küsser", "Schreibt viel zu viel", "Wohnt noch bei den Eltern", "Null Ehrgeiz", "Quatscht im Kino"] },
          { title: "Bester → schlechtester Ort zum Rummachen", items: ["Ein echtes Bett (langweilig)", "Die Rückbank", "Ein Festivalzelt", "Bei den Eltern", "Im Büro"] },
          { title: "Größte → kleinste Red Flag", items: ["Schreibt noch dem Ex", "Hat keine Freunde", "Hasst Tiere", "Gibt mies Trinkgeld", "Liebt Comic Sans"] },
          { title: "Attraktivste → unwichtigste Eigenschaft", items: ["Selbstbewusstsein", "Geld", "Versauter Humor", "Sixpack", "Antwortet wirklich auf Nachrichten"] },
          { title: "Größter → kleinster Dealbreaker im Bett", items: ["Egoistisch", "Keine Mühe", "Hört nicht auf zu reden", "Lässt die Socken an", "Schläft danach sofort ein"] },
          { title: "Am meisten → am wenigsten überbewertet", items: ["Nacktbilder verschicken", "Sex unter der Dusche", "Knutschflecke", "Sexting", "Kuscheln am Morgen danach"] },
          // ── Härtere Sachen ──
          { title: "Heißeste → harmloseste Kink", items: ["Würgen", "Gefesselt werden", "Spanking", "Dirty Talk", "Augenbinde"] },
          { title: "Größtes → kleinstes Tabu, das dich trotzdem anmacht", items: ["Beim Sex beobachtet werden", "Ein Dreier", "Sex in der Öffentlichkeit", "Festgebunden werden", "Rollenspiel mit Kostüm"] },
          { title: "Am meisten → am wenigsten überbewertete Sexstellung", items: ["Doggy", "Reverse Cowgirl", "69", "Missionar", "Im Stehen"] },
          { title: "Versautestes → harmlosestes Sextoy", items: ["Strap-on", "Handschellen", "Vibrator", "Augenbinde", "Federpeitsche"] },
          { title: "Würde ich am ehesten → niemals ausprobieren", items: ["Ein Dreier", "Ein Sextape drehen", "Swingerparty", "BDSM-Dungeon", "Sex am FKK-Strand"] },
          { title: "Heißeste → unschuldigste Stelle zum Beißen", items: ["Innenschenkel", "Hals", "Nacken", "Ohrläppchen", "Bauch"] },
          { title: "Größter → kleinster Turn-on im Bett", items: ["Wird dominant", "Stöhnt deinen Namen", "Kratzt den Rücken auf", "Beißt in die Lippe", "Flüstert dreckig ins Ohr"] },
          { title: "Schmutzigster → harmlosester Ort, an dem du es getrieben hast", items: ["Auf der Arbeit", "Im Auto am Straßenrand", "Festival-Klo", "Im Hausflur", "Im Bett von Freunden"] },
          { title: "Bestes → schlimmstes Geräusch beim Sex", items: ["Lautes Stöhnen", "Deinen Namen stöhnen", "Dreckig reden", "Plötzliche Stille", "Aus Versehen lachen"] },
          { title: "Macht beim Sexting am meisten → am wenigsten an", items: ["Nacktbild ohne Vorwarnung", "Detaillierte Beschreibung", "Versaute Sprachnachricht", "Einfach 'komm vorbei'", "Emoji-Andeutungen"] },
          { title: "Heißester → langweiligster Dreier-Aufbau", items: ["Zwei Frauen", "Zwei Männer", "Paar plus eine:r", "Zwei Fremde aus der Bar", "Mit guten Freunden"] },
          { title: "Größte → harmloseste Bett-Sünde", items: ["An jemand anderen denken", "Den Namen verwechseln", "Mittendrin aufhören", "Heimlich filmen wollen", "Danach sofort einschlafen"] },
        ],
      },
    },

    en: {
      general: {
        label: "🎲 General",
        people: [
          { title: "Most → least likely to get famous" },
          { title: "Survives longest → shortest in the wild" },
          { title: "Most → least likely to end up in jail" },
          { title: "Has the fullest → emptiest fridge" },
          { title: "Most → least likely to survive the zombie apocalypse" },
          { title: "Most → least likely to secretly be a genius" },
          { title: "Most → least likely to show up late" },
          { title: "Most → least likely to sacrifice a finger for €1M" },
        ],
        sets: [
          { title: "Best → worst superpower", items: ["Invisibility", "Flying", "Time travel", "Reading minds", "Teleportation"] },
          { title: "Best → worst pizza topping", items: ["Pineapple", "Pepperoni", "Mushroom", "Extra cheese", "Anchovies"] },
          { title: "Most → least essential app", items: ["WhatsApp", "Instagram", "TikTok", "Google Maps", "Spotify"] },
          { title: "Dream → nightmare holiday", items: ["Beach resort", "City trip", "Camping", "Cruise", "Skiing"] },
          { title: "Best → worst way to spend a Sunday", items: ["Hungover in bed", "Big brunch", "A long hike", "Gaming all day", "Family visit"] },
          { title: "Most → least useful school subject", items: ["Maths", "PE", "History", "Art", "Religion"] },
          { title: "Best → worst fast food", items: ["McDonald's", "Burger King", "KFC", "Subway", "The kebab shop round the corner"] },
          { title: "Most → least important invention", items: ["The internet", "The washing machine", "The smartphone", "The microwave", "The selfie stick"] },
          { title: "Best → worst streaming service", items: ["Netflix", "Disney+", "Amazon Prime", "YouTube Premium", "DAZN"] },
          { title: "Most → least annoying flatmate type", items: ["The dish-stacker", "The constantly loud one", "The freeloader", "The cleaning freak", "The ghost (never home)"] },
          { title: "Best → worst pet", items: ["Dog", "Cat", "Hamster", "Snake", "Tarantula"] },
          { title: "Coolest → least cool job", items: ["Pilot", "YouTuber", "Doctor", "Tax advisor", "Politician"] },
          { title: "Most → least important phone feature", items: ["Battery life", "Camera", "Storage", "Screen size", "The colour"] },
          { title: "Best → worst day of the week", items: ["Friday", "Saturday", "Sunday", "Wednesday", "Monday"] },
          { title: "Best → worst season", items: ["Summer", "Spring", "Autumn", "Winter", "The wet week in between"] },
          { title: "Smartest → dumbest excuse for being late", items: ["Traffic jam", "Didn't hear the alarm", "Train got cancelled", "The dog was sick", "Lost track of time"] },
          { title: "Most useful → most overrated life skill", items: ["Managing money", "Cooking", "Small talk", "Driving", "Nice handwriting"] },
          { title: "Best → worst snack", items: ["Chocolate bar", "Crisps", "An apple", "Trail mix", "Cold coffee"] },
          { title: "Most impressive → lamest flex", items: ["Own flat at 22", "Expensive car", "Loads of followers", "A six-pack", "Drinking fancy water"] },
          { title: "Best → worst first-date topic", items: ["Travel", "Favourite music", "Family", "Politics", "The ex"] },
          { title: "Most → least important value in a friendship", items: ["Honesty", "Loyalty", "Humour", "Punctuality", "Same taste in music"] },
        ],
      },
      party: {
        label: "🎉 Party",
        people: [
          { title: "First → last to throw up" },
          { title: "Can handle the most → least booze" },
          { title: "Dances the wildest → stiffest" },
          { title: "Most → least likely to drunk-text the ex" },
          { title: "First → last to get kicked out" },
          { title: "First → last to pass out" },
          { title: "Most → least likely to start a fight" },
          { title: "Most → least likely to be last on the dance floor" },
        ],
        sets: [
          { title: "Most → least acceptable drunk behaviour", items: ["Crying in the toilets", "Texting your ex", "Starting beef", "Passing out", "Yapping"] },
          { title: "Most → least classy drink", items: ["Champagne", "Craft beer", "Tequila shots", "Boxed wine", "Jägerbombs"] },
          { title: "Biggest → smallest party foul", items: ["Throwing up indoors", "Breaking stuff", "Spilling a drink", "Leaving early", "Skipping songs"] },
          { title: "Best → worst hangover cure", items: ["Greasy food", "Hair of the dog", "Sleeping till noon", "Water & ibuprofen", "Gym"] },
          { title: "Most → least likely to get you kicked out", items: ["Starting a fight", "Skinny dipping", "Dissing the host", "Peeing in the plant pot", "Passing out"] },
          { title: "Best → worst person to be stuck next to at a party", items: ["The mess", "The yapper", "The DJ", "The ex", "The boss"] },
          { title: "Best → worst pre-game drink", items: ["Aperol Spritz", "Road beer", "Vodka mixer", "Mulled wine", "Warm prosecco"] },
          { title: "Best → worst person to walk home with", items: ["The sober one with snacks", "The one who knows the night bus", "The taxi sponsor", "The one who pukes every 50 metres", "The one who insists on going on"] },
          { title: "Most legendary → most embarrassing dance-floor move", items: ["The moonwalk", "Air guitar", "Wild breakdance", "Twerking on the speaker", "Just falling over"] },
          { title: "Best → worst afterparty spot", items: ["A house party", "By the lake", "In the park", "The car park", "The petrol station"] },
          { title: "Biggest → smallest party hero", items: ["The DJ", "The one with the refills", "The host", "The one who knows the bouncer", "The cleanup crew"] },
          { title: "Best → worst shot", items: ["Tequila", "Jägermeister", "Sambuca", "Vodka", "Mystery shot"] },
          { title: "Biggest → smallest house-party drama", items: ["The cops show up", "Neighbours complain", "Someone throws up on the sofa", "The booze runs out", "Aux cord war"] },
          { title: "Best → worst reason to buy a round", items: ["A birthday", "A promotion", "Surviving a breakup", "Just because", "Out of guilt"] },
          { title: "Coolest → most cringe party trick", items: ["Opening a beer with a lighter", "A card trick", "Beatboxing", "Ventriloquism", "Jokes nobody gets"] },
          { title: "Best → worst excuse to leave early", items: ["Early start tomorrow", "The babysitter's waiting", "Gotta walk the dog", "Just done", "Just ghosting"] },
          { title: "Biggest → smallest hazard at a house party", items: ["The stairs", "The pool", "The barbecue", "The white couch", "The dodgy speaker"] },
          { title: "Best → worst beer-pong teammate", items: ["The sniper", "The pick-me girl", "The trash-talker", "The shaky one", "The already-plastered one"] },
        ],
      },
      videogames: {
        label: "🎮 Video Games",
        people: [
          { title: "Most → least likely to rage-quit" },
          { title: "The best → worst gamer" },
          { title: "Spams the mic the most → least" },
          { title: "Most → least likely to blame the team" },
          { title: "Games the longest → shortest in one sitting" },
          { title: "Spends the most → least on skins" },
          { title: "Camps the most → pushes the most" },
          { title: "Most → least likely to throw the controller" },
        ],
        sets: [
          // ── General ──
          { title: "Most → least annoying gamer type", items: ["The rage-quitter", "The mic spammer", "The smurf", "The try-hard", "The AFK farmer"] },
          { title: "Best → worst excuse after a loss", items: ["Lag", "The team's fault", "My mouse glitched", "Sun in my eyes", "Controller drift"] },
          { title: "Best → worst gaming platform", items: ["PC", "PlayStation", "Xbox", "Switch", "Phone"] },
          { title: "Most toxic → most chill community", items: ["League of Legends", "Counter-Strike", "Overwatch", "Dark Souls", "Stardew Valley"] },
          { title: "Best → worst gaming snack", items: ["Frozen pizza", "Crisps", "Energy drink", "Chocolate bar", "Yesterday's cold fries"] },
          { title: "Biggest → smallest gaming flex", items: ["1v5 clutch", "Ranked top 500", "A rare skin", "Speedrun record", "Expensive gaming chair"] },
          // (Minecraft has its own category now — see the ⛏️ pool.)
          // ── Overwatch ──
          { title: "Most → least hated hero", items: ["Widowmaker", "Mei", "Sombra", "Hanzo", "Genji"] },
          { title: "Most → least annoying ult to get hit by", items: ["Genji Blade", "Junkrat Tire", "Pharah Barrage", "Reaper Death Blossom", "Mei Blizzard"] },
          { title: "Best → worst support", items: ["Ana", "Kiriko", "Mercy", "Lúcio", "Moira"] },
          { title: "Most → least rewarding role", items: ["DPS", "Flex support", "Main tank", "Off-tank", "Main support"] },
          { title: "Biggest → smallest tilt moment", items: ["No healer on the team", "Enemy Bastion in the choke", "Mercy rezzes at the worst time", "DPS who hit nothing", "Nobody goes on the objective"] },
          // ── Counter-Strike ──
          { title: "Best → worst map", items: ["Mirage", "Inferno", "Dust 2", "Nuke", "Vertigo"] },
          { title: "Most → least stylish kill", items: ["AWP no-scope", "Knife from behind", "Deagle headshot", "AK spray", "P90 spam"] },
          { title: "Biggest → smallest tilt moment (CS)", items: ["Teamkill in the first second", "Lost 16:14", "Ace stolen by a teammate", "Lost the eco round", "Grenade into your own team"] },
          { title: "Most → least annoying teammate (CS)", items: ["Rage-quits after pistol", "Constantly yells Rush B", "Picks AWP and whiffs everything", "Mic spammer with music", "Throws flashes into your own team"] },
          { title: "Best → worst eco weapon", items: ["Deagle", "Tec-9", "P250", "Dual Berettas", "Glock spray"] },
        ],
      },
      minecraft: {
        label: "⛏️ Minecraft",
        people: [
          { title: "Survives the first night the longest → shortest" },
          { title: "Builds the prettiest → ugliest" },
          { title: "Most → least likely to dig straight down" },
          { title: "Most → least likely to get addicted to Minecraft" },
          { title: "Most → least likely to be the group's redstone nerd" },
          { title: "Most → least likely to fall into their own lava" },
          { title: "Most → least likely to get lost in the Nether" },
          { title: "Most → least likely to rage-quit when the base blows up" },
        ],
        sets: [
          { title: "Scariest → most harmless mob", items: ["The Warden", "Enderman", "Creeper", "Zombie", "Chicken"] },
          { title: "Most → least valuable ore", items: ["Netherite", "Diamond", "Emerald", "Redstone", "Coal"] },
          { title: "Best → worst way to die", items: ["Creeper from behind", "Fell into lava", "Fell off the scaffolding", "Drowned", "Starved while building"] },
          { title: "Most impressive → lamest build", items: ["Huge castle", "Automatic farm", "Pixel art", "Cobblestone tower to the sky", "Dirt house"] },
          { title: "First → last priority on night 1", items: ["Farm wood", "Craft tools", "Find food", "Build a house", "Dig a hole"] },
          { title: "Most → least useful tool", items: ["Diamond pickaxe", "Elytra", "Water bucket", "Fishing rod", "Shears"] },
          { title: "Best → worst enchantment", items: ["Mending", "Protection", "Efficiency", "Silk Touch", "Curse of Binding"] },
          { title: "Most dangerous → safest place", items: ["Ancient City", "Nether fortress", "Woodland Mansion", "Dark cave", "Village"] },
          { title: "Best → worst potion", items: ["Regeneration", "Fire Resistance", "Night Vision", "Jump Boost", "Potion of Weakness"] },
          { title: "Best → worst biome to spawn in", items: ["Plains", "Forest", "Badlands", "Swamp", "Icy tundra"] },
          { title: "Most → least annoying moment", items: ["Creeper blows up your build", "No bed at night", "Lost in the Nether", "Tool breaks mid-mine", "A sheep eats your grass"] },
        ],
      },
      leisure: {
        label: "🏖️ Leisure & Travel",
        people: [
          { title: "Packs the biggest → smallest suitcase" },
          { title: "Most → least likely to miss the flight" },
          { title: "Tans the fastest → burns first" },
          { title: "Plans the holiday the most → least" },
          { title: "Complains the most → least on holiday" },
          { title: "Most → least likely to be the spontaneous adventurer" },
          { title: "Most → least likely to lose their luggage" },
          { title: "Spends the most → least on holiday" },
        ],
        sets: [
          { title: "Best → worst holiday type", items: ["Beach resort", "Backpacking", "City trip", "Cruise", "All-inclusive package"] },
          { title: "Most relaxing → most stressful holiday activity", items: ["Lying by the pool", "Guided city tour", "Hiking", "Souvenir shopping", "Airport transfer"] },
          { title: "Biggest → smallest holiday disaster", items: ["Lost luggage", "Day-1 sunburn", "Missed flight", "Food poisoning at the hotel", "Dead phone battery"] },
          { title: "Best → worst festival moment", items: ["Seeing the headliner live", "Crowd surfing", "Portaloo at 3am", "Mud fight", "Tent flooding in the rain"] },
          { title: "Most relaxing → most exhausting hobby", items: ["Reading", "Yoga", "Gaming", "Marathon training", "Building flat-pack furniture"] },
          { title: "Best → most annoying travel souvenir", items: ["Fridge magnet", "Sand in every bag", "Sunburn lines", "3000 phone photos", "A new language app"] },
        ],
      },
      history: {
        label: "🏛️ Politics & History",
        people: [
          { title: "Would rule the best → worst" },
          { title: "Has the most → least money in the bank" },
          { title: "Survives longest → shortest in the Middle Ages" },
          { title: "Most → least likely to start a revolution" },
          { title: "Most → least likely to believe conspiracy theories" },
          { title: "Most → least likely to become a millionaire" },
          { title: "Would be the best → worst dictator" },
          { title: "Has the most → least power in this group" },
        ],
        sets: [
          { title: "Most important → most overrated invention in history", items: ["The printing press", "The internet", "The wheel", "Penicillin", "The selfie stick"] },
          { title: "Best → most pointless trait in a politician", items: ["Honesty", "A spine", "Charisma", "A good memory", "Pretty speeches"] },
          { title: "Biggest → smallest turning point in history", items: ["Fall of the Berlin Wall", "Moon landing", "Invention of the internet", "French Revolution", "Invention of coffee"] },
          { title: "Coolest → most boring era to time-travel to", items: ["Ancient Rome", "Wild West", "The 80s", "The Middle Ages", "The Stone Age"] },
          { title: "Most believable → most absurd conspiracy theory", items: ["Faked moon landing", "Lizard people", "Flat earth", "Aliens in Area 51", "Birds are drones"] },
          { title: "Most → least powerful position", items: ["US President", "Megacorp CEO", "Influencer", "Mayor", "Class president"] },
        ],
      },
      football: {
        label: "⚽ Football (World Cup)",
        people: [
          { title: "Most → least likely to go pro" },
          { title: "Celebrates a goal the wildest → most reserved" },
          { title: "Most → least likely to flop for a penalty" },
          { title: "Most → least likely to miss a World Cup match for work" },
          { title: "Screams the loudest → quietest at a penalty" },
          { title: "Owns the biggest → smallest jersey collection" },
          { title: "Most → least likely to become a referee" },
          { title: "Knows the most → fewest national anthems" },
        ],
        sets: [
          { title: "Best → worst national team at the World Cup", items: ["Brazil", "Argentina", "France", "Germany", "England"] },
          { title: "Biggest → smallest superstar of this World Cup", items: ["Mbappé", "Messi", "Haaland", "Bellingham", "Vinícius Júnior"] },
          { title: "Best → worst World Cup host", items: ["USA", "Mexico", "Canada", "Qatar 2022", "Brazil 2014"] },
          { title: "Most → least necessary rule in football", items: ["Offside", "VAR", "Yellow card", "Throw-in", "Advantage rule"] },
          { title: "Best → worst penalty-taker type", items: ["Ice-cold Panenka", "Blast it in the corner", "Short run-up, sure thing", "The shaky one", "The rebound-waster"] },
          { title: "Most legendary → most forgotten World Cup moment", items: ["The Hand of God", "Zidane's headbutt", "Germany 7:1 Brazil", "Penalty shootout in the final", "Last-minute equaliser"] },
          { title: "Best → worst fan gear", items: ["Jersey", "Face paint in national colours", "Vuvuzela", "Giant flag", "Wig in national colours"] },
          { title: "Most → least annoying person next to you at a public viewing", items: ["The know-it-all", "The nonstop screamer", "The one who's always in the bathroom", "The phone zombie", "The one who oversells every foul"] },
          { title: "Best → worst job on the pitch", items: ["Goalscorer", "Goalkeeper", "Captain", "Substitute bench", "Linesman"] },
          { title: "Biggest → smallest World Cup drama", items: ["A favourite gets knocked out early", "A superstar gets injured", "Penalty shootout in the final", "A referee scandal", "Weather chaos in the stadium"] },
          { title: "Best → worst public-viewing food", items: ["Grilled sausage", "Chips & dip", "Delivery pizza", "Popcorn", "Cold toast"] },
          { title: "Most impressive → most pointless goal celebration", items: ["A backflip", "Ripping off the jersey", "Sprinting to the bench", "The baby-rocking gesture", "Just running"] },
          { title: "Best → worst commentator moment", items: ["The classic goaaal scream", "Over-the-top roaring at a goal", "Stat overkill", "Getting the player's name wrong", "Dead silence after a goal"] },
          { title: "Biggest → smallest football rivalry", items: ["Germany – Netherlands", "Argentina – Brazil", "England – Germany", "France – Italy", "The next-town derby"] },
          { title: "Best → worst place to watch a World Cup match", items: ["A public viewing with the whole city", "A pub with mates", "Home on the sofa", "Live in the stadium", "Sneaking a look at work"] },
        ],
      },
      nsfw: {
        label: "🔞 18+",
        people: [
          { title: "Most → least into BDSM" },
          { title: "Has had the most → fewest partners" },
          { title: "Loudest → quietest in bed" },
          { title: "Most → least likely to send nudes" },
          { title: "The kinkiest → most vanilla" },
          { title: "Has had sex in the most → fewest places" },
          { title: "Talks the dirtiest → most innocent" },
          { title: "Most → least likely to have a threesome" },
        ],
        sets: [
          // ── Soft entry ──
          { title: "Biggest → most forgivable ick", items: ["Bad kisser", "Texts way too much", "Still lives with parents", "Zero ambition", "Talks during the film"] },
          { title: "Best → worst place to hook up", items: ["A real bed (boring)", "The back seat", "A festival tent", "Parents' house", "The office"] },
          { title: "Biggest → smallest red flag", items: ["Still texts their ex", "Has no friends", "Hates animals", "Terrible tipper", "Loves Comic Sans"] },
          { title: "Most → least attractive trait", items: ["Confidence", "Money", "A filthy sense of humour", "Abs", "Actually replies to texts"] },
          { title: "Biggest → smallest dealbreaker in bed", items: ["Selfish", "No effort", "Won't stop talking", "Keeps socks on", "Falls asleep after"] },
          { title: "Most → least overrated", items: ["Sending nudes", "Shower sex", "Hickeys", "Sexting", "Morning after cuddles"] },
          // ── Harder stuff ──
          { title: "Hottest → most harmless kink", items: ["Choking", "Being tied up", "Spanking", "Dirty talk", "Blindfold"] },
          { title: "Biggest → smallest taboo that still turns you on", items: ["Being watched during sex", "A threesome", "Sex in public", "Being restrained", "Roleplay with a costume"] },
          { title: "Most → least overrated sex position", items: ["Doggy", "Reverse cowgirl", "69", "Missionary", "Standing up"] },
          { title: "Filthiest → most harmless sex toy", items: ["Strap-on", "Handcuffs", "Vibrator", "Blindfold", "Feather whip"] },
          { title: "Most → least likely to try", items: ["A threesome", "Filming a sextape", "Swingers' party", "BDSM dungeon", "Sex on a nude beach"] },
          { title: "Hottest → most innocent spot to bite", items: ["Inner thigh", "Throat", "Back of the neck", "Earlobe", "Stomach"] },
          { title: "Biggest → smallest turn-on in bed", items: ["Gets dominant", "Moans your name", "Scratches your back up", "Bites your lip", "Whispers something filthy"] },
          { title: "Filthiest → most harmless place you've done it", items: ["At work", "In a car on the roadside", "Festival toilet", "The stairwell", "In a friend's bed"] },
          { title: "Best → worst sound during sex", items: ["Loud moaning", "Moaning your name", "Talking dirty", "Sudden silence", "Accidental laughing"] },
          { title: "Turns you on most → least when sexting", items: ["A nude with no warning", "A detailed description", "A filthy voice note", "Just 'come over'", "Emoji hints"] },
          { title: "Hottest → most boring threesome setup", items: ["Two women", "Two men", "Couple plus one", "Two strangers from the bar", "With close friends"] },
          { title: "Biggest → most harmless sin in bed", items: ["Thinking of someone else", "Saying the wrong name", "Stopping halfway", "Wanting to film it secretly", "Falling asleep right after"] },
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.RankItSets = RANKIT;
})(window);
