// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/simon.js — content for "Simon sagt" (Simon Says, voice-driven)
 *
 * EDIT ME. Pure content, no game logic. These are BARE imperative commands
 * WITHOUT the "Simon sagt:" prefix — the game reads a command aloud and randomly
 * decides whether to slap "Simon sagt:" in front of it. Players only obey when
 * the prefix is there. Keep commands short, doable instantly while seated in a
 * group, and smooth for text-to-speech to read.
 *
 * Pools keep theme editable and language-switchable. Add a key and it shows up
 * as a selectable chip automatically. `label` is what players see; the key is
 * the internal id. Keep de/en mirrored.
 */
(function (global) {
  "use strict";

  var SIMON = {
    de: {
      koerper: {
        label: "🤸 Körper & Gesten",
        commands: [
          "fass dein linkes Ohr an",
          "heb beide Hände",
          "berühr deine Nase",
          "zwinker deinem Nachbarn zu",
          "dreh dich einmal im Kreis",
          "klatsch dreimal in die Hände",
          "streck die Zunge raus",
          "leg beide Hände auf den Kopf",
          "mach ein Herz mit den Händen",
          "lächle so breit du kannst",
          "zeig deine Muskeln",
          "kratz dich am Kopf",
          "verschränk die Arme vor der Brust",
          "deute zur Decke",
          "nick dreimal mit dem Kopf",
          "berühr deinen linken Ellenbogen",
          "mach ein Peace-Zeichen",
          "schließ die Augen und zähl bis drei",
          "steh kurz auf und setz dich wieder",
          "mach einen Kussmund",
          "wackel mit den Ohren, so gut es geht",
          "streck beide Arme nach vorne",
          "beuge dich nach links",
          "mach dich ganz klein",
          "reib dir den Bauch",
          "leg den Kopf schief",
          "hüpf einmal auf der Stelle",
          "mach eine Verbeugung",
          "zeig mit dem Finger auf jemanden am Tisch",
          "stell dich auf ein Bein",
        ],
      },
      party: {
        label: "🎉 Party",
        commands: [
          "nimm einen Schluck",
          "prost mit deinem Nachbarn",
          "trink auf ex",
          "verteile zwei Schlücke",
          "nimm einen großen Schluck",
          "stoß mit allen an",
          "trink mit der linken Hand",
          "sing eine Zeile deines Lieblingslieds",
          "mach eine Welle wie im Stadion",
          "ruf laut Prost",
          "verteile einen Schluck an wen du willst",
          "trink, wenn du heute schon gelacht hast",
          "tausch dein Getränk mit dem Nachbarn",
          "mach den lautesten Jubel, den du kannst",
          "erfinde einen Trinkspruch",
          "trink so viele Schlücke wie du Geschwister hast",
          "balanciere dein Glas auf dem Handrücken",
          "gib deinem Nachbarn ein High-Five",
          "stell dein Glas auf den Kopf und trink ohne Hände",
          "nenn dein Lieblingsgetränk laut",
          "trink, wenn du diese Woche schon gefeiert hast",
          "mach einen Toast auf die ganze Runde",
          "bring alle zum Anstoßen",
          "erzähl in einem Satz, warum du heute hier bist",
          "trink, ohne das Glas mit der Hand zu berühren",
          "leg dein Glas für zehn Sekunden weg",
          "verteile Applaus für dich selbst",
          "trink so schnell du kannst, ohne zu kleckern",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        commands: [
          "flüster deinem Nachbarn etwas Verruchtes ins Ohr",
          "mach deinen sexiesten Blick",
          "beiß dir verführerisch auf die Lippe",
          "schick einer Person am Tisch einen Luftkuss",
          "sag deinem Nachbarn ein anzügliches Kompliment",
          "streich dir langsam durch die Haare",
          "zwinker der attraktivsten Person am Tisch zu",
          "flüster ganz leise dein heißestes Reizwort",
          "roll verführerisch mit der Schulter",
          "leck dir genüsslich über die Lippen",
          "mach einen langen Kussmund in die Runde",
          "stöhne einmal möglichst überzeugend",
          "mach deinem Nachbarn fünf Sekunden schöne Augen",
          "flirte eine Runde lang mit deinem Getränk",
          "sag mit tiefer Stimme komm näher",
          "pust deinem Nachbarn sanft ins Gesicht",
          "beschreib deinen Idealtyp in einem Wort",
          "tanz zwei Sekunden lang sexy auf deinem Stuhl",
          "streich deinem Nachbarn übers Bein",
          "flüster jemandem zu, was dir an ihm oder ihr gefällt",
          "mach ein Bett-Gesicht",
          "sag laut, wer am Tisch am besten küssen kann",
          "zeig mit einer Geste, was du dir heute Nacht wünschst",
          "flirte eine Runde lang nur mit Blicken",
          "mach ein leises Knurren, das verführerisch klingen soll",
          "beschreib dein perfektes Date in drei Worten",
        ],
      },
    },
    en: {
      koerper: {
        label: "🤸 Body & Gestures",
        commands: [
          "touch your left ear",
          "raise both hands",
          "touch your nose",
          "wink at your neighbour",
          "spin around once",
          "clap three times",
          "stick out your tongue",
          "put both hands on your head",
          "make a heart with your hands",
          "smile as wide as you can",
          "show off your muscles",
          "scratch your head",
          "cross your arms over your chest",
          "point at the ceiling",
          "nod your head three times",
          "touch your left elbow",
          "make a peace sign",
          "close your eyes and count to three",
          "stand up briefly and sit back down",
          "make a kissy face",
          "wiggle your ears as best you can",
          "stretch both arms out in front of you",
          "lean to the left",
          "make yourself as small as possible",
          "rub your belly",
          "tilt your head sideways",
          "hop once in place",
          "take a bow",
          "point a finger at someone at the table",
          "stand on one leg",
        ],
      },
      party: {
        label: "🎉 Party",
        commands: [
          "take a sip",
          "cheers with your neighbour",
          "down your drink",
          "hand out two sips",
          "take a big gulp",
          "clink glasses with everyone",
          "drink with your left hand",
          "sing one line of your favourite song",
          "do a stadium wave",
          "shout Cheers out loud",
          "hand out a sip to whoever you want",
          "drink if you've laughed today",
          "swap drinks with your neighbour",
          "do the loudest cheer you can",
          "make up a toast",
          "take one sip for each sibling you have",
          "balance your glass on the back of your hand",
          "give your neighbour a high five",
          "put your glass on your head and drink hands-free",
          "shout out your favourite drink",
          "drink if you've partied this week already",
          "give a toast to the whole table",
          "get everyone to clink glasses",
          "explain in one sentence why you're here tonight",
          "drink without touching the glass with your hand",
          "put your glass down for ten seconds",
          "applaud yourself",
          "drink as fast as you can without spilling",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        commands: [
          "whisper something naughty in your neighbour's ear",
          "give your sexiest look",
          "bite your lip seductively",
          "blow a kiss to someone at the table",
          "give your neighbour a suggestive compliment",
          "slowly run your fingers through your hair",
          "wink at the most attractive person at the table",
          "whisper your hottest word very quietly",
          "roll your shoulder seductively",
          "lick your lips with delight",
          "make a long pouty kiss face to the room",
          "moan once as convincingly as you can",
          "make eyes at your neighbour for five seconds",
          "flirt with your drink for one round",
          "say come closer in a deep voice",
          "gently blow air at your neighbour's face",
          "describe your ideal type in one word",
          "dance sexy on your chair for two seconds",
          "run your hand along your neighbour's leg",
          "whisper to someone what you like about them",
          "make a bedroom face",
          "say out loud who's the best kisser at the table",
          "gesture what you're hoping for tonight",
          "flirt with just your eyes for one round",
          "let out a low growl meant to sound seductive",
          "describe your perfect date in three words",
        ],
      },
    },
    es: {
      koerper: {
        label: "🤸 Cuerpo y gestos",
        commands: [
          "tócate la oreja izquierda",
          "levanta las dos manos",
          "tócate la nariz",
          "guíñale un ojo a tu vecino",
          "da una vuelta sobre ti mismo",
          "aplaude tres veces",
          "saca la lengua",
          "pon las dos manos en la cabeza",
          "haz un corazón con las manos",
          "sonríe lo más que puedas",
          "enseña músculo",
          "ráscate la cabeza",
          "cruza los brazos sobre el pecho",
          "señala el techo",
          "asiente tres veces",
          "tócate el codo izquierdo",
          "haz el signo de la paz",
          "cierra los ojos y cuenta hasta tres",
          "levántate un momento y vuelve a sentarte",
          "pon morritos",
          "mueve las orejas como puedas",
          "estira los dos brazos hacia delante",
          "inclínate a la izquierda",
          "hazte lo más pequeño posible",
          "frótate la barriga",
          "inclina la cabeza hacia un lado",
          "da un salto en el sitio",
          "haz una reverencia",
          "señala con el dedo a alguien de la mesa",
          "ponte a la pata coja",
        ],
      },
      party: {
        label: "🎉 Fiesta",
        commands: [
          "bebe un trago",
          "brinda con tu vecino",
          "acábate la copa",
          "reparte dos tragos",
          "da un buen trago",
          "choca la copa con todos",
          "bebe con la mano izquierda",
          "canta una frase de tu canción favorita",
          "haz la ola",
          "grita salud bien alto",
          "reparte un trago a quien quieras",
          "bebe si hoy te has reído",
          "cambia la bebida con tu vecino",
          "haz el brindis más ruidoso que puedas",
          "improvisa un brindis",
          "bebe un trago por cada hermano que tengas",
          "mantén la copa en equilibrio sobre el dorso de la mano",
          "choca los cinco con tu vecino",
          "ponte la copa en la cabeza y bebe sin manos",
          "grita tu bebida favorita",
          "bebe si ya has salido de fiesta esta semana",
          "haz un brindis por toda la mesa",
          "haz que todos choquen las copas",
          "explica en una frase por qué estás aquí esta noche",
          "bebe sin tocar la copa con la mano",
          "deja la copa en la mesa diez segundos",
          "apláudete a ti mismo",
          "bebe lo más rápido que puedas sin derramar",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        commands: [
          "susúrrale algo picante al oído a tu vecino",
          "pon tu mirada más sexy",
          "muérdete el labio de forma seductora",
          "lánzale un beso a alguien de la mesa",
          "hazle a tu vecino un cumplido sugerente",
          "pásate los dedos por el pelo despacio",
          "guíñale un ojo a la persona más atractiva de la mesa",
          "susurra muy bajito tu palabra más caliente",
          "mueve el hombro de forma seductora",
          "relámete los labios con gusto",
          "ponle a la sala morritos de beso largo",
          "gime una vez lo más convincente que puedas",
          "échale miraditas a tu vecino durante cinco segundos",
          "liga con tu bebida durante una ronda",
          "di acércate con voz grave",
          "sopla suavemente en la cara de tu vecino",
          "describe tu tipo ideal en una palabra",
          "baila sexy en tu silla dos segundos",
          "pasa la mano por la pierna de tu vecino",
          "susúrrale a alguien qué te gusta de él",
          "pon cara de dormitorio",
          "di en voz alta quién besa mejor de la mesa",
          "haz un gesto de lo que esperas de esta noche",
          "liga solo con la mirada durante una ronda",
          "suelta un gruñido grave que pretenda ser seductor",
          "describe tu cita perfecta en tres palabras",
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.SimonCommands = SIMON;
})(window);
