// © 2026 Paul Spieker — All rights reserved. Proprietary; do not copy or redistribute.
/*
 * content/truth.js — content for Truth or Drink (NSFW, adults only)
 *
 * EDIT ME. Pure content. Each entry is a TRUTH question put to one player. In
 * drinking mode they can dodge it by drinking; in plain mode they just answer.
 * The 🔞 pool is where it gets spicy.
 */
(function (global) {
  "use strict";

  var TRUTH = {
    de: {
      general: {
        label: "🎲 Allgemein",
        prompts: [
          "Was ist das Peinlichste in deinem Suchverlauf?",
          "Welche Lüge erzählst du ständig?",
          "Mit wem in diesem Raum würdest du für eine Woche das Leben tauschen?",
          "Aus welchem nichtigsten Grund hast du mal eine Freundschaft beendet?",
          "Was war das schlechteste Geschenk, das du je bekommen hast?",
          "Was tust du nur so, als würdest du es mögen, hasst es aber heimlich?",
          "Wen in diesem Raum hast du schon mal heimlich auf Social Media gestalkt?",
          "Was war deine peinlichste Phase als Teenager?",
          "Welche völlig unpopuläre Meinung würdest du bis zum Schluss verteidigen?",
          "Wie viel Geld hast du wirklich auf dem Konto – ungefähr?",
          "Was ist die größte Lüge, die in deinem Lebenslauf steht?",
          "Welchen Song hörst du heimlich rauf und runter, würdest es aber nie zugeben?",
          "Wem in diesem Raum würdest du niemals Geld leihen?",
          "Was ist das Kindischste, das du als Erwachsener noch tust?",
          "Wie lange brauchst du wirklich, um auf eine Nachricht zu antworten, die du gesehen hast?",
          "Welche Person aus deiner Vergangenheit würdest du gern noch mal blockieren?",
          "Was war dein dümmster Spontankauf der letzten Zeit?",
          "Wen in diesem Raum hast du anfangs total falsch eingeschätzt?",
          "Welche Ausrede benutzt du am häufigsten, um Pläne abzusagen?",
          "Was würdest du tun, wenn du eine Woche lang unsichtbar wärst?",
          "Auf welchem Dating-Profil hast du am meisten geschummelt?",
        ],
      },
      party: {
        label: "🎉 Party",
        prompts: [
          "Wie betrunken warst du jemals höchstens?",
          "Was ist das Schlimmste, das du auf einer durchzechten Nacht angestellt hast?",
          "Wem hier würdest du dein entsperrtes Handy am wenigsten anvertrauen?",
          "An welche durchzechte Nacht erinnerst du dich ehrlich gar nicht mehr?",
          "Was war deine peinlichste betrunkene Nachricht?",
          "Über wen in diesem Raum hast du hinter dem Rücken geredet?",
          "Wer hier verträgt am wenigsten Alkohol – ehrlich?",
          "Was war das Letzte, das du betrunken bestellt oder gekauft hast?",
          "Mit wem in diesem Raum würdest du am liebsten mal richtig die Nacht durchmachen?",
          "Was war deine peinlichste Aktion auf einer fremden Party?",
          "Wer hier wird auf der Tanzfläche am schlimmsten, sobald genug Drinks intus sind?",
          "Welchen Filmriss würdest du gern zurückgespult bekommen, um zu sehen, was passiert ist?",
          "Wem hier hast du betrunken mal deine Liebe gestanden?",
          "Was war dein peinlichster Auftritt am Tag nach einer Party (Stichwort Kater)?",
          "Wen in diesem Raum hast du schon mal nach Hause tragen oder retten müssen?",
          "Was ist das Verrückteste, das du je gemacht hast, um an Drinks zu kommen?",
          "Bei welcher Wette unter Alkohol hast du dich am meisten blamiert?",
          "Wer hier ist heimlich der größte Drama-Magnet auf Partys?",
          "Was war dein schlimmster Drunk-Text an einen Ex?",
          "Mit wem aus diesem Raum hast du schon mal angebandelt und es bereut?",
          "Welches Gerücht über dich von einer Party stimmt tatsächlich?",
        ],
      },
      leisure: {
        label: "🏖️ Freizeit & Urlaub",
        prompts: [
          "Was war dein peinlichstes Urlaubserlebnis?",
          "Welches Reiseziel ist völlig überbewertet?",
          "Was hast du im Urlaub schon mal mitgehen lassen (Hotel-Handtuch zählt)?",
          "Wohin würdest du sofort auswandern?",
          "Was war dein größtes Reise-Desaster?",
          "Mit wem in diesem Raum würdest du am liebsten verreisen – und mit wem niemals?",
        ],
      },
      history: {
        label: "🏛️ Politik & Geschichte",
        prompts: [
          "Welche historische Person würdest du gern treffen?",
          "In welcher Epoche hättest du lieber gelebt?",
          "Welche Verschwörungstheorie findest du heimlich ein bisschen plausibel?",
          "Wenn du einen Tag lang die absolute Macht hättest – was würdest du tun?",
          "Welches Schulfach war für dich am nutzlosesten?",
          "Über welches politische Thema regst du dich am meisten auf?",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "Wie hoch ist dein Body Count? (sei ehrlich)",
          "Was war der verrückteste Ort, an dem du es getrieben hast?",
          "Bei wem in diesem Raum würdest du nach rechts wischen?",
          "Was ist dein größter Turn-on?",
          "Welche Fantasie hast du noch niemandem erzählt?",
          "Was ist das Versauteste, das du je gemacht hast?",
          "An wen in diesem Raum hast du schon mal nackt gedacht?",
          "Was ist dein seltsamster Turn-on?",
          "Beschreib deinen letzten One-Night-Stand in drei Worten.",
          "Was war der öffentlichste Ort, an dem du es gemacht hast?",
          "Hast du es jemals vorgetäuscht? Bei wem?",
          "Was ist das Schlimmste, das du je im Bett gemacht hast?",
          "Wer war dein bester Sex aller Zeiten und warum?",
          "Welchen Kink würdest du wirklich gern mal ausprobieren?",
          "Wonach hast du zuletzt gesucht, das dir peinlich wäre?",
          "Hattest du je was mit dem Ex von jemandem in diesem Raum?",
          "Was war dein bestes Sexting-Erlebnis?",
          "An welchem Körperteil von dir stehen andere am meisten, das dir selbst egal ist?",
          "Was ist die verrückteste Location, an der du fast erwischt worden wärst?",
          "Welches Rollenspiel-Szenario reizt dich am meisten?",
          "Was war dein peinlichstes Erlebnis beim Ausziehen?",
          "Welchen Satz willst du im Bett am liebsten hören?",
          "Was hältst du für überbewertet, wenn's um Sex geht?",
          "Wie oft denkst du an einem normalen Tag an Sex?",
          "Was ist die kürzeste Zeit, die zwischen Kennenlernen und Sex vergangen ist?",
          "Welche Dating-App-Nachricht hat bei dir sofort funktioniert?",
        ],
      },
      date: {
        label: "🌹 Date",
        prompts: [
          "Wie findest du's, beim Sex gewürgt zu werden?",
          "Hand am Hals, Haare ziehen, festhalten – worauf stehst du am meisten?",
          "Bist du im Bett eher der dominante oder der devote Typ?",
          "Was ist der mutigste Move, mit dem du schon mal klargemacht hast, dass du wen willst?",
          "Worauf achtest du zuerst, wenn dich jemand richtig anmacht?",
          "Was ist der versauteste Gedanke, den du bei einem guten Date schon hattest?",
          "Beschreib in drei Worten, wie du küsst.",
          "Welchen Kink hast du noch nie einem Partner oder einer Partnerin gebeichtet?",
          "Hast du schon mal jemanden küssen wollen, dich aber zurückgehalten? Was hat dich gestoppt?",
          "Von 1 bis 10 – wie forsch bist du beim ersten Date?",
          "Was ist heißer für dich: langsam und neckend oder direkt und fordernd?",
          "Worauf stehst du, das dich selbst ein bisschen überrascht?",
          "Was war der Moment, in dem du die meiste Spannung gespürt hast?",
          "Wie merkst du, dass jemand dich will?",
          "Was ist das Direkteste, das du je im Bett gesagt hast?",
          "Wovon hast du im Bett schon mal geträumt, es aber nie angesprochen?",
          "Was ist dein Lieblingsmoment kurz bevor etwas passiert?",
          "Küssen oder alles danach — was ist dir wichtiger?",
          "Was macht jemanden für dich unwiderstehlich?",
          "Wie lange hast du mal mit jemandem geflirtet, ohne dass etwas passiert ist?",
          "Was war das Heißeste, das dir jemand ins Ohr geflüstert hat?",
          "Was ist der schnellste Weg, dich anzumachen?",
          "Bei welcher Berührung bist du sofort weg?",
          "Was hast du im Bett schon mal getan, nur weil der andere es wollte?",
          "Was würdest du im Bett gern öfter hören?",
          "Wann hast du zuletzt jemanden nur wegen der Spannung geküsst?",
        ],
      },
    },
    en: {
      general: {
        label: "🎲 General",
        prompts: [
          "What's the most embarrassing thing in your search history?",
          "What's a lie you tell all the time?",
          "Who in this room would you swap lives with for a week?",
          "What's the pettiest reason you've ended a friendship?",
          "What's the worst gift you've ever received?",
          "What's something you pretend to like but secretly hate?",
          "Who in this room have you secretly stalked on social media?",
          "What was your most embarrassing phase as a teenager?",
          "What totally unpopular opinion would you defend to the end?",
          "How much money is actually in your bank account right now — roughly?",
          "What's the biggest lie on your CV?",
          "What song do you secretly play on repeat but would never admit to?",
          "Who in this room would you never lend money to?",
          "What's the most childish thing you still do as an adult?",
          "How long do you really take to reply to a text you've already seen?",
          "Which person from your past would you happily block all over again?",
          "What was your dumbest impulse buy lately?",
          "Who in this room did you completely misjudge at first?",
          "What's the excuse you use most often to cancel plans?",
          "What would you do if you were invisible for a week?",
          "Which dating profile of yours had the most lies on it?",
        ],
      },
      party: {
        label: "🎉 Party",
        prompts: [
          "What's the drunkest you've ever been?",
          "What's the worst thing you've done on a night out?",
          "Who here would you trust least with your phone unlocked?",
          "What's a night out you genuinely don't remember?",
          "What's your most cringe drunk text?",
          "Who in this room have you talked about behind their back?",
          "Who here can hold their drink the worst — honestly?",
          "What's the last thing you ordered or bought while drunk?",
          "Who in this room would you most want to pull an all-nighter with?",
          "What's your most embarrassing moment at a stranger's party?",
          "Who here gets the messiest on the dance floor once the drinks kick in?",
          "Which blackout would you most want to rewind to see what actually happened?",
          "Who in this room have you drunkenly confessed your love to?",
          "What's your most embarrassing morning-after moment (hangover included)?",
          "Who in this room have you had to carry or rescue on a night out?",
          "What's the wildest thing you've done to score free drinks?",
          "Which drunken bet embarrassed you the most?",
          "Who here is secretly the biggest drama magnet at parties?",
          "What's the worst drunk text you've sent an ex?",
          "Who in this room have you hooked up with and regretted it?",
          "Which rumour about you from a party is actually true?",
        ],
      },
      leisure: {
        label: "🏖️ Leisure & Travel",
        prompts: [
          "What's your most embarrassing holiday story?",
          "Which travel destination is totally overrated?",
          "What have you swiped on holiday (hotel towels count)?",
          "Where would you emigrate to right now?",
          "What was your biggest travel disaster?",
          "Who in this room would you most — and never — travel with?",
        ],
      },
      history: {
        label: "🏛️ Politics & History",
        prompts: [
          "Which historical figure would you love to meet?",
          "Which era would you rather have lived in?",
          "Which conspiracy theory do you secretly find a bit plausible?",
          "If you had absolute power for one day, what would you do?",
          "Which school subject was the most useless to you?",
          "Which political topic winds you up the most?",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "What's your body count? (be honest)",
          "What's the wildest place you've hooked up?",
          "Who in this room would you swipe right on?",
          "What's your biggest turn-on?",
          "What's a fantasy you've never told anyone?",
          "What's the kinkiest thing you've ever done?",
          "Who in this room have you thought about naked?",
          "What's your weirdest turn-on?",
          "Describe your last hookup in three words.",
          "What's the most public place you've done it?",
          "Have you ever faked it? With who?",
          "What's the worst thing you've done in bed?",
          "Who was your best ever, and why?",
          "What's a kink you'd actually want to try?",
          "Last thing you searched that you'd be embarrassed by?",
          "Ever hooked up with someone's ex in this room?",
          "What's your best sexting story?",
          "Which body part do people compliment that you personally don't care about?",
          "What's the craziest place you almost got caught?",
          "What roleplay scenario turns you on the most?",
          "What's your most embarrassing moment getting undressed?",
          "What's the one line you most want to hear in bed?",
          "What's something about sex you think is overrated?",
          "How often do you think about sex on a normal day?",
          "What's the fastest you've slept with someone after meeting them?",
          "What's a dating app message that worked on you instantly?",
        ],
      },
      date: {
        label: "🌹 Date",
        prompts: [
          "How do you feel about being choked in bed?",
          "Hand on the throat, hair-pulling, being held down — which one's your favourite?",
          "In bed, are you more the dominant or the submissive type?",
          "What's the boldest move you've made to signal you were into someone?",
          "What do you notice first about someone you're attracted to?",
          "What's the filthiest thought that's crossed your mind on a good date?",
          "Describe how you kiss in three words.",
          "What's a kink you've never told a partner you wanted to try?",
          "Have you ever wanted to kiss someone but held back? What stopped you?",
          "On a scale of 1 to 10, how forward are you on a first date?",
          "What's hotter to you: slow and teasing, or direct and demanding?",
          "What are you into that surprises even you?",
          "What was the moment you felt the most tension with someone?",
          "How can you tell when someone wants you?",
          "What's the most direct thing you've ever said in bed?",
          "What have you fantasised about in bed but never brought up?",
          "What's your favourite moment right before something happens?",
          "Kissing or everything after — which matters more to you?",
          "What makes someone irresistible to you?",
          "What's the longest you've flirted with someone without anything happening?",
          "What's the hottest thing anyone's whispered in your ear?",
          "What's the fastest way to turn you on?",
          "What kind of touch makes you lose it instantly?",
          "What have you done in bed purely because the other person wanted it?",
          "What do you wish you heard more often in bed?",
          "When did you last kiss someone purely because of the tension?",
        ],
      },
    },
    es: {
      general: {
        label: "🎲 General",
        prompts: [
          "¿Qué es lo más vergonzoso de tu historial de búsqueda?",
          "¿Qué mentira dices todo el rato?",
          "¿Con quién de esta sala te cambiarías la vida durante una semana?",
          "¿Cuál es el motivo más mezquino por el que has terminado una amistad?",
          "¿Cuál es el peor regalo que te han hecho?",
          "¿Qué finges que te gusta pero en secreto odias?",
          "¿A quién de esta sala has cotilleado en secreto en redes sociales?",
          "¿Cuál fue tu etapa más vergonzosa de adolescente?",
          "¿Qué opinión totalmente impopular defenderías hasta el final?",
          "¿Cuánto dinero tienes ahora mismo en la cuenta — más o menos?",
          "¿Cuál es la mayor mentira de tu currículum?",
          "¿Qué canción escuchas en bucle en secreto pero nunca lo admitirías?",
          "¿A quién de esta sala nunca le prestarías dinero?",
          "¿Qué es lo más infantil que sigues haciendo de adulto?",
          "¿Cuánto tardas de verdad en contestar un mensaje que ya has visto?",
          "¿A qué persona de tu pasado volverías a bloquear encantado?",
          "¿Cuál ha sido tu compra impulsiva más tonta últimamente?",
          "¿A quién de esta sala juzgaste completamente mal al principio?",
          "¿Qué excusa usas más a menudo para cancelar planes?",
          "¿Qué harías si fueras invisible durante una semana?",
          "¿Cuál de tus perfiles de citas tenía más mentiras?",
        ],
      },
      party: {
        label: "🎉 Fiesta",
        prompts: [
          "¿Cuál es la mayor borrachera que has pillado?",
          "¿Qué es lo peor que has hecho de fiesta?",
          "¿En quién de aquí confiarías menos con tu móvil desbloqueado?",
          "¿Qué noche de fiesta no recuerdas en absoluto?",
          "¿Cuál es tu mensaje de borracho más vergonzoso?",
          "¿De quién de esta sala has hablado a sus espaldas?",
          "¿Quién de aquí aguanta peor el alcohol — sinceramente?",
          "¿Qué es lo último que pediste o compraste estando borracho?",
          "¿Con quién de esta sala te gustaría más pasar la noche en vela?",
          "¿Cuál es tu momento más vergonzoso en la fiesta de un desconocido?",
          "¿Quién de aquí se descontrola más en la pista cuando le hace efecto el alcohol?",
          "¿Qué laguna mental rebobinarías para ver qué pasó de verdad?",
          "¿A quién de esta sala le has declarado tu amor estando borracho?",
          "¿Cuál es tu mañana de después más vergonzosa (resaca incluida)?",
          "¿A quién de esta sala has tenido que cargar o rescatar de fiesta?",
          "¿Qué es lo más loco que has hecho para conseguir copas gratis?",
          "¿Qué apuesta de borracho te dejó más en ridículo?",
          "¿Quién de aquí es en secreto el mayor imán de dramas en las fiestas?",
          "¿Cuál es el peor mensaje de borracho que le has mandado a un ex?",
          "¿Con quién de esta sala te has liado y te has arrepentido?",
          "¿Qué rumor sobre ti de una fiesta es en realidad cierto?",
        ],
      },
      leisure: {
        label: "🏖️ Ocio y viajes",
        prompts: [
          "¿Cuál es tu historia de vacaciones más vergonzosa?",
          "¿Qué destino de viaje está totalmente sobrevalorado?",
          "¿Qué te has llevado de unas vacaciones (las toallas del hotel cuentan)?",
          "¿A dónde emigrarías ahora mismo?",
          "¿Cuál fue tu mayor desastre de viaje?",
          "¿Con quién de esta sala viajarías más a gusto — y con quién nunca?",
        ],
      },
      history: {
        label: "🏛️ Política e historia",
        prompts: [
          "¿Qué personaje histórico te encantaría conocer?",
          "¿En qué época preferirías haber vivido?",
          "¿Qué teoría de la conspiración te parece en secreto un poco creíble?",
          "Si tuvieras poder absoluto durante un día, ¿qué harías?",
          "¿Qué asignatura del cole te resultó más inútil?",
          "¿Qué tema político te saca más de quicio?",
        ],
      },
      nsfw: {
        label: "🔞 18+",
        prompts: [
          "¿Con cuántas personas te has acostado? (sé sincero)",
          "¿Cuál es el sitio más salvaje donde te has liado con alguien?",
          "¿A quién de esta sala le darías like?",
          "¿Qué es lo que más te pone?",
          "¿Qué fantasía no le has contado nunca a nadie?",
          "¿Qué es lo más pervertido que has hecho?",
          "¿A quién de esta sala te has imaginado desnudo?",
          "¿Qué es lo más raro que te pone?",
          "Describe tu último ligue en tres palabras.",
          "¿Cuál es el sitio más público donde lo has hecho?",
          "¿Alguna vez has fingido? ¿Con quién?",
          "¿Qué es lo peor que has hecho en la cama?",
          "¿Quién ha sido el mejor de tu vida y por qué?",
          "¿Qué fetiche te gustaría probar de verdad?",
          "¿Qué es lo último que has buscado que te daría vergüenza?",
          "¿Te has liado alguna vez con el ex de alguien de esta sala?",
          "¿Cuál es tu mejor historia de sexting?",
          "¿Qué parte de tu cuerpo te elogian que a ti personalmente te da igual?",
          "¿Cuál es el sitio más loco donde casi te pillan?",
          "¿Qué juego de rol es el que más te pone?",
          "¿Cuál es tu momento más vergonzoso al desnudarte?",
          "¿Qué frase es la que más te gustaría oír en la cama?",
          "¿Qué cosa del sexo te parece sobrevalorada?",
          "¿Cuántas veces piensas en sexo en un día normal?",
          "¿Qué es lo más rápido que te has acostado con alguien después de conocerlo?",
          "¿Qué mensaje de una app de citas funcionó contigo al instante?",
        ],
      },
      date: {
        label: "🌹 Cita",
        prompts: [
          "¿Qué te parece que te agarren del cuello en la cama?",
          "Mano en el cuello, tirón de pelo, que te sujeten — ¿cuál es tu favorito?",
          "En la cama, ¿eres más dominante o más sumiso?",
          "¿Cuál es el movimiento más atrevido que has hecho para dejar claro que alguien te gustaba?",
          "¿Qué es lo primero en lo que te fijas de alguien que te atrae?",
          "¿Cuál es el pensamiento más guarro que se te ha pasado por la cabeza en una buena cita?",
          "Describe cómo besas en tres palabras.",
          "¿Qué fetiche nunca le has dicho a una pareja que querías probar?",
          "¿Alguna vez has querido besar a alguien y te has contenido? ¿Qué te frenó?",
          "Del 1 al 10, ¿cuánto te lanzas en una primera cita?",
          "¿Qué te pone más: lento y provocador, o directo y exigente?",
          "¿Qué te pone que te sorprende incluso a ti?",
          "¿Cuál fue el momento en que sentiste más tensión con alguien?",
          "¿Cómo sabes cuándo alguien te desea?",
          "¿Qué es lo más directo que has dicho en la cama?",
          "¿Con qué has fantaseado en la cama pero nunca lo has propuesto?",
          "¿Cuál es tu momento favorito justo antes de que pase algo?",
          "Besarse o todo lo que viene después — ¿qué te importa más?",
          "¿Qué hace que alguien te resulte irresistible?",
          "¿Cuánto tiempo has llegado a tontear con alguien sin que pasara nada?",
          "¿Qué es lo más caliente que te han susurrado al oído?",
          "¿Cuál es la forma más rápida de ponerte?",
          "¿Qué tipo de caricia te hace perder la cabeza al instante?",
          "¿Qué has hecho en la cama solo porque la otra persona quería?",
          "¿Qué te gustaría oír más a menudo en la cama?",
          "¿Cuándo fue la última vez que besaste a alguien solo por la tensión?",
        ],
      },
    },
  };

  global.Spielecke = global.Spielecke || {};
  global.Spielecke.TruthQuestions = TRUTH;
})(window);
